package net.chrone.creditpay.model;

import java.util.Date;

public class Account extends ParentMode {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_account.owner_id
	 *
	 * @mbg.generated Thu Nov 16 10:53:39 CST 2017
	 */
	private String ownerId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_account.total
	 *
	 * @mbg.generated Thu Nov 16 10:53:39 CST 2017
	 */
	private Integer total;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_account.available
	 *
	 * @mbg.generated Thu Nov 16 10:53:39 CST 2017
	 */
	private Integer available;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_account.frozen
	 *
	 * @mbg.generated Thu Nov 16 10:53:39 CST 2017
	 */
	private Integer frozen;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_account.untransfer
	 *
	 * @mbg.generated Thu Nov 16 10:53:39 CST 2017
	 */
	private Integer untransfer;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_account.row_crt_ts
	 *
	 * @mbg.generated Thu Nov 16 10:53:39 CST 2017
	 */
	private Date rowCrtTs;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_account.row_crt_usr
	 *
	 * @mbg.generated Thu Nov 16 10:53:39 CST 2017
	 */
	private String rowCrtUsr;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_account.row_upd_ts
	 *
	 * @mbg.generated Thu Nov 16 10:53:39 CST 2017
	 */
	private Date rowUpdTs;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_account.row_upd_usr
	 *
	 * @mbg.generated Thu Nov 16 10:53:39 CST 2017
	 */
	private String rowUpdUsr;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_account.owner_id
	 *
	 * @return the value of t_account.owner_id
	 *
	 * @mbg.generated Thu Nov 16 10:53:39 CST 2017
	 */
	public String getOwnerId() {
		return ownerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_account.owner_id
	 *
	 * @param ownerId
	 *            the value for t_account.owner_id
	 *
	 * @mbg.generated Thu Nov 16 10:53:39 CST 2017
	 */
	public void setOwnerId(String ownerId) {
		this.ownerId = ownerId == null ? null : ownerId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_account.total
	 *
	 * @return the value of t_account.total
	 *
	 * @mbg.generated Thu Nov 16 10:53:39 CST 2017
	 */
	public Integer getTotal() {
		return total;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_account.total
	 *
	 * @param total
	 *            the value for t_account.total
	 *
	 * @mbg.generated Thu Nov 16 10:53:39 CST 2017
	 */
	public void setTotal(Integer total) {
		this.total = total;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_account.available
	 *
	 * @return the value of t_account.available
	 *
	 * @mbg.generated Thu Nov 16 10:53:39 CST 2017
	 */
	public Integer getAvailable() {
		return available;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_account.available
	 *
	 * @param available
	 *            the value for t_account.available
	 *
	 * @mbg.generated Thu Nov 16 10:53:39 CST 2017
	 */
	public void setAvailable(Integer available) {
		this.available = available;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_account.frozen
	 *
	 * @return the value of t_account.frozen
	 *
	 * @mbg.generated Thu Nov 16 10:53:39 CST 2017
	 */
	public Integer getFrozen() {
		return frozen;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_account.frozen
	 *
	 * @param frozen
	 *            the value for t_account.frozen
	 *
	 * @mbg.generated Thu Nov 16 10:53:39 CST 2017
	 */
	public void setFrozen(Integer frozen) {
		this.frozen = frozen;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_account.untransfer
	 *
	 * @return the value of t_account.untransfer
	 *
	 * @mbg.generated Thu Nov 16 10:53:39 CST 2017
	 */
	public Integer getUntransfer() {
		return untransfer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_account.untransfer
	 *
	 * @param untransfer
	 *            the value for t_account.untransfer
	 *
	 * @mbg.generated Thu Nov 16 10:53:39 CST 2017
	 */
	public void setUntransfer(Integer untransfer) {
		this.untransfer = untransfer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_account.row_crt_ts
	 *
	 * @return the value of t_account.row_crt_ts
	 *
	 * @mbg.generated Thu Nov 16 10:53:39 CST 2017
	 */
	public Date getRowCrtTs() {
		return rowCrtTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_account.row_crt_ts
	 *
	 * @param rowCrtTs
	 *            the value for t_account.row_crt_ts
	 *
	 * @mbg.generated Thu Nov 16 10:53:39 CST 2017
	 */
	public void setRowCrtTs(Date rowCrtTs) {
		this.rowCrtTs = rowCrtTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_account.row_crt_usr
	 *
	 * @return the value of t_account.row_crt_usr
	 *
	 * @mbg.generated Thu Nov 16 10:53:39 CST 2017
	 */
	public String getRowCrtUsr() {
		return rowCrtUsr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_account.row_crt_usr
	 *
	 * @param rowCrtUsr
	 *            the value for t_account.row_crt_usr
	 *
	 * @mbg.generated Thu Nov 16 10:53:39 CST 2017
	 */
	public void setRowCrtUsr(String rowCrtUsr) {
		this.rowCrtUsr = rowCrtUsr == null ? null : rowCrtUsr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_account.row_upd_ts
	 *
	 * @return the value of t_account.row_upd_ts
	 *
	 * @mbg.generated Thu Nov 16 10:53:39 CST 2017
	 */
	public Date getRowUpdTs() {
		return rowUpdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_account.row_upd_ts
	 *
	 * @param rowUpdTs
	 *            the value for t_account.row_upd_ts
	 *
	 * @mbg.generated Thu Nov 16 10:53:39 CST 2017
	 */
	public void setRowUpdTs(Date rowUpdTs) {
		this.rowUpdTs = rowUpdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_account.row_upd_usr
	 *
	 * @return the value of t_account.row_upd_usr
	 *
	 * @mbg.generated Thu Nov 16 10:53:39 CST 2017
	 */
	public String getRowUpdUsr() {
		return rowUpdUsr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_account.row_upd_usr
	 *
	 * @param rowUpdUsr
	 *            the value for t_account.row_upd_usr
	 *
	 * @mbg.generated Thu Nov 16 10:53:39 CST 2017
	 */
	public void setRowUpdUsr(String rowUpdUsr) {
		this.rowUpdUsr = rowUpdUsr == null ? null : rowUpdUsr.trim();
	}

	private String userId;
	private Integer orderBy;
	private String accountName;
	private String merName;
	private String levelName;

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public Integer getOrderBy() {
		return orderBy;
	}

	public void setOrderBy(Integer orderBy) {
		this.orderBy = orderBy;
	}

	public String getAccountName() {
		return accountName;
	}

	public void setAccountName(String accountName) {
		this.accountName = accountName;
	}

	public String getMerName() {
		return merName;
	}

	public void setMerName(String merName) {
		this.merName = merName;
	}

	public String getLevelName() {
		return levelName;
	}

	public void setLevelName(String levelName) {
		this.levelName = levelName;
	}

}