package net.chrone.creditpay.model;

import java.util.Date;

public class AgentRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agent_role_inf.agent_id
     *
     * @mbggenerated Thu Nov 23 17:06:36 CST 2017
     */
    private String agentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agent_role_inf.role_id
     *
     * @mbggenerated Thu Nov 23 17:06:36 CST 2017
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agent_role_inf.role_nm
     *
     * @mbggenerated Thu Nov 23 17:06:36 CST 2017
     */
    private String roleNm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agent_role_inf.role_desc
     *
     * @mbggenerated Thu Nov 23 17:06:36 CST 2017
     */
    private String roleDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agent_role_inf.row_crt_usr
     *
     * @mbggenerated Thu Nov 23 17:06:36 CST 2017
     */
    private String rowCrtUsr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agent_role_inf.row_crt_ts
     *
     * @mbggenerated Thu Nov 23 17:06:36 CST 2017
     */
    private Date rowCrtTs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agent_role_inf.rec_upd_usr
     *
     * @mbggenerated Thu Nov 23 17:06:36 CST 2017
     */
    private String recUpdUsr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agent_role_inf.rec_upd_ts
     *
     * @mbggenerated Thu Nov 23 17:06:36 CST 2017
     */
    private Date recUpdTs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agent_role_inf.agent_id
     *
     * @return the value of t_agent_role_inf.agent_id
     *
     * @mbggenerated Thu Nov 23 17:06:36 CST 2017
     */
    public String getAgentId() {
        return agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agent_role_inf.agent_id
     *
     * @param agentId the value for t_agent_role_inf.agent_id
     *
     * @mbggenerated Thu Nov 23 17:06:36 CST 2017
     */
    public void setAgentId(String agentId) {
        this.agentId = agentId == null ? null : agentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agent_role_inf.role_id
     *
     * @return the value of t_agent_role_inf.role_id
     *
     * @mbggenerated Thu Nov 23 17:06:36 CST 2017
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agent_role_inf.role_id
     *
     * @param roleId the value for t_agent_role_inf.role_id
     *
     * @mbggenerated Thu Nov 23 17:06:36 CST 2017
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agent_role_inf.role_nm
     *
     * @return the value of t_agent_role_inf.role_nm
     *
     * @mbggenerated Thu Nov 23 17:06:36 CST 2017
     */
    public String getRoleNm() {
        return roleNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agent_role_inf.role_nm
     *
     * @param roleNm the value for t_agent_role_inf.role_nm
     *
     * @mbggenerated Thu Nov 23 17:06:36 CST 2017
     */
    public void setRoleNm(String roleNm) {
        this.roleNm = roleNm == null ? null : roleNm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agent_role_inf.role_desc
     *
     * @return the value of t_agent_role_inf.role_desc
     *
     * @mbggenerated Thu Nov 23 17:06:36 CST 2017
     */
    public String getRoleDesc() {
        return roleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agent_role_inf.role_desc
     *
     * @param roleDesc the value for t_agent_role_inf.role_desc
     *
     * @mbggenerated Thu Nov 23 17:06:36 CST 2017
     */
    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc == null ? null : roleDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agent_role_inf.row_crt_usr
     *
     * @return the value of t_agent_role_inf.row_crt_usr
     *
     * @mbggenerated Thu Nov 23 17:06:36 CST 2017
     */
    public String getRowCrtUsr() {
        return rowCrtUsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agent_role_inf.row_crt_usr
     *
     * @param rowCrtUsr the value for t_agent_role_inf.row_crt_usr
     *
     * @mbggenerated Thu Nov 23 17:06:36 CST 2017
     */
    public void setRowCrtUsr(String rowCrtUsr) {
        this.rowCrtUsr = rowCrtUsr == null ? null : rowCrtUsr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agent_role_inf.row_crt_ts
     *
     * @return the value of t_agent_role_inf.row_crt_ts
     *
     * @mbggenerated Thu Nov 23 17:06:36 CST 2017
     */
    public Date getRowCrtTs() {
        return rowCrtTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agent_role_inf.row_crt_ts
     *
     * @param rowCrtTs the value for t_agent_role_inf.row_crt_ts
     *
     * @mbggenerated Thu Nov 23 17:06:36 CST 2017
     */
    public void setRowCrtTs(Date rowCrtTs) {
        this.rowCrtTs = rowCrtTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agent_role_inf.rec_upd_usr
     *
     * @return the value of t_agent_role_inf.rec_upd_usr
     *
     * @mbggenerated Thu Nov 23 17:06:36 CST 2017
     */
    public String getRecUpdUsr() {
        return recUpdUsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agent_role_inf.rec_upd_usr
     *
     * @param recUpdUsr the value for t_agent_role_inf.rec_upd_usr
     *
     * @mbggenerated Thu Nov 23 17:06:36 CST 2017
     */
    public void setRecUpdUsr(String recUpdUsr) {
        this.recUpdUsr = recUpdUsr == null ? null : recUpdUsr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agent_role_inf.rec_upd_ts
     *
     * @return the value of t_agent_role_inf.rec_upd_ts
     *
     * @mbggenerated Thu Nov 23 17:06:36 CST 2017
     */
    public Date getRecUpdTs() {
        return recUpdTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agent_role_inf.rec_upd_ts
     *
     * @param recUpdTs the value for t_agent_role_inf.rec_upd_ts
     *
     * @mbggenerated Thu Nov 23 17:06:36 CST 2017
     */
    public void setRecUpdTs(Date recUpdTs) {
        this.recUpdTs = recUpdTs;
    }
}