package net.chrone.creditpay.model;

public class CreditRootBank {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_credit_root_bank.bank_no
     *
     * @mbg.generated Thu Sep 20 18:13:05 CST 2018
     */
    private String bankNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_credit_root_bank.bank_nm
     *
     * @mbg.generated Thu Sep 20 18:13:05 CST 2018
     */
    private String bankNm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_credit_root_bank.bank_no
     *
     * @return the value of t_credit_root_bank.bank_no
     *
     * @mbg.generated Thu Sep 20 18:13:05 CST 2018
     */
    public String getBankNo() {
        return bankNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_credit_root_bank.bank_no
     *
     * @param bankNo the value for t_credit_root_bank.bank_no
     *
     * @mbg.generated Thu Sep 20 18:13:05 CST 2018
     */
    public void setBankNo(String bankNo) {
        this.bankNo = bankNo == null ? null : bankNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_credit_root_bank.bank_nm
     *
     * @return the value of t_credit_root_bank.bank_nm
     *
     * @mbg.generated Thu Sep 20 18:13:05 CST 2018
     */
    public String getBankNm() {
        return bankNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_credit_root_bank.bank_nm
     *
     * @param bankNm the value for t_credit_root_bank.bank_nm
     *
     * @mbg.generated Thu Sep 20 18:13:05 CST 2018
     */
    public void setBankNm(String bankNm) {
        this.bankNm = bankNm == null ? null : bankNm.trim();
    }
}