package net.chrone.creditpay.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FastOrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_fast_order
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_fast_order
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_fast_order
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fast_order
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    public FastOrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fast_order
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fast_order
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fast_order
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fast_order
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fast_order
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fast_order
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fast_order
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fast_order
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fast_order
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fast_order
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_fast_order
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOrderNoIsNull() {
            addCriterion("order_no is null");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNotNull() {
            addCriterion("order_no is not null");
            return (Criteria) this;
        }

        public Criteria andOrderNoEqualTo(String value) {
            addCriterion("order_no =", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotEqualTo(String value) {
            addCriterion("order_no <>", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoGreaterThan(String value) {
            addCriterion("order_no >", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoGreaterThanOrEqualTo(String value) {
            addCriterion("order_no >=", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLessThan(String value) {
            addCriterion("order_no <", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLessThanOrEqualTo(String value) {
            addCriterion("order_no <=", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLike(String value) {
            addCriterion("order_no like", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotLike(String value) {
            addCriterion("order_no not like", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoIn(List<String> values) {
            addCriterion("order_no in", values, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotIn(List<String> values) {
            addCriterion("order_no not in", values, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoBetween(String value1, String value2) {
            addCriterion("order_no between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotBetween(String value1, String value2) {
            addCriterion("order_no not between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderDtIsNull() {
            addCriterion("order_dt is null");
            return (Criteria) this;
        }

        public Criteria andOrderDtIsNotNull() {
            addCriterion("order_dt is not null");
            return (Criteria) this;
        }

        public Criteria andOrderDtEqualTo(String value) {
            addCriterion("order_dt =", value, "orderDt");
            return (Criteria) this;
        }

        public Criteria andOrderDtNotEqualTo(String value) {
            addCriterion("order_dt <>", value, "orderDt");
            return (Criteria) this;
        }

        public Criteria andOrderDtGreaterThan(String value) {
            addCriterion("order_dt >", value, "orderDt");
            return (Criteria) this;
        }

        public Criteria andOrderDtGreaterThanOrEqualTo(String value) {
            addCriterion("order_dt >=", value, "orderDt");
            return (Criteria) this;
        }

        public Criteria andOrderDtLessThan(String value) {
            addCriterion("order_dt <", value, "orderDt");
            return (Criteria) this;
        }

        public Criteria andOrderDtLessThanOrEqualTo(String value) {
            addCriterion("order_dt <=", value, "orderDt");
            return (Criteria) this;
        }

        public Criteria andOrderDtLike(String value) {
            addCriterion("order_dt like", value, "orderDt");
            return (Criteria) this;
        }

        public Criteria andOrderDtNotLike(String value) {
            addCriterion("order_dt not like", value, "orderDt");
            return (Criteria) this;
        }

        public Criteria andOrderDtIn(List<String> values) {
            addCriterion("order_dt in", values, "orderDt");
            return (Criteria) this;
        }

        public Criteria andOrderDtNotIn(List<String> values) {
            addCriterion("order_dt not in", values, "orderDt");
            return (Criteria) this;
        }

        public Criteria andOrderDtBetween(String value1, String value2) {
            addCriterion("order_dt between", value1, value2, "orderDt");
            return (Criteria) this;
        }

        public Criteria andOrderDtNotBetween(String value1, String value2) {
            addCriterion("order_dt not between", value1, value2, "orderDt");
            return (Criteria) this;
        }

        public Criteria andOrderTpIsNull() {
            addCriterion("order_tp is null");
            return (Criteria) this;
        }

        public Criteria andOrderTpIsNotNull() {
            addCriterion("order_tp is not null");
            return (Criteria) this;
        }

        public Criteria andOrderTpEqualTo(Integer value) {
            addCriterion("order_tp =", value, "orderTp");
            return (Criteria) this;
        }

        public Criteria andOrderTpNotEqualTo(Integer value) {
            addCriterion("order_tp <>", value, "orderTp");
            return (Criteria) this;
        }

        public Criteria andOrderTpGreaterThan(Integer value) {
            addCriterion("order_tp >", value, "orderTp");
            return (Criteria) this;
        }

        public Criteria andOrderTpGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_tp >=", value, "orderTp");
            return (Criteria) this;
        }

        public Criteria andOrderTpLessThan(Integer value) {
            addCriterion("order_tp <", value, "orderTp");
            return (Criteria) this;
        }

        public Criteria andOrderTpLessThanOrEqualTo(Integer value) {
            addCriterion("order_tp <=", value, "orderTp");
            return (Criteria) this;
        }

        public Criteria andOrderTpIn(List<Integer> values) {
            addCriterion("order_tp in", values, "orderTp");
            return (Criteria) this;
        }

        public Criteria andOrderTpNotIn(List<Integer> values) {
            addCriterion("order_tp not in", values, "orderTp");
            return (Criteria) this;
        }

        public Criteria andOrderTpBetween(Integer value1, Integer value2) {
            addCriterion("order_tp between", value1, value2, "orderTp");
            return (Criteria) this;
        }

        public Criteria andOrderTpNotBetween(Integer value1, Integer value2) {
            addCriterion("order_tp not between", value1, value2, "orderTp");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andAmountIsNull() {
            addCriterion("amount is null");
            return (Criteria) this;
        }

        public Criteria andAmountIsNotNull() {
            addCriterion("amount is not null");
            return (Criteria) this;
        }

        public Criteria andAmountEqualTo(Integer value) {
            addCriterion("amount =", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotEqualTo(Integer value) {
            addCriterion("amount <>", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThan(Integer value) {
            addCriterion("amount >", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("amount >=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThan(Integer value) {
            addCriterion("amount <", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThanOrEqualTo(Integer value) {
            addCriterion("amount <=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountIn(List<Integer> values) {
            addCriterion("amount in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotIn(List<Integer> values) {
            addCriterion("amount not in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountBetween(Integer value1, Integer value2) {
            addCriterion("amount between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("amount not between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andFeeIsNull() {
            addCriterion("fee is null");
            return (Criteria) this;
        }

        public Criteria andFeeIsNotNull() {
            addCriterion("fee is not null");
            return (Criteria) this;
        }

        public Criteria andFeeEqualTo(Integer value) {
            addCriterion("fee =", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeNotEqualTo(Integer value) {
            addCriterion("fee <>", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeGreaterThan(Integer value) {
            addCriterion("fee >", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeGreaterThanOrEqualTo(Integer value) {
            addCriterion("fee >=", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeLessThan(Integer value) {
            addCriterion("fee <", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeLessThanOrEqualTo(Integer value) {
            addCriterion("fee <=", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeIn(List<Integer> values) {
            addCriterion("fee in", values, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeNotIn(List<Integer> values) {
            addCriterion("fee not in", values, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeBetween(Integer value1, Integer value2) {
            addCriterion("fee between", value1, value2, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeNotBetween(Integer value1, Integer value2) {
            addCriterion("fee not between", value1, value2, "fee");
            return (Criteria) this;
        }

        public Criteria andChnlFeeIsNull() {
            addCriterion("chnl_fee is null");
            return (Criteria) this;
        }

        public Criteria andChnlFeeIsNotNull() {
            addCriterion("chnl_fee is not null");
            return (Criteria) this;
        }

        public Criteria andChnlFeeEqualTo(Integer value) {
            addCriterion("chnl_fee =", value, "chnlFee");
            return (Criteria) this;
        }

        public Criteria andChnlFeeNotEqualTo(Integer value) {
            addCriterion("chnl_fee <>", value, "chnlFee");
            return (Criteria) this;
        }

        public Criteria andChnlFeeGreaterThan(Integer value) {
            addCriterion("chnl_fee >", value, "chnlFee");
            return (Criteria) this;
        }

        public Criteria andChnlFeeGreaterThanOrEqualTo(Integer value) {
            addCriterion("chnl_fee >=", value, "chnlFee");
            return (Criteria) this;
        }

        public Criteria andChnlFeeLessThan(Integer value) {
            addCriterion("chnl_fee <", value, "chnlFee");
            return (Criteria) this;
        }

        public Criteria andChnlFeeLessThanOrEqualTo(Integer value) {
            addCriterion("chnl_fee <=", value, "chnlFee");
            return (Criteria) this;
        }

        public Criteria andChnlFeeIn(List<Integer> values) {
            addCriterion("chnl_fee in", values, "chnlFee");
            return (Criteria) this;
        }

        public Criteria andChnlFeeNotIn(List<Integer> values) {
            addCriterion("chnl_fee not in", values, "chnlFee");
            return (Criteria) this;
        }

        public Criteria andChnlFeeBetween(Integer value1, Integer value2) {
            addCriterion("chnl_fee between", value1, value2, "chnlFee");
            return (Criteria) this;
        }

        public Criteria andChnlFeeNotBetween(Integer value1, Integer value2) {
            addCriterion("chnl_fee not between", value1, value2, "chnlFee");
            return (Criteria) this;
        }

        public Criteria andCardNameIsNull() {
            addCriterion("card_name is null");
            return (Criteria) this;
        }

        public Criteria andCardNameIsNotNull() {
            addCriterion("card_name is not null");
            return (Criteria) this;
        }

        public Criteria andCardNameEqualTo(String value) {
            addCriterion("card_name =", value, "cardName");
            return (Criteria) this;
        }

        public Criteria andCardNameNotEqualTo(String value) {
            addCriterion("card_name <>", value, "cardName");
            return (Criteria) this;
        }

        public Criteria andCardNameGreaterThan(String value) {
            addCriterion("card_name >", value, "cardName");
            return (Criteria) this;
        }

        public Criteria andCardNameGreaterThanOrEqualTo(String value) {
            addCriterion("card_name >=", value, "cardName");
            return (Criteria) this;
        }

        public Criteria andCardNameLessThan(String value) {
            addCriterion("card_name <", value, "cardName");
            return (Criteria) this;
        }

        public Criteria andCardNameLessThanOrEqualTo(String value) {
            addCriterion("card_name <=", value, "cardName");
            return (Criteria) this;
        }

        public Criteria andCardNameLike(String value) {
            addCriterion("card_name like", value, "cardName");
            return (Criteria) this;
        }

        public Criteria andCardNameNotLike(String value) {
            addCriterion("card_name not like", value, "cardName");
            return (Criteria) this;
        }

        public Criteria andCardNameIn(List<String> values) {
            addCriterion("card_name in", values, "cardName");
            return (Criteria) this;
        }

        public Criteria andCardNameNotIn(List<String> values) {
            addCriterion("card_name not in", values, "cardName");
            return (Criteria) this;
        }

        public Criteria andCardNameBetween(String value1, String value2) {
            addCriterion("card_name between", value1, value2, "cardName");
            return (Criteria) this;
        }

        public Criteria andCardNameNotBetween(String value1, String value2) {
            addCriterion("card_name not between", value1, value2, "cardName");
            return (Criteria) this;
        }

        public Criteria andCardNoIsNull() {
            addCriterion("card_no is null");
            return (Criteria) this;
        }

        public Criteria andCardNoIsNotNull() {
            addCriterion("card_no is not null");
            return (Criteria) this;
        }

        public Criteria andCardNoEqualTo(String value) {
            addCriterion("card_no =", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoNotEqualTo(String value) {
            addCriterion("card_no <>", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoGreaterThan(String value) {
            addCriterion("card_no >", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoGreaterThanOrEqualTo(String value) {
            addCriterion("card_no >=", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoLessThan(String value) {
            addCriterion("card_no <", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoLessThanOrEqualTo(String value) {
            addCriterion("card_no <=", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoLike(String value) {
            addCriterion("card_no like", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoNotLike(String value) {
            addCriterion("card_no not like", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoIn(List<String> values) {
            addCriterion("card_no in", values, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoNotIn(List<String> values) {
            addCriterion("card_no not in", values, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoBetween(String value1, String value2) {
            addCriterion("card_no between", value1, value2, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoNotBetween(String value1, String value2) {
            addCriterion("card_no not between", value1, value2, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardIdIsNull() {
            addCriterion("card_id is null");
            return (Criteria) this;
        }

        public Criteria andCardIdIsNotNull() {
            addCriterion("card_id is not null");
            return (Criteria) this;
        }

        public Criteria andCardIdEqualTo(String value) {
            addCriterion("card_id =", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdNotEqualTo(String value) {
            addCriterion("card_id <>", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdGreaterThan(String value) {
            addCriterion("card_id >", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdGreaterThanOrEqualTo(String value) {
            addCriterion("card_id >=", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdLessThan(String value) {
            addCriterion("card_id <", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdLessThanOrEqualTo(String value) {
            addCriterion("card_id <=", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdLike(String value) {
            addCriterion("card_id like", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdNotLike(String value) {
            addCriterion("card_id not like", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdIn(List<String> values) {
            addCriterion("card_id in", values, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdNotIn(List<String> values) {
            addCriterion("card_id not in", values, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdBetween(String value1, String value2) {
            addCriterion("card_id between", value1, value2, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdNotBetween(String value1, String value2) {
            addCriterion("card_id not between", value1, value2, "cardId");
            return (Criteria) this;
        }

        public Criteria andBankNoIsNull() {
            addCriterion("bank_no is null");
            return (Criteria) this;
        }

        public Criteria andBankNoIsNotNull() {
            addCriterion("bank_no is not null");
            return (Criteria) this;
        }

        public Criteria andBankNoEqualTo(String value) {
            addCriterion("bank_no =", value, "bankNo");
            return (Criteria) this;
        }

        public Criteria andBankNoNotEqualTo(String value) {
            addCriterion("bank_no <>", value, "bankNo");
            return (Criteria) this;
        }

        public Criteria andBankNoGreaterThan(String value) {
            addCriterion("bank_no >", value, "bankNo");
            return (Criteria) this;
        }

        public Criteria andBankNoGreaterThanOrEqualTo(String value) {
            addCriterion("bank_no >=", value, "bankNo");
            return (Criteria) this;
        }

        public Criteria andBankNoLessThan(String value) {
            addCriterion("bank_no <", value, "bankNo");
            return (Criteria) this;
        }

        public Criteria andBankNoLessThanOrEqualTo(String value) {
            addCriterion("bank_no <=", value, "bankNo");
            return (Criteria) this;
        }

        public Criteria andBankNoLike(String value) {
            addCriterion("bank_no like", value, "bankNo");
            return (Criteria) this;
        }

        public Criteria andBankNoNotLike(String value) {
            addCriterion("bank_no not like", value, "bankNo");
            return (Criteria) this;
        }

        public Criteria andBankNoIn(List<String> values) {
            addCriterion("bank_no in", values, "bankNo");
            return (Criteria) this;
        }

        public Criteria andBankNoNotIn(List<String> values) {
            addCriterion("bank_no not in", values, "bankNo");
            return (Criteria) this;
        }

        public Criteria andBankNoBetween(String value1, String value2) {
            addCriterion("bank_no between", value1, value2, "bankNo");
            return (Criteria) this;
        }

        public Criteria andBankNoNotBetween(String value1, String value2) {
            addCriterion("bank_no not between", value1, value2, "bankNo");
            return (Criteria) this;
        }

        public Criteria andPayStIsNull() {
            addCriterion("pay_st is null");
            return (Criteria) this;
        }

        public Criteria andPayStIsNotNull() {
            addCriterion("pay_st is not null");
            return (Criteria) this;
        }

        public Criteria andPayStEqualTo(Integer value) {
            addCriterion("pay_st =", value, "paySt");
            return (Criteria) this;
        }

        public Criteria andPayStNotEqualTo(Integer value) {
            addCriterion("pay_st <>", value, "paySt");
            return (Criteria) this;
        }

        public Criteria andPayStGreaterThan(Integer value) {
            addCriterion("pay_st >", value, "paySt");
            return (Criteria) this;
        }

        public Criteria andPayStGreaterThanOrEqualTo(Integer value) {
            addCriterion("pay_st >=", value, "paySt");
            return (Criteria) this;
        }

        public Criteria andPayStLessThan(Integer value) {
            addCriterion("pay_st <", value, "paySt");
            return (Criteria) this;
        }

        public Criteria andPayStLessThanOrEqualTo(Integer value) {
            addCriterion("pay_st <=", value, "paySt");
            return (Criteria) this;
        }

        public Criteria andPayStIn(List<Integer> values) {
            addCriterion("pay_st in", values, "paySt");
            return (Criteria) this;
        }

        public Criteria andPayStNotIn(List<Integer> values) {
            addCriterion("pay_st not in", values, "paySt");
            return (Criteria) this;
        }

        public Criteria andPayStBetween(Integer value1, Integer value2) {
            addCriterion("pay_st between", value1, value2, "paySt");
            return (Criteria) this;
        }

        public Criteria andPayStNotBetween(Integer value1, Integer value2) {
            addCriterion("pay_st not between", value1, value2, "paySt");
            return (Criteria) this;
        }

        public Criteria andChnlOrderNoIsNull() {
            addCriterion("chnl_order_no is null");
            return (Criteria) this;
        }

        public Criteria andChnlOrderNoIsNotNull() {
            addCriterion("chnl_order_no is not null");
            return (Criteria) this;
        }

        public Criteria andChnlOrderNoEqualTo(String value) {
            addCriterion("chnl_order_no =", value, "chnlOrderNo");
            return (Criteria) this;
        }

        public Criteria andChnlOrderNoNotEqualTo(String value) {
            addCriterion("chnl_order_no <>", value, "chnlOrderNo");
            return (Criteria) this;
        }

        public Criteria andChnlOrderNoGreaterThan(String value) {
            addCriterion("chnl_order_no >", value, "chnlOrderNo");
            return (Criteria) this;
        }

        public Criteria andChnlOrderNoGreaterThanOrEqualTo(String value) {
            addCriterion("chnl_order_no >=", value, "chnlOrderNo");
            return (Criteria) this;
        }

        public Criteria andChnlOrderNoLessThan(String value) {
            addCriterion("chnl_order_no <", value, "chnlOrderNo");
            return (Criteria) this;
        }

        public Criteria andChnlOrderNoLessThanOrEqualTo(String value) {
            addCriterion("chnl_order_no <=", value, "chnlOrderNo");
            return (Criteria) this;
        }

        public Criteria andChnlOrderNoLike(String value) {
            addCriterion("chnl_order_no like", value, "chnlOrderNo");
            return (Criteria) this;
        }

        public Criteria andChnlOrderNoNotLike(String value) {
            addCriterion("chnl_order_no not like", value, "chnlOrderNo");
            return (Criteria) this;
        }

        public Criteria andChnlOrderNoIn(List<String> values) {
            addCriterion("chnl_order_no in", values, "chnlOrderNo");
            return (Criteria) this;
        }

        public Criteria andChnlOrderNoNotIn(List<String> values) {
            addCriterion("chnl_order_no not in", values, "chnlOrderNo");
            return (Criteria) this;
        }

        public Criteria andChnlOrderNoBetween(String value1, String value2) {
            addCriterion("chnl_order_no between", value1, value2, "chnlOrderNo");
            return (Criteria) this;
        }

        public Criteria andChnlOrderNoNotBetween(String value1, String value2) {
            addCriterion("chnl_order_no not between", value1, value2, "chnlOrderNo");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeIsNull() {
            addCriterion("pay_time is null");
            return (Criteria) this;
        }

        public Criteria andPayTimeIsNotNull() {
            addCriterion("pay_time is not null");
            return (Criteria) this;
        }

        public Criteria andPayTimeEqualTo(Date value) {
            addCriterion("pay_time =", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeNotEqualTo(Date value) {
            addCriterion("pay_time <>", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeGreaterThan(Date value) {
            addCriterion("pay_time >", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("pay_time >=", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeLessThan(Date value) {
            addCriterion("pay_time <", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeLessThanOrEqualTo(Date value) {
            addCriterion("pay_time <=", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeIn(List<Date> values) {
            addCriterion("pay_time in", values, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeNotIn(List<Date> values) {
            addCriterion("pay_time not in", values, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeBetween(Date value1, Date value2) {
            addCriterion("pay_time between", value1, value2, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeNotBetween(Date value1, Date value2) {
            addCriterion("pay_time not between", value1, value2, "payTime");
            return (Criteria) this;
        }

        public Criteria andSettleOrderNoIsNull() {
            addCriterion("settle_order_no is null");
            return (Criteria) this;
        }

        public Criteria andSettleOrderNoIsNotNull() {
            addCriterion("settle_order_no is not null");
            return (Criteria) this;
        }

        public Criteria andSettleOrderNoEqualTo(String value) {
            addCriterion("settle_order_no =", value, "settleOrderNo");
            return (Criteria) this;
        }

        public Criteria andSettleOrderNoNotEqualTo(String value) {
            addCriterion("settle_order_no <>", value, "settleOrderNo");
            return (Criteria) this;
        }

        public Criteria andSettleOrderNoGreaterThan(String value) {
            addCriterion("settle_order_no >", value, "settleOrderNo");
            return (Criteria) this;
        }

        public Criteria andSettleOrderNoGreaterThanOrEqualTo(String value) {
            addCriterion("settle_order_no >=", value, "settleOrderNo");
            return (Criteria) this;
        }

        public Criteria andSettleOrderNoLessThan(String value) {
            addCriterion("settle_order_no <", value, "settleOrderNo");
            return (Criteria) this;
        }

        public Criteria andSettleOrderNoLessThanOrEqualTo(String value) {
            addCriterion("settle_order_no <=", value, "settleOrderNo");
            return (Criteria) this;
        }

        public Criteria andSettleOrderNoLike(String value) {
            addCriterion("settle_order_no like", value, "settleOrderNo");
            return (Criteria) this;
        }

        public Criteria andSettleOrderNoNotLike(String value) {
            addCriterion("settle_order_no not like", value, "settleOrderNo");
            return (Criteria) this;
        }

        public Criteria andSettleOrderNoIn(List<String> values) {
            addCriterion("settle_order_no in", values, "settleOrderNo");
            return (Criteria) this;
        }

        public Criteria andSettleOrderNoNotIn(List<String> values) {
            addCriterion("settle_order_no not in", values, "settleOrderNo");
            return (Criteria) this;
        }

        public Criteria andSettleOrderNoBetween(String value1, String value2) {
            addCriterion("settle_order_no between", value1, value2, "settleOrderNo");
            return (Criteria) this;
        }

        public Criteria andSettleOrderNoNotBetween(String value1, String value2) {
            addCriterion("settle_order_no not between", value1, value2, "settleOrderNo");
            return (Criteria) this;
        }

        public Criteria andChnlIdIsNull() {
            addCriterion("chnl_id is null");
            return (Criteria) this;
        }

        public Criteria andChnlIdIsNotNull() {
            addCriterion("chnl_id is not null");
            return (Criteria) this;
        }

        public Criteria andChnlIdEqualTo(String value) {
            addCriterion("chnl_id =", value, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdNotEqualTo(String value) {
            addCriterion("chnl_id <>", value, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdGreaterThan(String value) {
            addCriterion("chnl_id >", value, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdGreaterThanOrEqualTo(String value) {
            addCriterion("chnl_id >=", value, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdLessThan(String value) {
            addCriterion("chnl_id <", value, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdLessThanOrEqualTo(String value) {
            addCriterion("chnl_id <=", value, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdLike(String value) {
            addCriterion("chnl_id like", value, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdNotLike(String value) {
            addCriterion("chnl_id not like", value, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdIn(List<String> values) {
            addCriterion("chnl_id in", values, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdNotIn(List<String> values) {
            addCriterion("chnl_id not in", values, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdBetween(String value1, String value2) {
            addCriterion("chnl_id between", value1, value2, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdNotBetween(String value1, String value2) {
            addCriterion("chnl_id not between", value1, value2, "chnlId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_fast_order
     *
     * @mbg.generated do_not_delete_during_merge Tue Jan 09 15:08:53 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_fast_order
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}