package net.chrone.creditpay.model;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.apache.commons.lang3.StringUtils;

public class FastOrder extends ParentMode{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fast_order.order_no
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fast_order.order_dt
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    private String orderDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fast_order.order_tp
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    private Integer orderTp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fast_order.user_id
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fast_order.amount
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fast_order.fee
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    private Integer fee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fast_order.chnl_fee
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    private Integer chnlFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fast_order.card_name
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    private String cardName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fast_order.card_no
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    private String cardNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fast_order.card_id
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    private String cardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fast_order.bank_no
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    private String bankNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fast_order.pay_st
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    private Integer paySt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fast_order.chnl_order_no
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    private String chnlOrderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fast_order.create_time
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fast_order.pay_time
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    private Date payTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fast_order.settle_order_no
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    private String settleOrderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fast_order.chnl_id
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    private String chnlId;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_fast_order.memo
    *
    * @mbg.generated Mon Aug 06 16:17:57 CST 2018
    */
   private String memo;
   
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fast_order.order_no
     *
     * @return the value of t_fast_order.order_no
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fast_order.order_no
     *
     * @param orderNo the value for t_fast_order.order_no
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fast_order.order_dt
     *
     * @return the value of t_fast_order.order_dt
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    public String getOrderDt() {
        return orderDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fast_order.order_dt
     *
     * @param orderDt the value for t_fast_order.order_dt
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    public void setOrderDt(String orderDt) {
        this.orderDt = orderDt == null ? null : orderDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fast_order.order_tp
     *
     * @return the value of t_fast_order.order_tp
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    public Integer getOrderTp() {
        return orderTp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fast_order.order_tp
     *
     * @param orderTp the value for t_fast_order.order_tp
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    public void setOrderTp(Integer orderTp) {
        this.orderTp = orderTp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fast_order.user_id
     *
     * @return the value of t_fast_order.user_id
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fast_order.user_id
     *
     * @param userId the value for t_fast_order.user_id
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fast_order.amount
     *
     * @return the value of t_fast_order.amount
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fast_order.amount
     *
     * @param amount the value for t_fast_order.amount
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fast_order.fee
     *
     * @return the value of t_fast_order.fee
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    public Integer getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fast_order.fee
     *
     * @param fee the value for t_fast_order.fee
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    public void setFee(Integer fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fast_order.chnl_fee
     *
     * @return the value of t_fast_order.chnl_fee
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    public Integer getChnlFee() {
        return chnlFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fast_order.chnl_fee
     *
     * @param chnlFee the value for t_fast_order.chnl_fee
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    public void setChnlFee(Integer chnlFee) {
        this.chnlFee = chnlFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fast_order.card_name
     *
     * @return the value of t_fast_order.card_name
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    public String getCardName() {
        return cardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fast_order.card_name
     *
     * @param cardName the value for t_fast_order.card_name
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    public void setCardName(String cardName) {
        this.cardName = cardName == null ? null : cardName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fast_order.card_no
     *
     * @return the value of t_fast_order.card_no
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fast_order.card_no
     *
     * @param cardNo the value for t_fast_order.card_no
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fast_order.card_id
     *
     * @return the value of t_fast_order.card_id
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    public String getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fast_order.card_id
     *
     * @param cardId the value for t_fast_order.card_id
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    public void setCardId(String cardId) {
        this.cardId = cardId == null ? null : cardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fast_order.bank_no
     *
     * @return the value of t_fast_order.bank_no
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    public String getBankNo() {
        return bankNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fast_order.bank_no
     *
     * @param bankNo the value for t_fast_order.bank_no
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    public void setBankNo(String bankNo) {
        this.bankNo = bankNo == null ? null : bankNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fast_order.pay_st
     *
     * @return the value of t_fast_order.pay_st
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    public Integer getPaySt() {
        return paySt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fast_order.pay_st
     *
     * @param paySt the value for t_fast_order.pay_st
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    public void setPaySt(Integer paySt) {
        this.paySt = paySt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fast_order.chnl_order_no
     *
     * @return the value of t_fast_order.chnl_order_no
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    public String getChnlOrderNo() {
        return chnlOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fast_order.chnl_order_no
     *
     * @param chnlOrderNo the value for t_fast_order.chnl_order_no
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    public void setChnlOrderNo(String chnlOrderNo) {
        this.chnlOrderNo = chnlOrderNo == null ? null : chnlOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fast_order.create_time
     *
     * @return the value of t_fast_order.create_time
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fast_order.create_time
     *
     * @param createTime the value for t_fast_order.create_time
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fast_order.pay_time
     *
     * @return the value of t_fast_order.pay_time
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fast_order.pay_time
     *
     * @param payTime the value for t_fast_order.pay_time
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fast_order.settle_order_no
     *
     * @return the value of t_fast_order.settle_order_no
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    public String getSettleOrderNo() {
        return settleOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fast_order.settle_order_no
     *
     * @param settleOrderNo the value for t_fast_order.settle_order_no
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    public void setSettleOrderNo(String settleOrderNo) {
        this.settleOrderNo = settleOrderNo == null ? null : settleOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fast_order.chnl_id
     *
     * @return the value of t_fast_order.chnl_id
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    public String getChnlId() {
        return chnlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fast_order.chnl_id
     *
     * @param chnlId the value for t_fast_order.chnl_id
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    public void setChnlId(String chnlId) {
        this.chnlId = chnlId == null ? null : chnlId.trim();
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fast_order.memo
     *
     * @return the value of t_fast_order.memo
     *
     * @mbg.generated Mon Aug 06 16:17:57 CST 2018
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fast_order.memo
     *
     * @param memo the value for t_fast_order.memo
     *
     * @mbg.generated Mon Aug 06 16:17:57 CST 2018
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }
    
	private String transMessage;
	private Integer payFee;
	private Integer chnlPayFee;
	private String reserve1;
	private String reserve2;
	
	
    
    private String chnlName;
    
    private Integer startAmt;
	private Integer endAmt;
	private String startAmtStr;
	private String endAmtStr;
	
	private String channel;
	private String paySmsCode;
	private int userProfits;
	private int agentProfits;
	private String userCertNo;
	
	private String agentId;
	private String agentName;

	private List<String> agentIds;
	
	public List<String> getAgentIds() {
		return agentIds;
	}

	public void setAgentIds(List<String> agentIds) {
		this.agentIds = agentIds;
	}

	public Integer getChnlPayFee() {
		return chnlPayFee;
	}

	public void setChnlPayFee(Integer chnlPayFee) {
		this.chnlPayFee = chnlPayFee;
	}

	public String getReserve1() {
		return reserve1;
	}

	public void setReserve1(String reserve1) {
		this.reserve1 = reserve1;
	}

	public String getReserve2() {
		return reserve2;
	}

	public void setReserve2(String reserve2) {
		this.reserve2 = reserve2;
	}

	public Integer getPayFee() {
		return payFee;
	}

	public void setPayFee(Integer payFee) {
		this.payFee = payFee;
	}

	public String getTransMessage() {
		return transMessage;
	}

	public void setTransMessage(String transMessage) {
		this.transMessage = transMessage;
	}

	public String getAgentId() {
		return agentId;
	}

	public void setAgentId(String agentId) {
		this.agentId = agentId;
	}

	public String getAgentName() {
		return agentName;
	}

	public void setAgentName(String agentName) {
		this.agentName = agentName;
	}

	public String getUserCertNo() {
		return userCertNo;
	}

	public void setUserCertNo(String userCertNo) {
		this.userCertNo = userCertNo;
	}

	public int getUserProfits() {
		return userProfits;
	}

	public void setUserProfits(int userProfits) {
		this.userProfits = userProfits;
	}

	public int getAgentProfits() {
		return agentProfits;
	}

	public void setAgentProfits(int agentProfits) {
		this.agentProfits = agentProfits;
	}

	public String getChannel() {
		return channel;
	}

	public void setChannel(String channel) {
		this.channel = channel;
	}

	public String getPaySmsCode() {
		return paySmsCode;
	}

	public void setPaySmsCode(String paySmsCode) {
		this.paySmsCode = paySmsCode;
	}

	public void setStartAmt(Integer startAmt) {
		this.startAmt = startAmt;
	}

	public void setEndAmt(Integer endAmt) {
		this.endAmt = endAmt;
	}

	public String getStartAmtStr() {
		return startAmtStr;
	}

	public void setStartAmtStr(String startAmtStr) {
		this.startAmtStr = startAmtStr;
	}

	public String getEndAmtStr() {
		return endAmtStr;
	}

	public void setEndAmtStr(String endAmtStr) {
		this.endAmtStr = endAmtStr;
	}

	public String getChnlName() {
		return chnlName;
	}

	public void setChnlName(String chnlName) {
		this.chnlName = chnlName;
	}
	public Integer getStartAmt() {
		if(StringUtils.isNotEmpty(startAmtStr)){
			return new BigDecimal(startAmtStr).multiply(new BigDecimal(100)).intValue();
		}
		return startAmt;
	}

	public Integer getEndAmt() {
		if(StringUtils.isNotEmpty(endAmtStr)){
			return new BigDecimal(endAmtStr).multiply(new BigDecimal(100)).intValue();
		}
		return endAmt;
	}
    
    
}