package net.chrone.creditpay.model;

import java.io.UnsupportedEncodingException;

public class Information extends ParentMode{
	
	private static final long serialVersionUID = 1L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_information.info_id
     *
     * @mbg.generated Wed Jul 10 11:49:47 CST 2019
     */
    private String infoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_information.title
     *
     * @mbg.generated Wed Jul 10 11:49:47 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_information.title_name
     *
     * @mbg.generated Wed Jul 10 11:49:47 CST 2019
     */
    private String titleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_information.title_img
     *
     * @mbg.generated Wed Jul 10 11:49:47 CST 2019
     */
    private String titleImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_information.status
     *
     * @mbg.generated Wed Jul 10 11:49:47 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_information.content
     *
     * @mbg.generated Wed Jul 10 11:49:47 CST 2019
     */
    private byte[] content;
    
    private String contentStr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_information.info_id
     *
     * @return the value of t_information.info_id
     *
     * @mbg.generated Wed Jul 10 11:49:47 CST 2019
     */
    public String getInfoId() {
        return infoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_information.info_id
     *
     * @param infoId the value for t_information.info_id
     *
     * @mbg.generated Wed Jul 10 11:49:47 CST 2019
     */
    public void setInfoId(String infoId) {
        this.infoId = infoId == null ? null : infoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_information.title
     *
     * @return the value of t_information.title
     *
     * @mbg.generated Wed Jul 10 11:49:47 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_information.title
     *
     * @param title the value for t_information.title
     *
     * @mbg.generated Wed Jul 10 11:49:47 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_information.title_name
     *
     * @return the value of t_information.title_name
     *
     * @mbg.generated Wed Jul 10 11:49:47 CST 2019
     */
    public String getTitleName() {
        return titleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_information.title_name
     *
     * @param titleName the value for t_information.title_name
     *
     * @mbg.generated Wed Jul 10 11:49:47 CST 2019
     */
    public void setTitleName(String titleName) {
        this.titleName = titleName == null ? null : titleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_information.title_img
     *
     * @return the value of t_information.title_img
     *
     * @mbg.generated Wed Jul 10 11:49:47 CST 2019
     */
    public String getTitleImg() {
        return titleImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_information.title_img
     *
     * @param titleImg the value for t_information.title_img
     *
     * @mbg.generated Wed Jul 10 11:49:47 CST 2019
     */
    public void setTitleImg(String titleImg) {
        this.titleImg = titleImg == null ? null : titleImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_information.status
     *
     * @return the value of t_information.status
     *
     * @mbg.generated Wed Jul 10 11:49:47 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_information.status
     *
     * @param status the value for t_information.status
     *
     * @mbg.generated Wed Jul 10 11:49:47 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_information.content
     *
     * @return the value of t_information.content
     *
     * @mbg.generated Wed Jul 10 11:49:47 CST 2019
     */
    public byte[] getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_information.content
     *
     * @param content the value for t_information.content
     *
     * @mbg.generated Wed Jul 10 11:49:47 CST 2019
     */
    public void setContent(byte[] content) {
        this.content = content;
        try {
			this.contentStr=new String(content,"UTF-8");
		} catch (UnsupportedEncodingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }

	public String getContentStr() {
		return contentStr;
	}

	public void setContentStr(String contentStr) {
		this.contentStr = contentStr;
	}
}