package net.chrone.creditpay.model;

import java.util.Date;

public class LevelOrder extends ParentMode{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_level_order.order_no
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_level_order.order_dt
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    private String orderDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_level_order.user_id
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_level_order.user_name
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_level_order.amount
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_level_order.the_level
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    private Integer theLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_level_order.end_level
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    private Integer endLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_level_order.pay_st
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    private Integer paySt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_level_order.pay_time
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    private Date payTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_level_order.chnl_order_no
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    private String chnlOrderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_level_order.row_crt_usr
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    private String rowCrtUsr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_level_order.row_crt_ts
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    private Date rowCrtTs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_level_order.rec_upd_usr
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    private String recUpdUsr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_level_order.rec_upd_ts
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    private Date recUpdTs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_level_order.order_no
     *
     * @return the value of t_level_order.order_no
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_level_order.order_no
     *
     * @param orderNo the value for t_level_order.order_no
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_level_order.order_dt
     *
     * @return the value of t_level_order.order_dt
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public String getOrderDt() {
        return orderDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_level_order.order_dt
     *
     * @param orderDt the value for t_level_order.order_dt
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public void setOrderDt(String orderDt) {
        this.orderDt = orderDt == null ? null : orderDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_level_order.user_id
     *
     * @return the value of t_level_order.user_id
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_level_order.user_id
     *
     * @param userId the value for t_level_order.user_id
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_level_order.user_name
     *
     * @return the value of t_level_order.user_name
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_level_order.user_name
     *
     * @param userName the value for t_level_order.user_name
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_level_order.amount
     *
     * @return the value of t_level_order.amount
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_level_order.amount
     *
     * @param amount the value for t_level_order.amount
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_level_order.the_level
     *
     * @return the value of t_level_order.the_level
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public Integer getTheLevel() {
        return theLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_level_order.the_level
     *
     * @param theLevel the value for t_level_order.the_level
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public void setTheLevel(Integer theLevel) {
        this.theLevel = theLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_level_order.end_level
     *
     * @return the value of t_level_order.end_level
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public Integer getEndLevel() {
        return endLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_level_order.end_level
     *
     * @param endLevel the value for t_level_order.end_level
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public void setEndLevel(Integer endLevel) {
        this.endLevel = endLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_level_order.pay_st
     *
     * @return the value of t_level_order.pay_st
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public Integer getPaySt() {
        return paySt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_level_order.pay_st
     *
     * @param paySt the value for t_level_order.pay_st
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public void setPaySt(Integer paySt) {
        this.paySt = paySt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_level_order.pay_time
     *
     * @return the value of t_level_order.pay_time
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_level_order.pay_time
     *
     * @param payTime the value for t_level_order.pay_time
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_level_order.chnl_order_no
     *
     * @return the value of t_level_order.chnl_order_no
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public String getChnlOrderNo() {
        return chnlOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_level_order.chnl_order_no
     *
     * @param chnlOrderNo the value for t_level_order.chnl_order_no
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public void setChnlOrderNo(String chnlOrderNo) {
        this.chnlOrderNo = chnlOrderNo == null ? null : chnlOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_level_order.row_crt_usr
     *
     * @return the value of t_level_order.row_crt_usr
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public String getRowCrtUsr() {
        return rowCrtUsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_level_order.row_crt_usr
     *
     * @param rowCrtUsr the value for t_level_order.row_crt_usr
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public void setRowCrtUsr(String rowCrtUsr) {
        this.rowCrtUsr = rowCrtUsr == null ? null : rowCrtUsr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_level_order.row_crt_ts
     *
     * @return the value of t_level_order.row_crt_ts
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public Date getRowCrtTs() {
        return rowCrtTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_level_order.row_crt_ts
     *
     * @param rowCrtTs the value for t_level_order.row_crt_ts
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public void setRowCrtTs(Date rowCrtTs) {
        this.rowCrtTs = rowCrtTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_level_order.rec_upd_usr
     *
     * @return the value of t_level_order.rec_upd_usr
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public String getRecUpdUsr() {
        return recUpdUsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_level_order.rec_upd_usr
     *
     * @param recUpdUsr the value for t_level_order.rec_upd_usr
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public void setRecUpdUsr(String recUpdUsr) {
        this.recUpdUsr = recUpdUsr == null ? null : recUpdUsr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_level_order.rec_upd_ts
     *
     * @return the value of t_level_order.rec_upd_ts
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public Date getRecUpdTs() {
        return recUpdTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_level_order.rec_upd_ts
     *
     * @param recUpdTs the value for t_level_order.rec_upd_ts
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public void setRecUpdTs(Date recUpdTs) {
        this.recUpdTs = recUpdTs;
    }
}