package net.chrone.creditpay.model;

import java.math.BigDecimal;
import java.util.Date;

public class LevelFeeRate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_level_fee_rate.id
     *
     * @mbg.generated Wed Apr 25 16:59:41 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_level_fee_rate.level_id
     *
     * @mbg.generated Wed Apr 25 16:59:41 CST 2018
     */
    private Integer levelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_level_fee_rate.trans_type
     *
     * @mbg.generated Wed Apr 25 16:59:41 CST 2018
     */
    private Integer transType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_level_fee_rate.status
     *
     * @mbg.generated Wed Apr 25 16:59:41 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_level_fee_rate.settle_type
     *
     * @mbg.generated Wed Apr 25 16:59:41 CST 2018
     */
    private Integer settleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_level_fee_rate.integral_type
     *
     * @mbg.generated Wed Apr 25 16:59:41 CST 2018
     */
    private Integer integralType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_level_fee_rate.fee_rate
     *
     * @mbg.generated Wed Apr 25 16:59:41 CST 2018
     */
    private BigDecimal feeRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_level_fee_rate.upperlimit
     *
     * @mbg.generated Wed Apr 25 16:59:41 CST 2018
     */
    private Integer upperlimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_level_fee_rate.pay_fee
     *
     * @mbg.generated Wed Apr 25 16:59:41 CST 2018
     */
    private Integer payFee;
	
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_level_fee_rate.pay_chnl_code
     *
     * @mbg.generated Wed Aug 08 18:06:51 CST 2018
     */
    private String payChnlCode;
	

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_level_fee_rate.row_crt_usr
     *
     * @mbg.generated Wed Apr 25 16:59:41 CST 2018
     */
    private String rowCrtUsr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_level_fee_rate.row_crt_ts
     *
     * @mbg.generated Wed Apr 25 16:59:41 CST 2018
     */
    private Date rowCrtTs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_level_fee_rate.rec_upd_usr
     *
     * @mbg.generated Wed Apr 25 16:59:41 CST 2018
     */
    private String recUpdUsr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_level_fee_rate.rec_upd_ts
     *
     * @mbg.generated Wed Apr 25 16:59:41 CST 2018
     */
    private Date recUpdTs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_level_fee_rate.id
     *
     * @return the value of t_level_fee_rate.id
     *
     * @mbg.generated Wed Apr 25 16:59:41 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_level_fee_rate.id
     *
     * @param id the value for t_level_fee_rate.id
     *
     * @mbg.generated Wed Apr 25 16:59:41 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_level_fee_rate.level_id
     *
     * @return the value of t_level_fee_rate.level_id
     *
     * @mbg.generated Wed Apr 25 16:59:41 CST 2018
     */
    public Integer getLevelId() {
        return levelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_level_fee_rate.level_id
     *
     * @param levelId the value for t_level_fee_rate.level_id
     *
     * @mbg.generated Wed Apr 25 16:59:41 CST 2018
     */
    public void setLevelId(Integer levelId) {
        this.levelId = levelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_level_fee_rate.trans_type
     *
     * @return the value of t_level_fee_rate.trans_type
     *
     * @mbg.generated Wed Apr 25 16:59:41 CST 2018
     */
    public Integer getTransType() {
        return transType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_level_fee_rate.trans_type
     *
     * @param transType the value for t_level_fee_rate.trans_type
     *
     * @mbg.generated Wed Apr 25 16:59:41 CST 2018
     */
    public void setTransType(Integer transType) {
        this.transType = transType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_level_fee_rate.status
     *
     * @return the value of t_level_fee_rate.status
     *
     * @mbg.generated Wed Apr 25 16:59:41 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_level_fee_rate.status
     *
     * @param status the value for t_level_fee_rate.status
     *
     * @mbg.generated Wed Apr 25 16:59:41 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_level_fee_rate.settle_type
     *
     * @return the value of t_level_fee_rate.settle_type
     *
     * @mbg.generated Wed Apr 25 16:59:41 CST 2018
     */
    public Integer getSettleType() {
        return settleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_level_fee_rate.settle_type
     *
     * @param settleType the value for t_level_fee_rate.settle_type
     *
     * @mbg.generated Wed Apr 25 16:59:41 CST 2018
     */
    public void setSettleType(Integer settleType) {
        this.settleType = settleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_level_fee_rate.integral_type
     *
     * @return the value of t_level_fee_rate.integral_type
     *
     * @mbg.generated Wed Apr 25 16:59:41 CST 2018
     */
    public Integer getIntegralType() {
        return integralType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_level_fee_rate.integral_type
     *
     * @param integralType the value for t_level_fee_rate.integral_type
     *
     * @mbg.generated Wed Apr 25 16:59:41 CST 2018
     */
    public void setIntegralType(Integer integralType) {
        this.integralType = integralType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_level_fee_rate.fee_rate
     *
     * @return the value of t_level_fee_rate.fee_rate
     *
     * @mbg.generated Wed Apr 25 16:59:41 CST 2018
     */
    public BigDecimal getFeeRate() {
        return feeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_level_fee_rate.fee_rate
     *
     * @param feeRate the value for t_level_fee_rate.fee_rate
     *
     * @mbg.generated Wed Apr 25 16:59:41 CST 2018
     */
    public void setFeeRate(BigDecimal feeRate) {
        this.feeRate = feeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_level_fee_rate.upperlimit
     *
     * @return the value of t_level_fee_rate.upperlimit
     *
     * @mbg.generated Wed Apr 25 16:59:41 CST 2018
     */
    public Integer getUpperlimit() {
        return upperlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_level_fee_rate.upperlimit
     *
     * @param upperlimit the value for t_level_fee_rate.upperlimit
     *
     * @mbg.generated Wed Apr 25 16:59:41 CST 2018
     */
    public void setUpperlimit(Integer upperlimit) {
        this.upperlimit = upperlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_level_fee_rate.pay_fee
     *
     * @return the value of t_level_fee_rate.pay_fee
     *
     * @mbg.generated Wed Apr 25 16:59:41 CST 2018
     */
    public Integer getPayFee() {
        return payFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_level_fee_rate.pay_fee
     *
     * @param payFee the value for t_level_fee_rate.pay_fee
     *
     * @mbg.generated Wed Apr 25 16:59:41 CST 2018
     */
    public void setPayFee(Integer payFee) {
        this.payFee = payFee;
    }
	
	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_level_fee_rate.pay_chnl_code
     *
     * @return the value of t_level_fee_rate.pay_chnl_code
     *
     * @mbg.generated Wed Aug 08 18:06:51 CST 2018
     */
    public String getPayChnlCode() {
        return payChnlCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_level_fee_rate.pay_chnl_code
     *
     * @param payChnlCode the value for t_level_fee_rate.pay_chnl_code
     *
     * @mbg.generated Wed Aug 08 18:06:51 CST 2018
     */
    public void setPayChnlCode(String payChnlCode) {
        this.payChnlCode = payChnlCode == null ? null : payChnlCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_level_fee_rate.row_crt_usr
     *
     * @return the value of t_level_fee_rate.row_crt_usr
     *
     * @mbg.generated Wed Apr 25 16:59:41 CST 2018
     */
    public String getRowCrtUsr() {
        return rowCrtUsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_level_fee_rate.row_crt_usr
     *
     * @param rowCrtUsr the value for t_level_fee_rate.row_crt_usr
     *
     * @mbg.generated Wed Apr 25 16:59:41 CST 2018
     */
    public void setRowCrtUsr(String rowCrtUsr) {
        this.rowCrtUsr = rowCrtUsr == null ? null : rowCrtUsr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_level_fee_rate.row_crt_ts
     *
     * @return the value of t_level_fee_rate.row_crt_ts
     *
     * @mbg.generated Wed Apr 25 16:59:41 CST 2018
     */
    public Date getRowCrtTs() {
        return rowCrtTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_level_fee_rate.row_crt_ts
     *
     * @param rowCrtTs the value for t_level_fee_rate.row_crt_ts
     *
     * @mbg.generated Wed Apr 25 16:59:41 CST 2018
     */
    public void setRowCrtTs(Date rowCrtTs) {
        this.rowCrtTs = rowCrtTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_level_fee_rate.rec_upd_usr
     *
     * @return the value of t_level_fee_rate.rec_upd_usr
     *
     * @mbg.generated Wed Apr 25 16:59:41 CST 2018
     */
    public String getRecUpdUsr() {
        return recUpdUsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_level_fee_rate.rec_upd_usr
     *
     * @param recUpdUsr the value for t_level_fee_rate.rec_upd_usr
     *
     * @mbg.generated Wed Apr 25 16:59:41 CST 2018
     */
    public void setRecUpdUsr(String recUpdUsr) {
        this.recUpdUsr = recUpdUsr == null ? null : recUpdUsr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_level_fee_rate.rec_upd_ts
     *
     * @return the value of t_level_fee_rate.rec_upd_ts
     *
     * @mbg.generated Wed Apr 25 16:59:41 CST 2018
     */
    public Date getRecUpdTs() {
        return recUpdTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_level_fee_rate.rec_upd_ts
     *
     * @param recUpdTs the value for t_level_fee_rate.rec_upd_ts
     *
     * @mbg.generated Wed Apr 25 16:59:41 CST 2018
     */
    public void setRecUpdTs(Date recUpdTs) {
        this.recUpdTs = recUpdTs;
    }
    
    public BigDecimal getUpperlimitFj() {
		return upperlimitFj;
	}

	public void setUpperlimitFj(BigDecimal upperlimitFj) {
		this.upperlimitFj = upperlimitFj;
	}

	public BigDecimal getPayFeeFj() {
		return payFeeFj;
	}

	public void setPayFeeFj(BigDecimal payFeeFj) {
		this.payFeeFj = payFeeFj;
	}

	private BigDecimal upperlimitFj;
    private BigDecimal payFeeFj;
    @Override
    public String toString() {
    	return "payChnlCode:["+payChnlCode+"]";
    }
}