package net.chrone.creditpay.model;

import java.util.Date;

public class MenuInf {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu_inf.menu_id
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    private String menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu_inf.menu_nm
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    private String menuNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu_inf.menu_url
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    private String menuUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu_inf.menu_parent
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    private String menuParent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu_inf.menu_sort
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    private String menuSort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu_inf.row_crt_usr
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    private String rowCrtUsr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu_inf.row_crt_ts
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    private Date rowCrtTs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu_inf.rec_upd_usr
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    private String recUpdUsr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu_inf.rec_upd_ts
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    private Date recUpdTs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu_inf.menu_id
     *
     * @return the value of t_menu_inf.menu_id
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu_inf.menu_id
     *
     * @param menuId the value for t_menu_inf.menu_id
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId == null ? null : menuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu_inf.menu_nm
     *
     * @return the value of t_menu_inf.menu_nm
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public String getMenuNm() {
        return menuNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu_inf.menu_nm
     *
     * @param menuNm the value for t_menu_inf.menu_nm
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public void setMenuNm(String menuNm) {
        this.menuNm = menuNm == null ? null : menuNm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu_inf.menu_url
     *
     * @return the value of t_menu_inf.menu_url
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public String getMenuUrl() {
        return menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu_inf.menu_url
     *
     * @param menuUrl the value for t_menu_inf.menu_url
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl == null ? null : menuUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu_inf.menu_parent
     *
     * @return the value of t_menu_inf.menu_parent
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public String getMenuParent() {
        return menuParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu_inf.menu_parent
     *
     * @param menuParent the value for t_menu_inf.menu_parent
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public void setMenuParent(String menuParent) {
        this.menuParent = menuParent == null ? null : menuParent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu_inf.menu_sort
     *
     * @return the value of t_menu_inf.menu_sort
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public String getMenuSort() {
        return menuSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu_inf.menu_sort
     *
     * @param menuSort the value for t_menu_inf.menu_sort
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public void setMenuSort(String menuSort) {
        this.menuSort = menuSort == null ? null : menuSort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu_inf.row_crt_usr
     *
     * @return the value of t_menu_inf.row_crt_usr
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public String getRowCrtUsr() {
        return rowCrtUsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu_inf.row_crt_usr
     *
     * @param rowCrtUsr the value for t_menu_inf.row_crt_usr
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public void setRowCrtUsr(String rowCrtUsr) {
        this.rowCrtUsr = rowCrtUsr == null ? null : rowCrtUsr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu_inf.row_crt_ts
     *
     * @return the value of t_menu_inf.row_crt_ts
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public Date getRowCrtTs() {
        return rowCrtTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu_inf.row_crt_ts
     *
     * @param rowCrtTs the value for t_menu_inf.row_crt_ts
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public void setRowCrtTs(Date rowCrtTs) {
        this.rowCrtTs = rowCrtTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu_inf.rec_upd_usr
     *
     * @return the value of t_menu_inf.rec_upd_usr
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public String getRecUpdUsr() {
        return recUpdUsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu_inf.rec_upd_usr
     *
     * @param recUpdUsr the value for t_menu_inf.rec_upd_usr
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public void setRecUpdUsr(String recUpdUsr) {
        this.recUpdUsr = recUpdUsr == null ? null : recUpdUsr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu_inf.rec_upd_ts
     *
     * @return the value of t_menu_inf.rec_upd_ts
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public Date getRecUpdTs() {
        return recUpdTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu_inf.rec_upd_ts
     *
     * @param recUpdTs the value for t_menu_inf.rec_upd_ts
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public void setRecUpdTs(Date recUpdTs) {
        this.recUpdTs = recUpdTs;
    }
}