package net.chrone.creditpay.model;

import java.util.Date;

public class MgrUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mgr_user.login_id
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    private String loginId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mgr_user.user_name
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mgr_user.login_pwd
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    private String loginPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mgr_user.mobile_no
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    private String mobileNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mgr_user.email
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mgr_user.role_id
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mgr_user.user_st
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    private String userSt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mgr_user.last_login_ip
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    private String lastLoginIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mgr_user.last_login_ts
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    private Date lastLoginTs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mgr_user.row_crt_usr
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    private String rowCrtUsr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mgr_user.row_crt_ts
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    private Date rowCrtTs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mgr_user.rec_upd_usr
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    private String recUpdUsr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mgr_user.rec_upd_ts
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    private Date recUpdTs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mgr_user.login_id
     *
     * @return the value of t_mgr_user.login_id
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public String getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mgr_user.login_id
     *
     * @param loginId the value for t_mgr_user.login_id
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public void setLoginId(String loginId) {
        this.loginId = loginId == null ? null : loginId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mgr_user.user_name
     *
     * @return the value of t_mgr_user.user_name
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mgr_user.user_name
     *
     * @param userName the value for t_mgr_user.user_name
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mgr_user.login_pwd
     *
     * @return the value of t_mgr_user.login_pwd
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public String getLoginPwd() {
        return loginPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mgr_user.login_pwd
     *
     * @param loginPwd the value for t_mgr_user.login_pwd
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public void setLoginPwd(String loginPwd) {
        this.loginPwd = loginPwd == null ? null : loginPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mgr_user.mobile_no
     *
     * @return the value of t_mgr_user.mobile_no
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public String getMobileNo() {
        return mobileNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mgr_user.mobile_no
     *
     * @param mobileNo the value for t_mgr_user.mobile_no
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo == null ? null : mobileNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mgr_user.email
     *
     * @return the value of t_mgr_user.email
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mgr_user.email
     *
     * @param email the value for t_mgr_user.email
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mgr_user.role_id
     *
     * @return the value of t_mgr_user.role_id
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mgr_user.role_id
     *
     * @param roleId the value for t_mgr_user.role_id
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mgr_user.user_st
     *
     * @return the value of t_mgr_user.user_st
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public String getUserSt() {
        return userSt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mgr_user.user_st
     *
     * @param userSt the value for t_mgr_user.user_st
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public void setUserSt(String userSt) {
        this.userSt = userSt == null ? null : userSt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mgr_user.last_login_ip
     *
     * @return the value of t_mgr_user.last_login_ip
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public String getLastLoginIp() {
        return lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mgr_user.last_login_ip
     *
     * @param lastLoginIp the value for t_mgr_user.last_login_ip
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp == null ? null : lastLoginIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mgr_user.last_login_ts
     *
     * @return the value of t_mgr_user.last_login_ts
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public Date getLastLoginTs() {
        return lastLoginTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mgr_user.last_login_ts
     *
     * @param lastLoginTs the value for t_mgr_user.last_login_ts
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public void setLastLoginTs(Date lastLoginTs) {
        this.lastLoginTs = lastLoginTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mgr_user.row_crt_usr
     *
     * @return the value of t_mgr_user.row_crt_usr
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public String getRowCrtUsr() {
        return rowCrtUsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mgr_user.row_crt_usr
     *
     * @param rowCrtUsr the value for t_mgr_user.row_crt_usr
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public void setRowCrtUsr(String rowCrtUsr) {
        this.rowCrtUsr = rowCrtUsr == null ? null : rowCrtUsr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mgr_user.row_crt_ts
     *
     * @return the value of t_mgr_user.row_crt_ts
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public Date getRowCrtTs() {
        return rowCrtTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mgr_user.row_crt_ts
     *
     * @param rowCrtTs the value for t_mgr_user.row_crt_ts
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public void setRowCrtTs(Date rowCrtTs) {
        this.rowCrtTs = rowCrtTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mgr_user.rec_upd_usr
     *
     * @return the value of t_mgr_user.rec_upd_usr
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public String getRecUpdUsr() {
        return recUpdUsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mgr_user.rec_upd_usr
     *
     * @param recUpdUsr the value for t_mgr_user.rec_upd_usr
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public void setRecUpdUsr(String recUpdUsr) {
        this.recUpdUsr = recUpdUsr == null ? null : recUpdUsr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mgr_user.rec_upd_ts
     *
     * @return the value of t_mgr_user.rec_upd_ts
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public Date getRecUpdTs() {
        return recUpdTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mgr_user.rec_upd_ts
     *
     * @param recUpdTs the value for t_mgr_user.rec_upd_ts
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public void setRecUpdTs(Date recUpdTs) {
        this.recUpdTs = recUpdTs;
    }
    private String roleNm;

	public String getRoleNm() {
		return roleNm;
	}

	public void setRoleNm(String roleNm) {
		this.roleNm = roleNm;
	}
    
}