package net.chrone.creditpay.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OperationLogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_operation_log
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_operation_log
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_operation_log
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_log
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public OperationLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_log
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_log
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_log
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_log
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_log
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_log
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_log
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_log
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_log
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_log
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_operation_log
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Integer> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Integer> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andOperationUserIsNull() {
            addCriterion("operation_user is null");
            return (Criteria) this;
        }

        public Criteria andOperationUserIsNotNull() {
            addCriterion("operation_user is not null");
            return (Criteria) this;
        }

        public Criteria andOperationUserEqualTo(String value) {
            addCriterion("operation_user =", value, "operationUser");
            return (Criteria) this;
        }

        public Criteria andOperationUserNotEqualTo(String value) {
            addCriterion("operation_user <>", value, "operationUser");
            return (Criteria) this;
        }

        public Criteria andOperationUserGreaterThan(String value) {
            addCriterion("operation_user >", value, "operationUser");
            return (Criteria) this;
        }

        public Criteria andOperationUserGreaterThanOrEqualTo(String value) {
            addCriterion("operation_user >=", value, "operationUser");
            return (Criteria) this;
        }

        public Criteria andOperationUserLessThan(String value) {
            addCriterion("operation_user <", value, "operationUser");
            return (Criteria) this;
        }

        public Criteria andOperationUserLessThanOrEqualTo(String value) {
            addCriterion("operation_user <=", value, "operationUser");
            return (Criteria) this;
        }

        public Criteria andOperationUserLike(String value) {
            addCriterion("operation_user like", value, "operationUser");
            return (Criteria) this;
        }

        public Criteria andOperationUserNotLike(String value) {
            addCriterion("operation_user not like", value, "operationUser");
            return (Criteria) this;
        }

        public Criteria andOperationUserIn(List<String> values) {
            addCriterion("operation_user in", values, "operationUser");
            return (Criteria) this;
        }

        public Criteria andOperationUserNotIn(List<String> values) {
            addCriterion("operation_user not in", values, "operationUser");
            return (Criteria) this;
        }

        public Criteria andOperationUserBetween(String value1, String value2) {
            addCriterion("operation_user between", value1, value2, "operationUser");
            return (Criteria) this;
        }

        public Criteria andOperationUserNotBetween(String value1, String value2) {
            addCriterion("operation_user not between", value1, value2, "operationUser");
            return (Criteria) this;
        }

        public Criteria andContentIsNull() {
            addCriterion("content is null");
            return (Criteria) this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("content is not null");
            return (Criteria) this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("content =", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("content <>", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("content >", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("content >=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("content <", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("content <=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("content like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("content not like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentIn(List<String> values) {
            addCriterion("content in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotIn(List<String> values) {
            addCriterion("content not in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("content between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("content not between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andIpIsNull() {
            addCriterion("ip is null");
            return (Criteria) this;
        }

        public Criteria andIpIsNotNull() {
            addCriterion("ip is not null");
            return (Criteria) this;
        }

        public Criteria andIpEqualTo(String value) {
            addCriterion("ip =", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotEqualTo(String value) {
            addCriterion("ip <>", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThan(String value) {
            addCriterion("ip >", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThanOrEqualTo(String value) {
            addCriterion("ip >=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThan(String value) {
            addCriterion("ip <", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThanOrEqualTo(String value) {
            addCriterion("ip <=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLike(String value) {
            addCriterion("ip like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotLike(String value) {
            addCriterion("ip not like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpIn(List<String> values) {
            addCriterion("ip in", values, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotIn(List<String> values) {
            addCriterion("ip not in", values, "ip");
            return (Criteria) this;
        }

        public Criteria andIpBetween(String value1, String value2) {
            addCriterion("ip between", value1, value2, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotBetween(String value1, String value2) {
            addCriterion("ip not between", value1, value2, "ip");
            return (Criteria) this;
        }

        public Criteria andMemoIsNull() {
            addCriterion("memo is null");
            return (Criteria) this;
        }

        public Criteria andMemoIsNotNull() {
            addCriterion("memo is not null");
            return (Criteria) this;
        }

        public Criteria andMemoEqualTo(String value) {
            addCriterion("memo =", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotEqualTo(String value) {
            addCriterion("memo <>", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThan(String value) {
            addCriterion("memo >", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThanOrEqualTo(String value) {
            addCriterion("memo >=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThan(String value) {
            addCriterion("memo <", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThanOrEqualTo(String value) {
            addCriterion("memo <=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLike(String value) {
            addCriterion("memo like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotLike(String value) {
            addCriterion("memo not like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoIn(List<String> values) {
            addCriterion("memo in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotIn(List<String> values) {
            addCriterion("memo not in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoBetween(String value1, String value2) {
            addCriterion("memo between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotBetween(String value1, String value2) {
            addCriterion("memo not between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andRowCrtTsIsNull() {
            addCriterion("row_crt_ts is null");
            return (Criteria) this;
        }

        public Criteria andRowCrtTsIsNotNull() {
            addCriterion("row_crt_ts is not null");
            return (Criteria) this;
        }

        public Criteria andRowCrtTsEqualTo(Date value) {
            addCriterion("row_crt_ts =", value, "rowCrtTs");
            return (Criteria) this;
        }

        public Criteria andRowCrtTsNotEqualTo(Date value) {
            addCriterion("row_crt_ts <>", value, "rowCrtTs");
            return (Criteria) this;
        }

        public Criteria andRowCrtTsGreaterThan(Date value) {
            addCriterion("row_crt_ts >", value, "rowCrtTs");
            return (Criteria) this;
        }

        public Criteria andRowCrtTsGreaterThanOrEqualTo(Date value) {
            addCriterion("row_crt_ts >=", value, "rowCrtTs");
            return (Criteria) this;
        }

        public Criteria andRowCrtTsLessThan(Date value) {
            addCriterion("row_crt_ts <", value, "rowCrtTs");
            return (Criteria) this;
        }

        public Criteria andRowCrtTsLessThanOrEqualTo(Date value) {
            addCriterion("row_crt_ts <=", value, "rowCrtTs");
            return (Criteria) this;
        }

        public Criteria andRowCrtTsIn(List<Date> values) {
            addCriterion("row_crt_ts in", values, "rowCrtTs");
            return (Criteria) this;
        }

        public Criteria andRowCrtTsNotIn(List<Date> values) {
            addCriterion("row_crt_ts not in", values, "rowCrtTs");
            return (Criteria) this;
        }

        public Criteria andRowCrtTsBetween(Date value1, Date value2) {
            addCriterion("row_crt_ts between", value1, value2, "rowCrtTs");
            return (Criteria) this;
        }

        public Criteria andRowCrtTsNotBetween(Date value1, Date value2) {
            addCriterion("row_crt_ts not between", value1, value2, "rowCrtTs");
            return (Criteria) this;
        }

        public Criteria andRowCrtUsrIsNull() {
            addCriterion("row_crt_usr is null");
            return (Criteria) this;
        }

        public Criteria andRowCrtUsrIsNotNull() {
            addCriterion("row_crt_usr is not null");
            return (Criteria) this;
        }

        public Criteria andRowCrtUsrEqualTo(String value) {
            addCriterion("row_crt_usr =", value, "rowCrtUsr");
            return (Criteria) this;
        }

        public Criteria andRowCrtUsrNotEqualTo(String value) {
            addCriterion("row_crt_usr <>", value, "rowCrtUsr");
            return (Criteria) this;
        }

        public Criteria andRowCrtUsrGreaterThan(String value) {
            addCriterion("row_crt_usr >", value, "rowCrtUsr");
            return (Criteria) this;
        }

        public Criteria andRowCrtUsrGreaterThanOrEqualTo(String value) {
            addCriterion("row_crt_usr >=", value, "rowCrtUsr");
            return (Criteria) this;
        }

        public Criteria andRowCrtUsrLessThan(String value) {
            addCriterion("row_crt_usr <", value, "rowCrtUsr");
            return (Criteria) this;
        }

        public Criteria andRowCrtUsrLessThanOrEqualTo(String value) {
            addCriterion("row_crt_usr <=", value, "rowCrtUsr");
            return (Criteria) this;
        }

        public Criteria andRowCrtUsrLike(String value) {
            addCriterion("row_crt_usr like", value, "rowCrtUsr");
            return (Criteria) this;
        }

        public Criteria andRowCrtUsrNotLike(String value) {
            addCriterion("row_crt_usr not like", value, "rowCrtUsr");
            return (Criteria) this;
        }

        public Criteria andRowCrtUsrIn(List<String> values) {
            addCriterion("row_crt_usr in", values, "rowCrtUsr");
            return (Criteria) this;
        }

        public Criteria andRowCrtUsrNotIn(List<String> values) {
            addCriterion("row_crt_usr not in", values, "rowCrtUsr");
            return (Criteria) this;
        }

        public Criteria andRowCrtUsrBetween(String value1, String value2) {
            addCriterion("row_crt_usr between", value1, value2, "rowCrtUsr");
            return (Criteria) this;
        }

        public Criteria andRowCrtUsrNotBetween(String value1, String value2) {
            addCriterion("row_crt_usr not between", value1, value2, "rowCrtUsr");
            return (Criteria) this;
        }

        public Criteria andRowUpdTsIsNull() {
            addCriterion("row_upd_ts is null");
            return (Criteria) this;
        }

        public Criteria andRowUpdTsIsNotNull() {
            addCriterion("row_upd_ts is not null");
            return (Criteria) this;
        }

        public Criteria andRowUpdTsEqualTo(Date value) {
            addCriterion("row_upd_ts =", value, "rowUpdTs");
            return (Criteria) this;
        }

        public Criteria andRowUpdTsNotEqualTo(Date value) {
            addCriterion("row_upd_ts <>", value, "rowUpdTs");
            return (Criteria) this;
        }

        public Criteria andRowUpdTsGreaterThan(Date value) {
            addCriterion("row_upd_ts >", value, "rowUpdTs");
            return (Criteria) this;
        }

        public Criteria andRowUpdTsGreaterThanOrEqualTo(Date value) {
            addCriterion("row_upd_ts >=", value, "rowUpdTs");
            return (Criteria) this;
        }

        public Criteria andRowUpdTsLessThan(Date value) {
            addCriterion("row_upd_ts <", value, "rowUpdTs");
            return (Criteria) this;
        }

        public Criteria andRowUpdTsLessThanOrEqualTo(Date value) {
            addCriterion("row_upd_ts <=", value, "rowUpdTs");
            return (Criteria) this;
        }

        public Criteria andRowUpdTsIn(List<Date> values) {
            addCriterion("row_upd_ts in", values, "rowUpdTs");
            return (Criteria) this;
        }

        public Criteria andRowUpdTsNotIn(List<Date> values) {
            addCriterion("row_upd_ts not in", values, "rowUpdTs");
            return (Criteria) this;
        }

        public Criteria andRowUpdTsBetween(Date value1, Date value2) {
            addCriterion("row_upd_ts between", value1, value2, "rowUpdTs");
            return (Criteria) this;
        }

        public Criteria andRowUpdTsNotBetween(Date value1, Date value2) {
            addCriterion("row_upd_ts not between", value1, value2, "rowUpdTs");
            return (Criteria) this;
        }

        public Criteria andRowUpdUsrIsNull() {
            addCriterion("row_upd_usr is null");
            return (Criteria) this;
        }

        public Criteria andRowUpdUsrIsNotNull() {
            addCriterion("row_upd_usr is not null");
            return (Criteria) this;
        }

        public Criteria andRowUpdUsrEqualTo(String value) {
            addCriterion("row_upd_usr =", value, "rowUpdUsr");
            return (Criteria) this;
        }

        public Criteria andRowUpdUsrNotEqualTo(String value) {
            addCriterion("row_upd_usr <>", value, "rowUpdUsr");
            return (Criteria) this;
        }

        public Criteria andRowUpdUsrGreaterThan(String value) {
            addCriterion("row_upd_usr >", value, "rowUpdUsr");
            return (Criteria) this;
        }

        public Criteria andRowUpdUsrGreaterThanOrEqualTo(String value) {
            addCriterion("row_upd_usr >=", value, "rowUpdUsr");
            return (Criteria) this;
        }

        public Criteria andRowUpdUsrLessThan(String value) {
            addCriterion("row_upd_usr <", value, "rowUpdUsr");
            return (Criteria) this;
        }

        public Criteria andRowUpdUsrLessThanOrEqualTo(String value) {
            addCriterion("row_upd_usr <=", value, "rowUpdUsr");
            return (Criteria) this;
        }

        public Criteria andRowUpdUsrLike(String value) {
            addCriterion("row_upd_usr like", value, "rowUpdUsr");
            return (Criteria) this;
        }

        public Criteria andRowUpdUsrNotLike(String value) {
            addCriterion("row_upd_usr not like", value, "rowUpdUsr");
            return (Criteria) this;
        }

        public Criteria andRowUpdUsrIn(List<String> values) {
            addCriterion("row_upd_usr in", values, "rowUpdUsr");
            return (Criteria) this;
        }

        public Criteria andRowUpdUsrNotIn(List<String> values) {
            addCriterion("row_upd_usr not in", values, "rowUpdUsr");
            return (Criteria) this;
        }

        public Criteria andRowUpdUsrBetween(String value1, String value2) {
            addCriterion("row_upd_usr between", value1, value2, "rowUpdUsr");
            return (Criteria) this;
        }

        public Criteria andRowUpdUsrNotBetween(String value1, String value2) {
            addCriterion("row_upd_usr not between", value1, value2, "rowUpdUsr");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_operation_log
     *
     * @mbg.generated do_not_delete_during_merge Thu Nov 16 10:53:39 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_operation_log
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}