package net.chrone.creditpay.model;

import java.util.Date;
import java.math.BigDecimal;

public class PayChannel extends ParentMode{
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_pay_channel.id
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	private String id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_pay_channel.code
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	private String code;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_pay_channel.name
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_pay_channel.chnl_type
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	private Integer chnlType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_pay_channel.settle_type
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	private Integer settleType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_pay_channel.status
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	private Integer status;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_pay_channel.fee_type
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	private Integer feeType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_pay_channel.fee_rate
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	private BigDecimal feeRate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_pay_channel.pay_fee_type
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	private Integer payFeeType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_pay_channel.pay_fee_rate
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	private BigDecimal payFeeRate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_pay_channel.min_amount
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	private Integer minAmount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_pay_channel.max_amount
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	private Integer maxAmount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_pay_channel.day_sum_amount
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	private Integer daySumAmount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_pay_channel.day_sum_cnt
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	private Integer daySumCnt;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_pay_channel.start_time
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	private Date startTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_pay_channel.end_time
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	private Date endTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_pay_channel.priority
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	private Integer priority;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_pay_channel.sub_merchant_id
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	private String subMerchantId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_pay_channel.chnl_desc
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	private String chnlDesc;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_pay_channel.chnl_risk
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	private String chnlRisk;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_pay_channel.reserved
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	private String reserved;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_pay_channel.created
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	private Date created;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_pay_channel.created_user
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	private String createdUser;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_pay_channel.modified
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	private Date modified;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_pay_channel.modified_user
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	private String modifiedUser;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_pay_channel.upperlimit
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	private Integer upperlimit;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_pay_channel.integral_type
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	private Integer integralType;
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_pay_channel.id
	 * @return  the value of t_pay_channel.id
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_pay_channel.id
	 * @param id  the value for t_pay_channel.id
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_pay_channel.code
	 * @return  the value of t_pay_channel.code
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_pay_channel.code
	 * @param code  the value for t_pay_channel.code
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public void setCode(String code) {
		this.code = code == null ? null : code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_pay_channel.name
	 * @return  the value of t_pay_channel.name
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_pay_channel.name
	 * @param name  the value for t_pay_channel.name
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_pay_channel.chnl_type
	 * @return  the value of t_pay_channel.chnl_type
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public Integer getChnlType() {
		return chnlType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_pay_channel.chnl_type
	 * @param chnlType  the value for t_pay_channel.chnl_type
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public void setChnlType(Integer chnlType) {
		this.chnlType = chnlType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_pay_channel.settle_type
	 * @return  the value of t_pay_channel.settle_type
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public Integer getSettleType() {
		return settleType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_pay_channel.settle_type
	 * @param settleType  the value for t_pay_channel.settle_type
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public void setSettleType(Integer settleType) {
		this.settleType = settleType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_pay_channel.status
	 * @return  the value of t_pay_channel.status
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_pay_channel.status
	 * @param status  the value for t_pay_channel.status
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_pay_channel.fee_type
	 * @return  the value of t_pay_channel.fee_type
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public Integer getFeeType() {
		return feeType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_pay_channel.fee_type
	 * @param feeType  the value for t_pay_channel.fee_type
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public void setFeeType(Integer feeType) {
		this.feeType = feeType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_pay_channel.fee_rate
	 * @return  the value of t_pay_channel.fee_rate
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public BigDecimal getFeeRate() {
		return feeRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_pay_channel.fee_rate
	 * @param feeRate  the value for t_pay_channel.fee_rate
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public void setFeeRate(BigDecimal feeRate) {
		this.feeRate = feeRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_pay_channel.pay_fee_type
	 * @return  the value of t_pay_channel.pay_fee_type
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public Integer getPayFeeType() {
		return payFeeType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_pay_channel.pay_fee_type
	 * @param payFeeType  the value for t_pay_channel.pay_fee_type
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public void setPayFeeType(Integer payFeeType) {
		this.payFeeType = payFeeType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_pay_channel.pay_fee_rate
	 * @return  the value of t_pay_channel.pay_fee_rate
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public BigDecimal getPayFeeRate() {
		return payFeeRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_pay_channel.pay_fee_rate
	 * @param payFeeRate  the value for t_pay_channel.pay_fee_rate
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public void setPayFeeRate(BigDecimal payFeeRate) {
		this.payFeeRate = payFeeRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_pay_channel.min_amount
	 * @return  the value of t_pay_channel.min_amount
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public Integer getMinAmount() {
		return minAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_pay_channel.min_amount
	 * @param minAmount  the value for t_pay_channel.min_amount
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public void setMinAmount(Integer minAmount) {
		this.minAmount = minAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_pay_channel.max_amount
	 * @return  the value of t_pay_channel.max_amount
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public Integer getMaxAmount() {
		return maxAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_pay_channel.max_amount
	 * @param maxAmount  the value for t_pay_channel.max_amount
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public void setMaxAmount(Integer maxAmount) {
		this.maxAmount = maxAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_pay_channel.day_sum_amount
	 * @return  the value of t_pay_channel.day_sum_amount
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public Integer getDaySumAmount() {
		return daySumAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_pay_channel.day_sum_amount
	 * @param daySumAmount  the value for t_pay_channel.day_sum_amount
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public void setDaySumAmount(Integer daySumAmount) {
		this.daySumAmount = daySumAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_pay_channel.day_sum_cnt
	 * @return  the value of t_pay_channel.day_sum_cnt
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public Integer getDaySumCnt() {
		return daySumCnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_pay_channel.day_sum_cnt
	 * @param daySumCnt  the value for t_pay_channel.day_sum_cnt
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public void setDaySumCnt(Integer daySumCnt) {
		this.daySumCnt = daySumCnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_pay_channel.start_time
	 * @return  the value of t_pay_channel.start_time
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public Date getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_pay_channel.start_time
	 * @param startTime  the value for t_pay_channel.start_time
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_pay_channel.end_time
	 * @return  the value of t_pay_channel.end_time
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public Date getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_pay_channel.end_time
	 * @param endTime  the value for t_pay_channel.end_time
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_pay_channel.priority
	 * @return  the value of t_pay_channel.priority
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public Integer getPriority() {
		return priority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_pay_channel.priority
	 * @param priority  the value for t_pay_channel.priority
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_pay_channel.sub_merchant_id
	 * @return  the value of t_pay_channel.sub_merchant_id
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public String getSubMerchantId() {
		return subMerchantId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_pay_channel.sub_merchant_id
	 * @param subMerchantId  the value for t_pay_channel.sub_merchant_id
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public void setSubMerchantId(String subMerchantId) {
		this.subMerchantId = subMerchantId == null ? null : subMerchantId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_pay_channel.chnl_desc
	 * @return  the value of t_pay_channel.chnl_desc
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public String getChnlDesc() {
		return chnlDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_pay_channel.chnl_desc
	 * @param chnlDesc  the value for t_pay_channel.chnl_desc
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public void setChnlDesc(String chnlDesc) {
		this.chnlDesc = chnlDesc == null ? null : chnlDesc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_pay_channel.reserved
	 * @return  the value of t_pay_channel.reserved
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public String getReserved() {
		return reserved;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_pay_channel.reserved
	 * @param reserved  the value for t_pay_channel.reserved
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public void setReserved(String reserved) {
		this.reserved = reserved == null ? null : reserved.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_pay_channel.created
	 * @return  the value of t_pay_channel.created
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public Date getCreated() {
		return created;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_pay_channel.created
	 * @param created  the value for t_pay_channel.created
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public void setCreated(Date created) {
		this.created = created;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_pay_channel.created_user
	 * @return  the value of t_pay_channel.created_user
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public String getCreatedUser() {
		return createdUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_pay_channel.created_user
	 * @param createdUser  the value for t_pay_channel.created_user
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public void setCreatedUser(String createdUser) {
		this.createdUser = createdUser == null ? null : createdUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_pay_channel.modified
	 * @return  the value of t_pay_channel.modified
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public Date getModified() {
		return modified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_pay_channel.modified
	 * @param modified  the value for t_pay_channel.modified
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public void setModified(Date modified) {
		this.modified = modified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_pay_channel.modified_user
	 * @return  the value of t_pay_channel.modified_user
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public String getModifiedUser() {
		return modifiedUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_pay_channel.modified_user
	 * @param modifiedUser  the value for t_pay_channel.modified_user
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public void setModifiedUser(String modifiedUser) {
		this.modifiedUser = modifiedUser == null ? null : modifiedUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_pay_channel.upperlimit
	 * @return  the value of t_pay_channel.upperlimit
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public Integer getUpperlimit() {
		return upperlimit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_pay_channel.upperlimit
	 * @param upperlimit  the value for t_pay_channel.upperlimit
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public void setUpperlimit(Integer upperlimit) {
		this.upperlimit = upperlimit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_pay_channel.integral_type
	 * @return  the value of t_pay_channel.integral_type
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public Integer getIntegralType() {
		return integralType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_pay_channel.integral_type
	 * @param integralType  the value for t_pay_channel.integral_type
	 * @mbg.generated  Thu Apr 26 16:05:03 CST 2018
	 */
	public void setIntegralType(Integer integralType) {
		this.integralType = integralType;
	}

	public String getChnlRisk() {
		return chnlRisk;
	}

	public void setChnlRisk(String chnlRisk) {
		this.chnlRisk = chnlRisk;
	}

	public Integer getOrderBy() {
		return orderBy;
	}

	public void setOrderBy(Integer orderBy) {
		this.orderBy = orderBy;
	}

	public double getDaySumAmtDou() {
		return daySumAmtDou;
	}

	public void setDaySumAmtDou(double daySumAmtDou) {
		this.daySumAmtDou = daySumAmtDou;
	}

	public double getMaxAmountDou() {
		return maxAmountDou;
	}

	public void setMaxAmountDou(double maxAmountDou) {
		this.maxAmountDou = maxAmountDou;
	}

	public double getMinAmountDou() {
		return minAmountDou;
	}

	public void setMinAmountDou(double minAmountDou) {
		this.minAmountDou = minAmountDou;
	}

	public BigDecimal getUpperlimitDou() {
		return upperlimitDou;
	}

	public void setUpperlimitDou(BigDecimal upperlimitDou) {
		this.upperlimitDou = upperlimitDou;
	}

	private Integer orderBy;
	
	private double minAmountDou;
	private double maxAmountDou;
	private double daySumAmtDou;
	private BigDecimal upperlimitDou;
	@Override
	public String toString() {
		return "PayChannel [code=" + code + ", name=" + name + ", chnlType=" + chnlType + ", settleType=" + settleType
				+ ", status=" + status + ", feeType=" + feeType + ", feeRate=" + feeRate + ", payFeeType=" + payFeeType
				+ ", payFeeRate=" + payFeeRate + ", chnlDesc=" + chnlDesc + ", reserved=" + reserved + ", integralType="
				+ integralType + "]";
	}
	
	

}