package net.chrone.creditpay.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PayProfitsExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_pay_profits
	 * @mbg.generated  Mon Dec 25 14:53:20 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_pay_profits
	 * @mbg.generated  Mon Dec 25 14:53:20 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_pay_profits
	 * @mbg.generated  Mon Dec 25 14:53:20 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pay_profits
	 * @mbg.generated  Mon Dec 25 14:53:20 CST 2017
	 */
	public PayProfitsExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pay_profits
	 * @mbg.generated  Mon Dec 25 14:53:20 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pay_profits
	 * @mbg.generated  Mon Dec 25 14:53:20 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pay_profits
	 * @mbg.generated  Mon Dec 25 14:53:20 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pay_profits
	 * @mbg.generated  Mon Dec 25 14:53:20 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pay_profits
	 * @mbg.generated  Mon Dec 25 14:53:20 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pay_profits
	 * @mbg.generated  Mon Dec 25 14:53:20 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pay_profits
	 * @mbg.generated  Mon Dec 25 14:53:20 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pay_profits
	 * @mbg.generated  Mon Dec 25 14:53:20 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pay_profits
	 * @mbg.generated  Mon Dec 25 14:53:20 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pay_profits
	 * @mbg.generated  Mon Dec 25 14:53:20 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_pay_profits
	 * @mbg.generated  Mon Dec 25 14:53:20 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andProfitsIdIsNull() {
			addCriterion("profits_id is null");
			return (Criteria) this;
		}

		public Criteria andProfitsIdIsNotNull() {
			addCriterion("profits_id is not null");
			return (Criteria) this;
		}

		public Criteria andProfitsIdEqualTo(String value) {
			addCriterion("profits_id =", value, "profitsId");
			return (Criteria) this;
		}

		public Criteria andProfitsIdNotEqualTo(String value) {
			addCriterion("profits_id <>", value, "profitsId");
			return (Criteria) this;
		}

		public Criteria andProfitsIdGreaterThan(String value) {
			addCriterion("profits_id >", value, "profitsId");
			return (Criteria) this;
		}

		public Criteria andProfitsIdGreaterThanOrEqualTo(String value) {
			addCriterion("profits_id >=", value, "profitsId");
			return (Criteria) this;
		}

		public Criteria andProfitsIdLessThan(String value) {
			addCriterion("profits_id <", value, "profitsId");
			return (Criteria) this;
		}

		public Criteria andProfitsIdLessThanOrEqualTo(String value) {
			addCriterion("profits_id <=", value, "profitsId");
			return (Criteria) this;
		}

		public Criteria andProfitsIdLike(String value) {
			addCriterion("profits_id like", value, "profitsId");
			return (Criteria) this;
		}

		public Criteria andProfitsIdNotLike(String value) {
			addCriterion("profits_id not like", value, "profitsId");
			return (Criteria) this;
		}

		public Criteria andProfitsIdIn(List<String> values) {
			addCriterion("profits_id in", values, "profitsId");
			return (Criteria) this;
		}

		public Criteria andProfitsIdNotIn(List<String> values) {
			addCriterion("profits_id not in", values, "profitsId");
			return (Criteria) this;
		}

		public Criteria andProfitsIdBetween(String value1, String value2) {
			addCriterion("profits_id between", value1, value2, "profitsId");
			return (Criteria) this;
		}

		public Criteria andProfitsIdNotBetween(String value1, String value2) {
			addCriterion("profits_id not between", value1, value2, "profitsId");
			return (Criteria) this;
		}

		public Criteria andProfitsDtIsNull() {
			addCriterion("profits_dt is null");
			return (Criteria) this;
		}

		public Criteria andProfitsDtIsNotNull() {
			addCriterion("profits_dt is not null");
			return (Criteria) this;
		}

		public Criteria andProfitsDtEqualTo(String value) {
			addCriterion("profits_dt =", value, "profitsDt");
			return (Criteria) this;
		}

		public Criteria andProfitsDtNotEqualTo(String value) {
			addCriterion("profits_dt <>", value, "profitsDt");
			return (Criteria) this;
		}

		public Criteria andProfitsDtGreaterThan(String value) {
			addCriterion("profits_dt >", value, "profitsDt");
			return (Criteria) this;
		}

		public Criteria andProfitsDtGreaterThanOrEqualTo(String value) {
			addCriterion("profits_dt >=", value, "profitsDt");
			return (Criteria) this;
		}

		public Criteria andProfitsDtLessThan(String value) {
			addCriterion("profits_dt <", value, "profitsDt");
			return (Criteria) this;
		}

		public Criteria andProfitsDtLessThanOrEqualTo(String value) {
			addCriterion("profits_dt <=", value, "profitsDt");
			return (Criteria) this;
		}

		public Criteria andProfitsDtLike(String value) {
			addCriterion("profits_dt like", value, "profitsDt");
			return (Criteria) this;
		}

		public Criteria andProfitsDtNotLike(String value) {
			addCriterion("profits_dt not like", value, "profitsDt");
			return (Criteria) this;
		}

		public Criteria andProfitsDtIn(List<String> values) {
			addCriterion("profits_dt in", values, "profitsDt");
			return (Criteria) this;
		}

		public Criteria andProfitsDtNotIn(List<String> values) {
			addCriterion("profits_dt not in", values, "profitsDt");
			return (Criteria) this;
		}

		public Criteria andProfitsDtBetween(String value1, String value2) {
			addCriterion("profits_dt between", value1, value2, "profitsDt");
			return (Criteria) this;
		}

		public Criteria andProfitsDtNotBetween(String value1, String value2) {
			addCriterion("profits_dt not between", value1, value2, "profitsDt");
			return (Criteria) this;
		}

		public Criteria andPlanIdIsNull() {
			addCriterion("plan_id is null");
			return (Criteria) this;
		}

		public Criteria andPlanIdIsNotNull() {
			addCriterion("plan_id is not null");
			return (Criteria) this;
		}

		public Criteria andPlanIdEqualTo(String value) {
			addCriterion("plan_id =", value, "planId");
			return (Criteria) this;
		}

		public Criteria andPlanIdNotEqualTo(String value) {
			addCriterion("plan_id <>", value, "planId");
			return (Criteria) this;
		}

		public Criteria andPlanIdGreaterThan(String value) {
			addCriterion("plan_id >", value, "planId");
			return (Criteria) this;
		}

		public Criteria andPlanIdGreaterThanOrEqualTo(String value) {
			addCriterion("plan_id >=", value, "planId");
			return (Criteria) this;
		}

		public Criteria andPlanIdLessThan(String value) {
			addCriterion("plan_id <", value, "planId");
			return (Criteria) this;
		}

		public Criteria andPlanIdLessThanOrEqualTo(String value) {
			addCriterion("plan_id <=", value, "planId");
			return (Criteria) this;
		}

		public Criteria andPlanIdLike(String value) {
			addCriterion("plan_id like", value, "planId");
			return (Criteria) this;
		}

		public Criteria andPlanIdNotLike(String value) {
			addCriterion("plan_id not like", value, "planId");
			return (Criteria) this;
		}

		public Criteria andPlanIdIn(List<String> values) {
			addCriterion("plan_id in", values, "planId");
			return (Criteria) this;
		}

		public Criteria andPlanIdNotIn(List<String> values) {
			addCriterion("plan_id not in", values, "planId");
			return (Criteria) this;
		}

		public Criteria andPlanIdBetween(String value1, String value2) {
			addCriterion("plan_id between", value1, value2, "planId");
			return (Criteria) this;
		}

		public Criteria andPlanIdNotBetween(String value1, String value2) {
			addCriterion("plan_id not between", value1, value2, "planId");
			return (Criteria) this;
		}

		public Criteria andTaskIdIsNull() {
			addCriterion("task_id is null");
			return (Criteria) this;
		}

		public Criteria andTaskIdIsNotNull() {
			addCriterion("task_id is not null");
			return (Criteria) this;
		}

		public Criteria andTaskIdEqualTo(String value) {
			addCriterion("task_id =", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdNotEqualTo(String value) {
			addCriterion("task_id <>", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdGreaterThan(String value) {
			addCriterion("task_id >", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdGreaterThanOrEqualTo(String value) {
			addCriterion("task_id >=", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdLessThan(String value) {
			addCriterion("task_id <", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdLessThanOrEqualTo(String value) {
			addCriterion("task_id <=", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdLike(String value) {
			addCriterion("task_id like", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdNotLike(String value) {
			addCriterion("task_id not like", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdIn(List<String> values) {
			addCriterion("task_id in", values, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdNotIn(List<String> values) {
			addCriterion("task_id not in", values, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdBetween(String value1, String value2) {
			addCriterion("task_id between", value1, value2, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdNotBetween(String value1, String value2) {
			addCriterion("task_id not between", value1, value2, "taskId");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(String value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(String value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(String value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(String value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(String value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLike(String value) {
			addCriterion("user_id like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotLike(String value) {
			addCriterion("user_id not like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<String> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<String> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(String value1, String value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(String value1, String value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andPlanAmtIsNull() {
			addCriterion("plan_amt is null");
			return (Criteria) this;
		}

		public Criteria andPlanAmtIsNotNull() {
			addCriterion("plan_amt is not null");
			return (Criteria) this;
		}

		public Criteria andPlanAmtEqualTo(Integer value) {
			addCriterion("plan_amt =", value, "planAmt");
			return (Criteria) this;
		}

		public Criteria andPlanAmtNotEqualTo(Integer value) {
			addCriterion("plan_amt <>", value, "planAmt");
			return (Criteria) this;
		}

		public Criteria andPlanAmtGreaterThan(Integer value) {
			addCriterion("plan_amt >", value, "planAmt");
			return (Criteria) this;
		}

		public Criteria andPlanAmtGreaterThanOrEqualTo(Integer value) {
			addCriterion("plan_amt >=", value, "planAmt");
			return (Criteria) this;
		}

		public Criteria andPlanAmtLessThan(Integer value) {
			addCriterion("plan_amt <", value, "planAmt");
			return (Criteria) this;
		}

		public Criteria andPlanAmtLessThanOrEqualTo(Integer value) {
			addCriterion("plan_amt <=", value, "planAmt");
			return (Criteria) this;
		}

		public Criteria andPlanAmtIn(List<Integer> values) {
			addCriterion("plan_amt in", values, "planAmt");
			return (Criteria) this;
		}

		public Criteria andPlanAmtNotIn(List<Integer> values) {
			addCriterion("plan_amt not in", values, "planAmt");
			return (Criteria) this;
		}

		public Criteria andPlanAmtBetween(Integer value1, Integer value2) {
			addCriterion("plan_amt between", value1, value2, "planAmt");
			return (Criteria) this;
		}

		public Criteria andPlanAmtNotBetween(Integer value1, Integer value2) {
			addCriterion("plan_amt not between", value1, value2, "planAmt");
			return (Criteria) this;
		}

		public Criteria andFeeIsNull() {
			addCriterion("fee is null");
			return (Criteria) this;
		}

		public Criteria andFeeIsNotNull() {
			addCriterion("fee is not null");
			return (Criteria) this;
		}

		public Criteria andFeeEqualTo(Integer value) {
			addCriterion("fee =", value, "fee");
			return (Criteria) this;
		}

		public Criteria andFeeNotEqualTo(Integer value) {
			addCriterion("fee <>", value, "fee");
			return (Criteria) this;
		}

		public Criteria andFeeGreaterThan(Integer value) {
			addCriterion("fee >", value, "fee");
			return (Criteria) this;
		}

		public Criteria andFeeGreaterThanOrEqualTo(Integer value) {
			addCriterion("fee >=", value, "fee");
			return (Criteria) this;
		}

		public Criteria andFeeLessThan(Integer value) {
			addCriterion("fee <", value, "fee");
			return (Criteria) this;
		}

		public Criteria andFeeLessThanOrEqualTo(Integer value) {
			addCriterion("fee <=", value, "fee");
			return (Criteria) this;
		}

		public Criteria andFeeIn(List<Integer> values) {
			addCriterion("fee in", values, "fee");
			return (Criteria) this;
		}

		public Criteria andFeeNotIn(List<Integer> values) {
			addCriterion("fee not in", values, "fee");
			return (Criteria) this;
		}

		public Criteria andFeeBetween(Integer value1, Integer value2) {
			addCriterion("fee between", value1, value2, "fee");
			return (Criteria) this;
		}

		public Criteria andFeeNotBetween(Integer value1, Integer value2) {
			addCriterion("fee not between", value1, value2, "fee");
			return (Criteria) this;
		}

		public Criteria andDfFeeIsNull() {
			addCriterion("df_fee is null");
			return (Criteria) this;
		}

		public Criteria andDfFeeIsNotNull() {
			addCriterion("df_fee is not null");
			return (Criteria) this;
		}

		public Criteria andDfFeeEqualTo(Integer value) {
			addCriterion("df_fee =", value, "dfFee");
			return (Criteria) this;
		}

		public Criteria andDfFeeNotEqualTo(Integer value) {
			addCriterion("df_fee <>", value, "dfFee");
			return (Criteria) this;
		}

		public Criteria andDfFeeGreaterThan(Integer value) {
			addCriterion("df_fee >", value, "dfFee");
			return (Criteria) this;
		}

		public Criteria andDfFeeGreaterThanOrEqualTo(Integer value) {
			addCriterion("df_fee >=", value, "dfFee");
			return (Criteria) this;
		}

		public Criteria andDfFeeLessThan(Integer value) {
			addCriterion("df_fee <", value, "dfFee");
			return (Criteria) this;
		}

		public Criteria andDfFeeLessThanOrEqualTo(Integer value) {
			addCriterion("df_fee <=", value, "dfFee");
			return (Criteria) this;
		}

		public Criteria andDfFeeIn(List<Integer> values) {
			addCriterion("df_fee in", values, "dfFee");
			return (Criteria) this;
		}

		public Criteria andDfFeeNotIn(List<Integer> values) {
			addCriterion("df_fee not in", values, "dfFee");
			return (Criteria) this;
		}

		public Criteria andDfFeeBetween(Integer value1, Integer value2) {
			addCriterion("df_fee between", value1, value2, "dfFee");
			return (Criteria) this;
		}

		public Criteria andDfFeeNotBetween(Integer value1, Integer value2) {
			addCriterion("df_fee not between", value1, value2, "dfFee");
			return (Criteria) this;
		}

		public Criteria andUserProfitsIsNull() {
			addCriterion("user_profits is null");
			return (Criteria) this;
		}

		public Criteria andUserProfitsIsNotNull() {
			addCriterion("user_profits is not null");
			return (Criteria) this;
		}

		public Criteria andUserProfitsEqualTo(Integer value) {
			addCriterion("user_profits =", value, "userProfits");
			return (Criteria) this;
		}

		public Criteria andUserProfitsNotEqualTo(Integer value) {
			addCriterion("user_profits <>", value, "userProfits");
			return (Criteria) this;
		}

		public Criteria andUserProfitsGreaterThan(Integer value) {
			addCriterion("user_profits >", value, "userProfits");
			return (Criteria) this;
		}

		public Criteria andUserProfitsGreaterThanOrEqualTo(Integer value) {
			addCriterion("user_profits >=", value, "userProfits");
			return (Criteria) this;
		}

		public Criteria andUserProfitsLessThan(Integer value) {
			addCriterion("user_profits <", value, "userProfits");
			return (Criteria) this;
		}

		public Criteria andUserProfitsLessThanOrEqualTo(Integer value) {
			addCriterion("user_profits <=", value, "userProfits");
			return (Criteria) this;
		}

		public Criteria andUserProfitsIn(List<Integer> values) {
			addCriterion("user_profits in", values, "userProfits");
			return (Criteria) this;
		}

		public Criteria andUserProfitsNotIn(List<Integer> values) {
			addCriterion("user_profits not in", values, "userProfits");
			return (Criteria) this;
		}

		public Criteria andUserProfitsBetween(Integer value1, Integer value2) {
			addCriterion("user_profits between", value1, value2, "userProfits");
			return (Criteria) this;
		}

		public Criteria andUserProfitsNotBetween(Integer value1, Integer value2) {
			addCriterion("user_profits not between", value1, value2, "userProfits");
			return (Criteria) this;
		}

		public Criteria andAgentProfitsIsNull() {
			addCriterion("agent_profits is null");
			return (Criteria) this;
		}

		public Criteria andAgentProfitsIsNotNull() {
			addCriterion("agent_profits is not null");
			return (Criteria) this;
		}

		public Criteria andAgentProfitsEqualTo(Integer value) {
			addCriterion("agent_profits =", value, "agentProfits");
			return (Criteria) this;
		}

		public Criteria andAgentProfitsNotEqualTo(Integer value) {
			addCriterion("agent_profits <>", value, "agentProfits");
			return (Criteria) this;
		}

		public Criteria andAgentProfitsGreaterThan(Integer value) {
			addCriterion("agent_profits >", value, "agentProfits");
			return (Criteria) this;
		}

		public Criteria andAgentProfitsGreaterThanOrEqualTo(Integer value) {
			addCriterion("agent_profits >=", value, "agentProfits");
			return (Criteria) this;
		}

		public Criteria andAgentProfitsLessThan(Integer value) {
			addCriterion("agent_profits <", value, "agentProfits");
			return (Criteria) this;
		}

		public Criteria andAgentProfitsLessThanOrEqualTo(Integer value) {
			addCriterion("agent_profits <=", value, "agentProfits");
			return (Criteria) this;
		}

		public Criteria andAgentProfitsIn(List<Integer> values) {
			addCriterion("agent_profits in", values, "agentProfits");
			return (Criteria) this;
		}

		public Criteria andAgentProfitsNotIn(List<Integer> values) {
			addCriterion("agent_profits not in", values, "agentProfits");
			return (Criteria) this;
		}

		public Criteria andAgentProfitsBetween(Integer value1, Integer value2) {
			addCriterion("agent_profits between", value1, value2, "agentProfits");
			return (Criteria) this;
		}

		public Criteria andAgentProfitsNotBetween(Integer value1, Integer value2) {
			addCriterion("agent_profits not between", value1, value2, "agentProfits");
			return (Criteria) this;
		}

		public Criteria andRowCrtUsrIsNull() {
			addCriterion("row_crt_usr is null");
			return (Criteria) this;
		}

		public Criteria andRowCrtUsrIsNotNull() {
			addCriterion("row_crt_usr is not null");
			return (Criteria) this;
		}

		public Criteria andRowCrtUsrEqualTo(String value) {
			addCriterion("row_crt_usr =", value, "rowCrtUsr");
			return (Criteria) this;
		}

		public Criteria andRowCrtUsrNotEqualTo(String value) {
			addCriterion("row_crt_usr <>", value, "rowCrtUsr");
			return (Criteria) this;
		}

		public Criteria andRowCrtUsrGreaterThan(String value) {
			addCriterion("row_crt_usr >", value, "rowCrtUsr");
			return (Criteria) this;
		}

		public Criteria andRowCrtUsrGreaterThanOrEqualTo(String value) {
			addCriterion("row_crt_usr >=", value, "rowCrtUsr");
			return (Criteria) this;
		}

		public Criteria andRowCrtUsrLessThan(String value) {
			addCriterion("row_crt_usr <", value, "rowCrtUsr");
			return (Criteria) this;
		}

		public Criteria andRowCrtUsrLessThanOrEqualTo(String value) {
			addCriterion("row_crt_usr <=", value, "rowCrtUsr");
			return (Criteria) this;
		}

		public Criteria andRowCrtUsrLike(String value) {
			addCriterion("row_crt_usr like", value, "rowCrtUsr");
			return (Criteria) this;
		}

		public Criteria andRowCrtUsrNotLike(String value) {
			addCriterion("row_crt_usr not like", value, "rowCrtUsr");
			return (Criteria) this;
		}

		public Criteria andRowCrtUsrIn(List<String> values) {
			addCriterion("row_crt_usr in", values, "rowCrtUsr");
			return (Criteria) this;
		}

		public Criteria andRowCrtUsrNotIn(List<String> values) {
			addCriterion("row_crt_usr not in", values, "rowCrtUsr");
			return (Criteria) this;
		}

		public Criteria andRowCrtUsrBetween(String value1, String value2) {
			addCriterion("row_crt_usr between", value1, value2, "rowCrtUsr");
			return (Criteria) this;
		}

		public Criteria andRowCrtUsrNotBetween(String value1, String value2) {
			addCriterion("row_crt_usr not between", value1, value2, "rowCrtUsr");
			return (Criteria) this;
		}

		public Criteria andRowCrtTsIsNull() {
			addCriterion("row_crt_ts is null");
			return (Criteria) this;
		}

		public Criteria andRowCrtTsIsNotNull() {
			addCriterion("row_crt_ts is not null");
			return (Criteria) this;
		}

		public Criteria andRowCrtTsEqualTo(Date value) {
			addCriterion("row_crt_ts =", value, "rowCrtTs");
			return (Criteria) this;
		}

		public Criteria andRowCrtTsNotEqualTo(Date value) {
			addCriterion("row_crt_ts <>", value, "rowCrtTs");
			return (Criteria) this;
		}

		public Criteria andRowCrtTsGreaterThan(Date value) {
			addCriterion("row_crt_ts >", value, "rowCrtTs");
			return (Criteria) this;
		}

		public Criteria andRowCrtTsGreaterThanOrEqualTo(Date value) {
			addCriterion("row_crt_ts >=", value, "rowCrtTs");
			return (Criteria) this;
		}

		public Criteria andRowCrtTsLessThan(Date value) {
			addCriterion("row_crt_ts <", value, "rowCrtTs");
			return (Criteria) this;
		}

		public Criteria andRowCrtTsLessThanOrEqualTo(Date value) {
			addCriterion("row_crt_ts <=", value, "rowCrtTs");
			return (Criteria) this;
		}

		public Criteria andRowCrtTsIn(List<Date> values) {
			addCriterion("row_crt_ts in", values, "rowCrtTs");
			return (Criteria) this;
		}

		public Criteria andRowCrtTsNotIn(List<Date> values) {
			addCriterion("row_crt_ts not in", values, "rowCrtTs");
			return (Criteria) this;
		}

		public Criteria andRowCrtTsBetween(Date value1, Date value2) {
			addCriterion("row_crt_ts between", value1, value2, "rowCrtTs");
			return (Criteria) this;
		}

		public Criteria andRowCrtTsNotBetween(Date value1, Date value2) {
			addCriterion("row_crt_ts not between", value1, value2, "rowCrtTs");
			return (Criteria) this;
		}

		public Criteria andRecUpdUsrIsNull() {
			addCriterion("rec_upd_usr is null");
			return (Criteria) this;
		}

		public Criteria andRecUpdUsrIsNotNull() {
			addCriterion("rec_upd_usr is not null");
			return (Criteria) this;
		}

		public Criteria andRecUpdUsrEqualTo(String value) {
			addCriterion("rec_upd_usr =", value, "recUpdUsr");
			return (Criteria) this;
		}

		public Criteria andRecUpdUsrNotEqualTo(String value) {
			addCriterion("rec_upd_usr <>", value, "recUpdUsr");
			return (Criteria) this;
		}

		public Criteria andRecUpdUsrGreaterThan(String value) {
			addCriterion("rec_upd_usr >", value, "recUpdUsr");
			return (Criteria) this;
		}

		public Criteria andRecUpdUsrGreaterThanOrEqualTo(String value) {
			addCriterion("rec_upd_usr >=", value, "recUpdUsr");
			return (Criteria) this;
		}

		public Criteria andRecUpdUsrLessThan(String value) {
			addCriterion("rec_upd_usr <", value, "recUpdUsr");
			return (Criteria) this;
		}

		public Criteria andRecUpdUsrLessThanOrEqualTo(String value) {
			addCriterion("rec_upd_usr <=", value, "recUpdUsr");
			return (Criteria) this;
		}

		public Criteria andRecUpdUsrLike(String value) {
			addCriterion("rec_upd_usr like", value, "recUpdUsr");
			return (Criteria) this;
		}

		public Criteria andRecUpdUsrNotLike(String value) {
			addCriterion("rec_upd_usr not like", value, "recUpdUsr");
			return (Criteria) this;
		}

		public Criteria andRecUpdUsrIn(List<String> values) {
			addCriterion("rec_upd_usr in", values, "recUpdUsr");
			return (Criteria) this;
		}

		public Criteria andRecUpdUsrNotIn(List<String> values) {
			addCriterion("rec_upd_usr not in", values, "recUpdUsr");
			return (Criteria) this;
		}

		public Criteria andRecUpdUsrBetween(String value1, String value2) {
			addCriterion("rec_upd_usr between", value1, value2, "recUpdUsr");
			return (Criteria) this;
		}

		public Criteria andRecUpdUsrNotBetween(String value1, String value2) {
			addCriterion("rec_upd_usr not between", value1, value2, "recUpdUsr");
			return (Criteria) this;
		}

		public Criteria andRecUpdTsIsNull() {
			addCriterion("rec_upd_ts is null");
			return (Criteria) this;
		}

		public Criteria andRecUpdTsIsNotNull() {
			addCriterion("rec_upd_ts is not null");
			return (Criteria) this;
		}

		public Criteria andRecUpdTsEqualTo(Date value) {
			addCriterion("rec_upd_ts =", value, "recUpdTs");
			return (Criteria) this;
		}

		public Criteria andRecUpdTsNotEqualTo(Date value) {
			addCriterion("rec_upd_ts <>", value, "recUpdTs");
			return (Criteria) this;
		}

		public Criteria andRecUpdTsGreaterThan(Date value) {
			addCriterion("rec_upd_ts >", value, "recUpdTs");
			return (Criteria) this;
		}

		public Criteria andRecUpdTsGreaterThanOrEqualTo(Date value) {
			addCriterion("rec_upd_ts >=", value, "recUpdTs");
			return (Criteria) this;
		}

		public Criteria andRecUpdTsLessThan(Date value) {
			addCriterion("rec_upd_ts <", value, "recUpdTs");
			return (Criteria) this;
		}

		public Criteria andRecUpdTsLessThanOrEqualTo(Date value) {
			addCriterion("rec_upd_ts <=", value, "recUpdTs");
			return (Criteria) this;
		}

		public Criteria andRecUpdTsIn(List<Date> values) {
			addCriterion("rec_upd_ts in", values, "recUpdTs");
			return (Criteria) this;
		}

		public Criteria andRecUpdTsNotIn(List<Date> values) {
			addCriterion("rec_upd_ts not in", values, "recUpdTs");
			return (Criteria) this;
		}

		public Criteria andRecUpdTsBetween(Date value1, Date value2) {
			addCriterion("rec_upd_ts between", value1, value2, "recUpdTs");
			return (Criteria) this;
		}

		public Criteria andRecUpdTsNotBetween(Date value1, Date value2) {
			addCriterion("rec_upd_ts not between", value1, value2, "recUpdTs");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_pay_profits
	 * @mbg.generated  Mon Dec 25 14:53:20 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_pay_profits
     *
     * @mbg.generated do_not_delete_during_merge Thu Nov 16 10:53:39 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}