package net.chrone.creditpay.model;

import java.util.Date;

public class ShareImg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_share_img.img_name
     *
     * @mbg.generated Wed Sep 19 15:13:02 CST 2018
     */
    private String imgName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_share_img.img_path
     *
     * @mbg.generated Wed Sep 19 15:13:02 CST 2018
     */
    private String imgPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_share_img.img_sort
     *
     * @mbg.generated Wed Sep 19 15:13:02 CST 2018
     */
    private Integer imgSort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_share_img.img_use
     *
     * @mbg.generated Wed Sep 19 15:13:02 CST 2018
     */
    private Boolean imgUse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_share_img.file_size
     *
     * @mbg.generated Wed Sep 19 15:13:02 CST 2018
     */
    private Integer fileSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_share_img.oper_admin
     *
     * @mbg.generated Wed Sep 19 15:13:02 CST 2018
     */
    private String operAdmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_share_img.create_time
     *
     * @mbg.generated Wed Sep 19 15:13:02 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_share_img.img_name
     *
     * @return the value of t_share_img.img_name
     *
     * @mbg.generated Wed Sep 19 15:13:02 CST 2018
     */
    public String getImgName() {
        return imgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_share_img.img_name
     *
     * @param imgName the value for t_share_img.img_name
     *
     * @mbg.generated Wed Sep 19 15:13:02 CST 2018
     */
    public void setImgName(String imgName) {
        this.imgName = imgName == null ? null : imgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_share_img.img_path
     *
     * @return the value of t_share_img.img_path
     *
     * @mbg.generated Wed Sep 19 15:13:02 CST 2018
     */
    public String getImgPath() {
        return imgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_share_img.img_path
     *
     * @param imgPath the value for t_share_img.img_path
     *
     * @mbg.generated Wed Sep 19 15:13:02 CST 2018
     */
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath == null ? null : imgPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_share_img.img_sort
     *
     * @return the value of t_share_img.img_sort
     *
     * @mbg.generated Wed Sep 19 15:13:02 CST 2018
     */
    public Integer getImgSort() {
        return imgSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_share_img.img_sort
     *
     * @param imgSort the value for t_share_img.img_sort
     *
     * @mbg.generated Wed Sep 19 15:13:02 CST 2018
     */
    public void setImgSort(Integer imgSort) {
        this.imgSort = imgSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_share_img.img_use
     *
     * @return the value of t_share_img.img_use
     *
     * @mbg.generated Wed Sep 19 15:13:02 CST 2018
     */
    public Boolean getImgUse() {
        return imgUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_share_img.img_use
     *
     * @param imgUse the value for t_share_img.img_use
     *
     * @mbg.generated Wed Sep 19 15:13:02 CST 2018
     */
    public void setImgUse(Boolean imgUse) {
        this.imgUse = imgUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_share_img.file_size
     *
     * @return the value of t_share_img.file_size
     *
     * @mbg.generated Wed Sep 19 15:13:02 CST 2018
     */
    public Integer getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_share_img.file_size
     *
     * @param fileSize the value for t_share_img.file_size
     *
     * @mbg.generated Wed Sep 19 15:13:02 CST 2018
     */
    public void setFileSize(Integer fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_share_img.oper_admin
     *
     * @return the value of t_share_img.oper_admin
     *
     * @mbg.generated Wed Sep 19 15:13:02 CST 2018
     */
    public String getOperAdmin() {
        return operAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_share_img.oper_admin
     *
     * @param operAdmin the value for t_share_img.oper_admin
     *
     * @mbg.generated Wed Sep 19 15:13:02 CST 2018
     */
    public void setOperAdmin(String operAdmin) {
        this.operAdmin = operAdmin == null ? null : operAdmin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_share_img.create_time
     *
     * @return the value of t_share_img.create_time
     *
     * @mbg.generated Wed Sep 19 15:13:02 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_share_img.create_time
     *
     * @param createTime the value for t_share_img.create_time
     *
     * @mbg.generated Wed Sep 19 15:13:02 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}