package net.chrone.creditpay.model;

public class UserAwardStatus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_award_status.user_id
     *
     * @mbg.generated Wed Feb 27 10:11:17 CST 2019
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_award_status.reg_award_status
     *
     * @mbg.generated Wed Feb 27 10:11:17 CST 2019
     */
    private Integer regAwardStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_award_status.fastpay_award_status
     *
     * @mbg.generated Wed Feb 27 10:11:17 CST 2019
     */
    private Integer fastpayAwardStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_award_status.wanmei_award_status
     *
     * @mbg.generated Wed Feb 27 10:11:17 CST 2019
     */
    private Integer wanmeiAwardStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_award_status.reserved1
     *
     * @mbg.generated Wed Feb 27 10:11:17 CST 2019
     */
    private String reserved1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_award_status.reserved2
     *
     * @mbg.generated Wed Feb 27 10:11:17 CST 2019
     */
    private String reserved2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_award_status.user_id
     *
     * @return the value of t_user_award_status.user_id
     *
     * @mbg.generated Wed Feb 27 10:11:17 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_award_status.user_id
     *
     * @param userId the value for t_user_award_status.user_id
     *
     * @mbg.generated Wed Feb 27 10:11:17 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_award_status.reg_award_status
     *
     * @return the value of t_user_award_status.reg_award_status
     *
     * @mbg.generated Wed Feb 27 10:11:17 CST 2019
     */
    public Integer getRegAwardStatus() {
        return regAwardStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_award_status.reg_award_status
     *
     * @param regAwardStatus the value for t_user_award_status.reg_award_status
     *
     * @mbg.generated Wed Feb 27 10:11:17 CST 2019
     */
    public void setRegAwardStatus(Integer regAwardStatus) {
        this.regAwardStatus = regAwardStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_award_status.fastpay_award_status
     *
     * @return the value of t_user_award_status.fastpay_award_status
     *
     * @mbg.generated Wed Feb 27 10:11:17 CST 2019
     */
    public Integer getFastpayAwardStatus() {
        return fastpayAwardStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_award_status.fastpay_award_status
     *
     * @param fastpayAwardStatus the value for t_user_award_status.fastpay_award_status
     *
     * @mbg.generated Wed Feb 27 10:11:17 CST 2019
     */
    public void setFastpayAwardStatus(Integer fastpayAwardStatus) {
        this.fastpayAwardStatus = fastpayAwardStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_award_status.wanmei_award_status
     *
     * @return the value of t_user_award_status.wanmei_award_status
     *
     * @mbg.generated Wed Feb 27 10:11:17 CST 2019
     */
    public Integer getWanmeiAwardStatus() {
        return wanmeiAwardStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_award_status.wanmei_award_status
     *
     * @param wanmeiAwardStatus the value for t_user_award_status.wanmei_award_status
     *
     * @mbg.generated Wed Feb 27 10:11:17 CST 2019
     */
    public void setWanmeiAwardStatus(Integer wanmeiAwardStatus) {
        this.wanmeiAwardStatus = wanmeiAwardStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_award_status.reserved1
     *
     * @return the value of t_user_award_status.reserved1
     *
     * @mbg.generated Wed Feb 27 10:11:17 CST 2019
     */
    public String getReserved1() {
        return reserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_award_status.reserved1
     *
     * @param reserved1 the value for t_user_award_status.reserved1
     *
     * @mbg.generated Wed Feb 27 10:11:17 CST 2019
     */
    public void setReserved1(String reserved1) {
        this.reserved1 = reserved1 == null ? null : reserved1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_award_status.reserved2
     *
     * @return the value of t_user_award_status.reserved2
     *
     * @mbg.generated Wed Feb 27 10:11:17 CST 2019
     */
    public String getReserved2() {
        return reserved2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_award_status.reserved2
     *
     * @param reserved2 the value for t_user_award_status.reserved2
     *
     * @mbg.generated Wed Feb 27 10:11:17 CST 2019
     */
    public void setReserved2(String reserved2) {
        this.reserved2 = reserved2 == null ? null : reserved2.trim();
    }
}