package net.chrone.creditpay.model;

import java.util.ArrayList;
import java.util.List;

public class UserAwardStatusExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user_award_status
     *
     * @mbg.generated Wed Feb 27 10:11:17 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user_award_status
     *
     * @mbg.generated Wed Feb 27 10:11:17 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user_award_status
     *
     * @mbg.generated Wed Feb 27 10:11:17 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_award_status
     *
     * @mbg.generated Wed Feb 27 10:11:17 CST 2019
     */
    public UserAwardStatusExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_award_status
     *
     * @mbg.generated Wed Feb 27 10:11:17 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_award_status
     *
     * @mbg.generated Wed Feb 27 10:11:17 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_award_status
     *
     * @mbg.generated Wed Feb 27 10:11:17 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_award_status
     *
     * @mbg.generated Wed Feb 27 10:11:17 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_award_status
     *
     * @mbg.generated Wed Feb 27 10:11:17 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_award_status
     *
     * @mbg.generated Wed Feb 27 10:11:17 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_award_status
     *
     * @mbg.generated Wed Feb 27 10:11:17 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_award_status
     *
     * @mbg.generated Wed Feb 27 10:11:17 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_award_status
     *
     * @mbg.generated Wed Feb 27 10:11:17 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_award_status
     *
     * @mbg.generated Wed Feb 27 10:11:17 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user_award_status
     *
     * @mbg.generated Wed Feb 27 10:11:17 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andRegAwardStatusIsNull() {
            addCriterion("reg_award_status is null");
            return (Criteria) this;
        }

        public Criteria andRegAwardStatusIsNotNull() {
            addCriterion("reg_award_status is not null");
            return (Criteria) this;
        }

        public Criteria andRegAwardStatusEqualTo(Integer value) {
            addCriterion("reg_award_status =", value, "regAwardStatus");
            return (Criteria) this;
        }

        public Criteria andRegAwardStatusNotEqualTo(Integer value) {
            addCriterion("reg_award_status <>", value, "regAwardStatus");
            return (Criteria) this;
        }

        public Criteria andRegAwardStatusGreaterThan(Integer value) {
            addCriterion("reg_award_status >", value, "regAwardStatus");
            return (Criteria) this;
        }

        public Criteria andRegAwardStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("reg_award_status >=", value, "regAwardStatus");
            return (Criteria) this;
        }

        public Criteria andRegAwardStatusLessThan(Integer value) {
            addCriterion("reg_award_status <", value, "regAwardStatus");
            return (Criteria) this;
        }

        public Criteria andRegAwardStatusLessThanOrEqualTo(Integer value) {
            addCriterion("reg_award_status <=", value, "regAwardStatus");
            return (Criteria) this;
        }

        public Criteria andRegAwardStatusIn(List<Integer> values) {
            addCriterion("reg_award_status in", values, "regAwardStatus");
            return (Criteria) this;
        }

        public Criteria andRegAwardStatusNotIn(List<Integer> values) {
            addCriterion("reg_award_status not in", values, "regAwardStatus");
            return (Criteria) this;
        }

        public Criteria andRegAwardStatusBetween(Integer value1, Integer value2) {
            addCriterion("reg_award_status between", value1, value2, "regAwardStatus");
            return (Criteria) this;
        }

        public Criteria andRegAwardStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("reg_award_status not between", value1, value2, "regAwardStatus");
            return (Criteria) this;
        }

        public Criteria andFastpayAwardStatusIsNull() {
            addCriterion("fastpay_award_status is null");
            return (Criteria) this;
        }

        public Criteria andFastpayAwardStatusIsNotNull() {
            addCriterion("fastpay_award_status is not null");
            return (Criteria) this;
        }

        public Criteria andFastpayAwardStatusEqualTo(Integer value) {
            addCriterion("fastpay_award_status =", value, "fastpayAwardStatus");
            return (Criteria) this;
        }

        public Criteria andFastpayAwardStatusNotEqualTo(Integer value) {
            addCriterion("fastpay_award_status <>", value, "fastpayAwardStatus");
            return (Criteria) this;
        }

        public Criteria andFastpayAwardStatusGreaterThan(Integer value) {
            addCriterion("fastpay_award_status >", value, "fastpayAwardStatus");
            return (Criteria) this;
        }

        public Criteria andFastpayAwardStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("fastpay_award_status >=", value, "fastpayAwardStatus");
            return (Criteria) this;
        }

        public Criteria andFastpayAwardStatusLessThan(Integer value) {
            addCriterion("fastpay_award_status <", value, "fastpayAwardStatus");
            return (Criteria) this;
        }

        public Criteria andFastpayAwardStatusLessThanOrEqualTo(Integer value) {
            addCriterion("fastpay_award_status <=", value, "fastpayAwardStatus");
            return (Criteria) this;
        }

        public Criteria andFastpayAwardStatusIn(List<Integer> values) {
            addCriterion("fastpay_award_status in", values, "fastpayAwardStatus");
            return (Criteria) this;
        }

        public Criteria andFastpayAwardStatusNotIn(List<Integer> values) {
            addCriterion("fastpay_award_status not in", values, "fastpayAwardStatus");
            return (Criteria) this;
        }

        public Criteria andFastpayAwardStatusBetween(Integer value1, Integer value2) {
            addCriterion("fastpay_award_status between", value1, value2, "fastpayAwardStatus");
            return (Criteria) this;
        }

        public Criteria andFastpayAwardStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("fastpay_award_status not between", value1, value2, "fastpayAwardStatus");
            return (Criteria) this;
        }

        public Criteria andWanmeiAwardStatusIsNull() {
            addCriterion("wanmei_award_status is null");
            return (Criteria) this;
        }

        public Criteria andWanmeiAwardStatusIsNotNull() {
            addCriterion("wanmei_award_status is not null");
            return (Criteria) this;
        }

        public Criteria andWanmeiAwardStatusEqualTo(Integer value) {
            addCriterion("wanmei_award_status =", value, "wanmeiAwardStatus");
            return (Criteria) this;
        }

        public Criteria andWanmeiAwardStatusNotEqualTo(Integer value) {
            addCriterion("wanmei_award_status <>", value, "wanmeiAwardStatus");
            return (Criteria) this;
        }

        public Criteria andWanmeiAwardStatusGreaterThan(Integer value) {
            addCriterion("wanmei_award_status >", value, "wanmeiAwardStatus");
            return (Criteria) this;
        }

        public Criteria andWanmeiAwardStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("wanmei_award_status >=", value, "wanmeiAwardStatus");
            return (Criteria) this;
        }

        public Criteria andWanmeiAwardStatusLessThan(Integer value) {
            addCriterion("wanmei_award_status <", value, "wanmeiAwardStatus");
            return (Criteria) this;
        }

        public Criteria andWanmeiAwardStatusLessThanOrEqualTo(Integer value) {
            addCriterion("wanmei_award_status <=", value, "wanmeiAwardStatus");
            return (Criteria) this;
        }

        public Criteria andWanmeiAwardStatusIn(List<Integer> values) {
            addCriterion("wanmei_award_status in", values, "wanmeiAwardStatus");
            return (Criteria) this;
        }

        public Criteria andWanmeiAwardStatusNotIn(List<Integer> values) {
            addCriterion("wanmei_award_status not in", values, "wanmeiAwardStatus");
            return (Criteria) this;
        }

        public Criteria andWanmeiAwardStatusBetween(Integer value1, Integer value2) {
            addCriterion("wanmei_award_status between", value1, value2, "wanmeiAwardStatus");
            return (Criteria) this;
        }

        public Criteria andWanmeiAwardStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("wanmei_award_status not between", value1, value2, "wanmeiAwardStatus");
            return (Criteria) this;
        }

        public Criteria andReserved1IsNull() {
            addCriterion("reserved1 is null");
            return (Criteria) this;
        }

        public Criteria andReserved1IsNotNull() {
            addCriterion("reserved1 is not null");
            return (Criteria) this;
        }

        public Criteria andReserved1EqualTo(String value) {
            addCriterion("reserved1 =", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1NotEqualTo(String value) {
            addCriterion("reserved1 <>", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1GreaterThan(String value) {
            addCriterion("reserved1 >", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1GreaterThanOrEqualTo(String value) {
            addCriterion("reserved1 >=", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1LessThan(String value) {
            addCriterion("reserved1 <", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1LessThanOrEqualTo(String value) {
            addCriterion("reserved1 <=", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1Like(String value) {
            addCriterion("reserved1 like", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1NotLike(String value) {
            addCriterion("reserved1 not like", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1In(List<String> values) {
            addCriterion("reserved1 in", values, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1NotIn(List<String> values) {
            addCriterion("reserved1 not in", values, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1Between(String value1, String value2) {
            addCriterion("reserved1 between", value1, value2, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1NotBetween(String value1, String value2) {
            addCriterion("reserved1 not between", value1, value2, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved2IsNull() {
            addCriterion("reserved2 is null");
            return (Criteria) this;
        }

        public Criteria andReserved2IsNotNull() {
            addCriterion("reserved2 is not null");
            return (Criteria) this;
        }

        public Criteria andReserved2EqualTo(String value) {
            addCriterion("reserved2 =", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2NotEqualTo(String value) {
            addCriterion("reserved2 <>", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2GreaterThan(String value) {
            addCriterion("reserved2 >", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2GreaterThanOrEqualTo(String value) {
            addCriterion("reserved2 >=", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2LessThan(String value) {
            addCriterion("reserved2 <", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2LessThanOrEqualTo(String value) {
            addCriterion("reserved2 <=", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2Like(String value) {
            addCriterion("reserved2 like", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2NotLike(String value) {
            addCriterion("reserved2 not like", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2In(List<String> values) {
            addCriterion("reserved2 in", values, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2NotIn(List<String> values) {
            addCriterion("reserved2 not in", values, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2Between(String value1, String value2) {
            addCriterion("reserved2 between", value1, value2, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2NotBetween(String value1, String value2) {
            addCriterion("reserved2 not between", value1, value2, "reserved2");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user_award_status
     *
     * @mbg.generated do_not_delete_during_merge Wed Feb 27 10:11:17 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user_award_status
     *
     * @mbg.generated Wed Feb 27 10:11:17 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}