package net.chrone.creditpay.model;

import java.util.Date;

public class UserAwardDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_award_detail.id
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_award_detail.award_object
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    private Integer awardObject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_award_detail.reg_award_type
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    private Integer regAwardType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_award_detail.reg_award_diruser_money
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    private Integer regAwardDiruserMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_award_detail.reg_award_agent_money
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    private Integer regAwardAgentMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_award_detail.reg_award_begin_time
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    private Date regAwardBeginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_award_detail.fastpay_award_type
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    private Integer fastpayAwardType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_award_detail.fastpay_award_diruser_money
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    private Integer fastpayAwardDiruserMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_award_detail.fastpay_award_agent_money
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    private Integer fastpayAwardAgentMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_award_detail.fastpay_award_total
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    private Integer fastpayAwardTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_award_detail.fastpay_award_begin_time
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    private Date fastpayAwardBeginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_award_detail.wanmei_award_type
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    private Integer wanmeiAwardType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_award_detail.wanmei_award_diruser_money
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    private Integer wanmeiAwardDiruserMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_award_detail.wanmei_award_agent_money
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    private Integer wanmeiAwardAgentMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_award_detail.wanmei_award_total
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    private Integer wanmeiAwardTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_award_detail.wanmei_award_begin_time
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    private Date wanmeiAwardBeginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_award_detail.create_time
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_award_detail.create_user
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    private String createUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_award_detail.id
     *
     * @return the value of t_user_award_detail.id
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_award_detail.id
     *
     * @param id the value for t_user_award_detail.id
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_award_detail.award_object
     *
     * @return the value of t_user_award_detail.award_object
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    public Integer getAwardObject() {
        return awardObject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_award_detail.award_object
     *
     * @param awardObject the value for t_user_award_detail.award_object
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    public void setAwardObject(Integer awardObject) {
        this.awardObject = awardObject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_award_detail.reg_award_type
     *
     * @return the value of t_user_award_detail.reg_award_type
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    public Integer getRegAwardType() {
        return regAwardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_award_detail.reg_award_type
     *
     * @param regAwardType the value for t_user_award_detail.reg_award_type
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    public void setRegAwardType(Integer regAwardType) {
        this.regAwardType = regAwardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_award_detail.reg_award_diruser_money
     *
     * @return the value of t_user_award_detail.reg_award_diruser_money
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    public Integer getRegAwardDiruserMoney() {
        return regAwardDiruserMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_award_detail.reg_award_diruser_money
     *
     * @param regAwardDiruserMoney the value for t_user_award_detail.reg_award_diruser_money
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    public void setRegAwardDiruserMoney(Integer regAwardDiruserMoney) {
        this.regAwardDiruserMoney = regAwardDiruserMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_award_detail.reg_award_agent_money
     *
     * @return the value of t_user_award_detail.reg_award_agent_money
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    public Integer getRegAwardAgentMoney() {
        return regAwardAgentMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_award_detail.reg_award_agent_money
     *
     * @param regAwardAgentMoney the value for t_user_award_detail.reg_award_agent_money
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    public void setRegAwardAgentMoney(Integer regAwardAgentMoney) {
        this.regAwardAgentMoney = regAwardAgentMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_award_detail.reg_award_begin_time
     *
     * @return the value of t_user_award_detail.reg_award_begin_time
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    public Date getRegAwardBeginTime() {
        return regAwardBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_award_detail.reg_award_begin_time
     *
     * @param regAwardBeginTime the value for t_user_award_detail.reg_award_begin_time
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    public void setRegAwardBeginTime(Date regAwardBeginTime) {
        this.regAwardBeginTime = regAwardBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_award_detail.fastpay_award_type
     *
     * @return the value of t_user_award_detail.fastpay_award_type
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    public Integer getFastpayAwardType() {
        return fastpayAwardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_award_detail.fastpay_award_type
     *
     * @param fastpayAwardType the value for t_user_award_detail.fastpay_award_type
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    public void setFastpayAwardType(Integer fastpayAwardType) {
        this.fastpayAwardType = fastpayAwardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_award_detail.fastpay_award_diruser_money
     *
     * @return the value of t_user_award_detail.fastpay_award_diruser_money
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    public Integer getFastpayAwardDiruserMoney() {
        return fastpayAwardDiruserMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_award_detail.fastpay_award_diruser_money
     *
     * @param fastpayAwardDiruserMoney the value for t_user_award_detail.fastpay_award_diruser_money
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    public void setFastpayAwardDiruserMoney(Integer fastpayAwardDiruserMoney) {
        this.fastpayAwardDiruserMoney = fastpayAwardDiruserMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_award_detail.fastpay_award_agent_money
     *
     * @return the value of t_user_award_detail.fastpay_award_agent_money
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    public Integer getFastpayAwardAgentMoney() {
        return fastpayAwardAgentMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_award_detail.fastpay_award_agent_money
     *
     * @param fastpayAwardAgentMoney the value for t_user_award_detail.fastpay_award_agent_money
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    public void setFastpayAwardAgentMoney(Integer fastpayAwardAgentMoney) {
        this.fastpayAwardAgentMoney = fastpayAwardAgentMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_award_detail.fastpay_award_total
     *
     * @return the value of t_user_award_detail.fastpay_award_total
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    public Integer getFastpayAwardTotal() {
        return fastpayAwardTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_award_detail.fastpay_award_total
     *
     * @param fastpayAwardTotal the value for t_user_award_detail.fastpay_award_total
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    public void setFastpayAwardTotal(Integer fastpayAwardTotal) {
        this.fastpayAwardTotal = fastpayAwardTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_award_detail.fastpay_award_begin_time
     *
     * @return the value of t_user_award_detail.fastpay_award_begin_time
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    public Date getFastpayAwardBeginTime() {
        return fastpayAwardBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_award_detail.fastpay_award_begin_time
     *
     * @param fastpayAwardBeginTime the value for t_user_award_detail.fastpay_award_begin_time
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    public void setFastpayAwardBeginTime(Date fastpayAwardBeginTime) {
        this.fastpayAwardBeginTime = fastpayAwardBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_award_detail.wanmei_award_type
     *
     * @return the value of t_user_award_detail.wanmei_award_type
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    public Integer getWanmeiAwardType() {
        return wanmeiAwardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_award_detail.wanmei_award_type
     *
     * @param wanmeiAwardType the value for t_user_award_detail.wanmei_award_type
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    public void setWanmeiAwardType(Integer wanmeiAwardType) {
        this.wanmeiAwardType = wanmeiAwardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_award_detail.wanmei_award_diruser_money
     *
     * @return the value of t_user_award_detail.wanmei_award_diruser_money
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    public Integer getWanmeiAwardDiruserMoney() {
        return wanmeiAwardDiruserMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_award_detail.wanmei_award_diruser_money
     *
     * @param wanmeiAwardDiruserMoney the value for t_user_award_detail.wanmei_award_diruser_money
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    public void setWanmeiAwardDiruserMoney(Integer wanmeiAwardDiruserMoney) {
        this.wanmeiAwardDiruserMoney = wanmeiAwardDiruserMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_award_detail.wanmei_award_agent_money
     *
     * @return the value of t_user_award_detail.wanmei_award_agent_money
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    public Integer getWanmeiAwardAgentMoney() {
        return wanmeiAwardAgentMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_award_detail.wanmei_award_agent_money
     *
     * @param wanmeiAwardAgentMoney the value for t_user_award_detail.wanmei_award_agent_money
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    public void setWanmeiAwardAgentMoney(Integer wanmeiAwardAgentMoney) {
        this.wanmeiAwardAgentMoney = wanmeiAwardAgentMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_award_detail.wanmei_award_total
     *
     * @return the value of t_user_award_detail.wanmei_award_total
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    public Integer getWanmeiAwardTotal() {
        return wanmeiAwardTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_award_detail.wanmei_award_total
     *
     * @param wanmeiAwardTotal the value for t_user_award_detail.wanmei_award_total
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    public void setWanmeiAwardTotal(Integer wanmeiAwardTotal) {
        this.wanmeiAwardTotal = wanmeiAwardTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_award_detail.wanmei_award_begin_time
     *
     * @return the value of t_user_award_detail.wanmei_award_begin_time
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    public Date getWanmeiAwardBeginTime() {
        return wanmeiAwardBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_award_detail.wanmei_award_begin_time
     *
     * @param wanmeiAwardBeginTime the value for t_user_award_detail.wanmei_award_begin_time
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    public void setWanmeiAwardBeginTime(Date wanmeiAwardBeginTime) {
        this.wanmeiAwardBeginTime = wanmeiAwardBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_award_detail.create_time
     *
     * @return the value of t_user_award_detail.create_time
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_award_detail.create_time
     *
     * @param createTime the value for t_user_award_detail.create_time
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_award_detail.create_user
     *
     * @return the value of t_user_award_detail.create_user
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_award_detail.create_user
     *
     * @param createUser the value for t_user_award_detail.create_user
     *
     * @mbg.generated Thu Mar 28 15:12:21 CST 2019
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }
}