package net.chrone.creditpay.mapper;

import java.util.List;
import net.chrone.creditpay.model.AgentMenu;
import net.chrone.creditpay.model.AgentMenuExample;
import org.apache.ibatis.annotations.Param;

public interface AgentMenuMapper extends ParentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_menu_inf
     *
     * @mbggenerated Thu Nov 23 17:06:36 CST 2017
     */
    int countByExample(AgentMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_menu_inf
     *
     * @mbggenerated Thu Nov 23 17:06:36 CST 2017
     */
    int deleteByExample(AgentMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_menu_inf
     *
     * @mbggenerated Thu Nov 23 17:06:36 CST 2017
     */
    int deleteByPrimaryKey(String menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_menu_inf
     *
     * @mbggenerated Thu Nov 23 17:06:36 CST 2017
     */
    int insert(AgentMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_menu_inf
     *
     * @mbggenerated Thu Nov 23 17:06:36 CST 2017
     */
    int insertSelective(AgentMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_menu_inf
     *
     * @mbggenerated Thu Nov 23 17:06:36 CST 2017
     */
    List<AgentMenu> selectByExample(AgentMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_menu_inf
     *
     * @mbggenerated Thu Nov 23 17:06:36 CST 2017
     */
    AgentMenu selectByPrimaryKey(String menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_menu_inf
     *
     * @mbggenerated Thu Nov 23 17:06:36 CST 2017
     */
    int updateByExampleSelective(@Param("record") AgentMenu record, @Param("example") AgentMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_menu_inf
     *
     * @mbggenerated Thu Nov 23 17:06:36 CST 2017
     */
    int updateByExample(@Param("record") AgentMenu record, @Param("example") AgentMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_menu_inf
     *
     * @mbggenerated Thu Nov 23 17:06:36 CST 2017
     */
    int updateByPrimaryKeySelective(AgentMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_menu_inf
     *
     * @mbggenerated Thu Nov 23 17:06:36 CST 2017
     */
    int updateByPrimaryKey(AgentMenu record);
}