package net.chrone.creditpay.mapper;

import java.util.List;
import net.chrone.creditpay.model.AgentRoleMenu;
import net.chrone.creditpay.model.AgentRoleMenuExample;
import org.apache.ibatis.annotations.Param;

public interface AgentRoleMenuMapper extends ParentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_role_menu
     *
     * @mbggenerated Thu Nov 23 17:06:36 CST 2017
     */
    int countByExample(AgentRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_role_menu
     *
     * @mbggenerated Thu Nov 23 17:06:36 CST 2017
     */
    int deleteByExample(AgentRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_role_menu
     *
     * @mbggenerated Thu Nov 23 17:06:36 CST 2017
     */
    int deleteByPrimaryKey(@Param("agentId") String agentId, @Param("menuId") String menuId, @Param("roleId") String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_role_menu
     *
     * @mbggenerated Thu Nov 23 17:06:36 CST 2017
     */
    int insert(AgentRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_role_menu
     *
     * @mbggenerated Thu Nov 23 17:06:36 CST 2017
     */
    int insertSelective(AgentRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_role_menu
     *
     * @mbggenerated Thu Nov 23 17:06:36 CST 2017
     */
    List<AgentRoleMenu> selectByExample(AgentRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_role_menu
     *
     * @mbggenerated Thu Nov 23 17:06:36 CST 2017
     */
    AgentRoleMenu selectByPrimaryKey(@Param("agentId") String agentId, @Param("menuId") String menuId, @Param("roleId") String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_role_menu
     *
     * @mbggenerated Thu Nov 23 17:06:36 CST 2017
     */
    int updateByExampleSelective(@Param("record") AgentRoleMenu record, @Param("example") AgentRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_role_menu
     *
     * @mbggenerated Thu Nov 23 17:06:36 CST 2017
     */
    int updateByExample(@Param("record") AgentRoleMenu record, @Param("example") AgentRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_role_menu
     *
     * @mbggenerated Thu Nov 23 17:06:36 CST 2017
     */
    int updateByPrimaryKeySelective(AgentRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_role_menu
     *
     * @mbggenerated Thu Nov 23 17:06:36 CST 2017
     */
    int updateByPrimaryKey(AgentRoleMenu record);
}