package net.chrone.creditpay.mapper;

import java.util.List;
import net.chrone.creditpay.model.Agent;
import net.chrone.creditpay.model.AgentExample;
import net.chrone.creditpay.model.AgentProfitVO;

import org.apache.ibatis.annotations.Param;

public interface AgentMapper extends ParentMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agent_inf
	 * @mbg.generated  Wed Apr 03 16:38:39 CST 2019
	 */
	long countByExample(AgentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agent_inf
	 * @mbg.generated  Wed Apr 03 16:38:39 CST 2019
	 */
	int deleteByExample(AgentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agent_inf
	 * @mbg.generated  Wed Apr 03 16:38:39 CST 2019
	 */
	int deleteByPrimaryKey(String agentId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agent_inf
	 * @mbg.generated  Wed Apr 03 16:38:39 CST 2019
	 */
	int insert(Agent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agent_inf
	 * @mbg.generated  Wed Apr 03 16:38:39 CST 2019
	 */
	int insertSelective(Agent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agent_inf
	 * @mbg.generated  Wed Apr 03 16:38:39 CST 2019
	 */List<Agent> selectByExample(AgentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agent_inf
	 * @mbg.generated  Wed Apr 03 16:38:39 CST 2019
	 */
	Agent selectByPrimaryKey(String agentId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agent_inf
	 * @mbg.generated  Wed Apr 03 16:38:39 CST 2019
	 */int updateByExampleSelective(@Param("record") Agent record,@Param("example") AgentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agent_inf
	 * @mbg.generated  Wed Apr 03 16:38:39 CST 2019
	 */int updateByExample(@Param("record") Agent record,@Param("example") AgentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agent_inf
	 * @mbg.generated  Wed Apr 03 16:38:39 CST 2019
	 */
	int updateByPrimaryKeySelective(Agent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agent_inf
	 * @mbg.generated  Wed Apr 03 16:38:39 CST 2019
	 */
	int updateByPrimaryKey(Agent record);

	int getAgentByPageCount(Agent agent);

	List<Agent> getAgentByPage(Agent agent);
	
	String getSUBAgentIdByAgentId(String agentId);

	int getAgentUserStatisticsCount(Agent agent);

	List<Agent> getAgentUserStatisticsByPage(Agent agent);
}