package net.chrone.creditpay.mapper;

import java.util.List;
import net.chrone.creditpay.model.AgentFeeRate;
import net.chrone.creditpay.model.AgentFeeRateExample;
import org.apache.ibatis.annotations.Param;

public interface AgentFeeRateMapper extends ParentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agent_fee_rate
	 * @mbg.generated  Wed Apr 03 19:53:24 CST 2019
	 */
	long countByExample(AgentFeeRateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agent_fee_rate
	 * @mbg.generated  Wed Apr 03 19:53:24 CST 2019
	 */
	int deleteByExample(AgentFeeRateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agent_fee_rate
	 * @mbg.generated  Wed Apr 03 19:53:24 CST 2019
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agent_fee_rate
	 * @mbg.generated  Wed Apr 03 19:53:24 CST 2019
	 */
	int insert(AgentFeeRate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agent_fee_rate
	 * @mbg.generated  Wed Apr 03 19:53:24 CST 2019
	 */
	int insertSelective(AgentFeeRate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agent_fee_rate
	 * @mbg.generated  Wed Apr 03 19:53:24 CST 2019
	 */List<AgentFeeRate> selectByExample(AgentFeeRateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agent_fee_rate
	 * @mbg.generated  Wed Apr 03 19:53:24 CST 2019
	 */
	AgentFeeRate selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agent_fee_rate
	 * @mbg.generated  Wed Apr 03 19:53:24 CST 2019
	 */int updateByExampleSelective(@Param("record") AgentFeeRate record,@Param("example") AgentFeeRateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agent_fee_rate
	 * @mbg.generated  Wed Apr 03 19:53:24 CST 2019
	 */int updateByExample(@Param("record") AgentFeeRate record,@Param("example") AgentFeeRateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agent_fee_rate
	 * @mbg.generated  Wed Apr 03 19:53:24 CST 2019
	 */
	int updateByPrimaryKeySelective(AgentFeeRate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agent_fee_rate
	 * @mbg.generated  Wed Apr 03 19:53:24 CST 2019
	 */
	int updateByPrimaryKey(AgentFeeRate record);
}