package net.chrone.creditpay.mapper;

import java.util.List;
import net.chrone.creditpay.model.AgentLevel;
import net.chrone.creditpay.model.AgentLevelExample;
import org.apache.ibatis.annotations.Param;

public interface AgentLevelMapper extends ParentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_level
     *
     * @mbg.generated Tue Feb 19 13:42:56 CST 2019
     */
    long countByExample(AgentLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_level
     *
     * @mbg.generated Tue Feb 19 13:42:56 CST 2019
     */
    int deleteByExample(AgentLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_level
     *
     * @mbg.generated Tue Feb 19 13:42:56 CST 2019
     */
    int deleteByPrimaryKey(Integer levelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_level
     *
     * @mbg.generated Tue Feb 19 13:42:56 CST 2019
     */
    int insert(AgentLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_level
     *
     * @mbg.generated Tue Feb 19 13:42:56 CST 2019
     */
    int insertSelective(AgentLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_level
     *
     * @mbg.generated Tue Feb 19 13:42:56 CST 2019
     */
    List<AgentLevel> selectByExample(AgentLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_level
     *
     * @mbg.generated Tue Feb 19 13:42:56 CST 2019
     */
    AgentLevel selectByPrimaryKey(Integer levelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_level
     *
     * @mbg.generated Tue Feb 19 13:42:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") AgentLevel record, @Param("example") AgentLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_level
     *
     * @mbg.generated Tue Feb 19 13:42:56 CST 2019
     */
    int updateByExample(@Param("record") AgentLevel record, @Param("example") AgentLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_level
     *
     * @mbg.generated Tue Feb 19 13:42:56 CST 2019
     */
    int updateByPrimaryKeySelective(AgentLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_level
     *
     * @mbg.generated Tue Feb 19 13:42:56 CST 2019
     */
    int updateByPrimaryKey(AgentLevel record);
}