package net.chrone.creditpay.mapper;

import net.chrone.creditpay.model.AppBanner;
import net.chrone.creditpay.model.AppBannerExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AppBannerMapper extends ParentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app_banner
     *
     * @mbggenerated Tue Oct 29 16:28:37 CST 2019
     */
    int countByExample(AppBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app_banner
     *
     * @mbggenerated Tue Oct 29 16:28:37 CST 2019
     */
    int deleteByExample(AppBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app_banner
     *
     * @mbggenerated Tue Oct 29 16:28:37 CST 2019
     */
    int deleteByPrimaryKey(String bannerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app_banner
     *
     * @mbggenerated Tue Oct 29 16:28:37 CST 2019
     */
    int insert(AppBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app_banner
     *
     * @mbggenerated Tue Oct 29 16:28:37 CST 2019
     */
    int insertSelective(AppBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app_banner
     *
     * @mbggenerated Tue Oct 29 16:28:37 CST 2019
     */
    List<AppBanner> selectByExample(AppBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app_banner
     *
     * @mbggenerated Tue Oct 29 16:28:37 CST 2019
     */
    AppBanner selectByPrimaryKey(String bannerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app_banner
     *
     * @mbggenerated Tue Oct 29 16:28:37 CST 2019
     */
    int updateByExampleSelective(@Param("record") AppBanner record, @Param("example") AppBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app_banner
     *
     * @mbggenerated Tue Oct 29 16:28:37 CST 2019
     */
    int updateByExample(@Param("record") AppBanner record, @Param("example") AppBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app_banner
     *
     * @mbggenerated Tue Oct 29 16:28:37 CST 2019
     */
    int updateByPrimaryKeySelective(AppBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app_banner
     *
     * @mbggenerated Tue Oct 29 16:28:37 CST 2019
     */
    int updateByPrimaryKey(AppBanner record);


    List<AppBanner> selectBannerByPage(AppBanner appBanner);

    AppBanner selectBannerByBannerName(String bannerName);
}