package net.chrone.creditpay.mapper;

import java.util.List;
import java.util.Map;

import net.chrone.creditpay.model.AppUser;
import net.chrone.creditpay.model.AppUserExample;
import org.apache.ibatis.annotations.Param;

public interface AppUserMapper extends ParentMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_app_user
	 * @mbg.generated  Mon Dec 18 18:05:52 CST 2017
	 */
	int countByExample(AppUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_app_user
	 * @mbg.generated  Mon Dec 18 18:05:52 CST 2017
	 */
	int deleteByExample(AppUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_app_user
	 * @mbg.generated  Mon Dec 18 18:05:52 CST 2017
	 */
	int deleteByPrimaryKey(String userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_app_user
	 * @mbg.generated  Mon Dec 18 18:05:52 CST 2017
	 */
	int insert(AppUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_app_user
	 * @mbg.generated  Mon Dec 18 18:05:52 CST 2017
	 */
	int insertSelective(AppUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_app_user
	 * @mbg.generated  Mon Dec 18 18:05:52 CST 2017
	 */
	List<AppUser> selectByExample(AppUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_app_user
	 * @mbg.generated  Mon Dec 18 18:05:52 CST 2017
	 */
	AppUser selectByPrimaryKey(String userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_app_user
	 * @mbg.generated  Mon Dec 18 18:05:52 CST 2017
	 */
	int updateByExampleSelective(@Param("record") AppUser record, @Param("example") AppUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_app_user
	 * @mbg.generated  Mon Dec 18 18:05:52 CST 2017
	 */
	int updateByExample(@Param("record") AppUser record, @Param("example") AppUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_app_user
	 * @mbg.generated  Mon Dec 18 18:05:52 CST 2017
	 */
	int updateByPrimaryKeySelective(AppUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_app_user
	 * @mbg.generated  Mon Dec 18 18:05:52 CST 2017
	 */
	int updateByPrimaryKey(AppUser record);

	int getAppUserByPageCount(AppUser appuser);

	List<AppUser> getAppUserByPage(AppUser appuser);

	List<String> getAppUserByParentIdList(Map<String, Object> map);
	
	int updateAppUserAgentIdByParentUserId(AppUser appUser);

	List<AppUser> getUserLikeUserId(String userId);
	
	//等级分布
	List<Map<String, Object>> levelDistribution();
	
	/**
	 * 日增统计
	 * @param appUser
	 * @return
	 */
	List<Map<String, Object>> listIncreasing(AppUser appUser);
	
}