package net.chrone.creditpay.mapper;

import java.util.List;
import java.util.Map;

import net.chrone.creditpay.model.CardValuate;
import net.chrone.creditpay.model.CardValuateExample;
import org.apache.ibatis.annotations.Param;

public interface CardValuateMapper extends ParentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card_valuate
     *
     * @mbg.generated Thu Apr 11 14:01:47 CST 2019
     */
    long countByExample(CardValuateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card_valuate
     *
     * @mbg.generated Thu Apr 11 14:01:47 CST 2019
     */
    int deleteByExample(CardValuateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card_valuate
     *
     * @mbg.generated Thu Apr 11 14:01:47 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card_valuate
     *
     * @mbg.generated Thu Apr 11 14:01:47 CST 2019
     */
    int insert(CardValuate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card_valuate
     *
     * @mbg.generated Thu Apr 11 14:01:47 CST 2019
     */
    int insertSelective(CardValuate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card_valuate
     *
     * @mbg.generated Thu Apr 11 14:01:47 CST 2019
     */
    List<CardValuate> selectByExample(CardValuateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card_valuate
     *
     * @mbg.generated Thu Apr 11 14:01:47 CST 2019
     */
    CardValuate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card_valuate
     *
     * @mbg.generated Thu Apr 11 14:01:47 CST 2019
     */
    int updateByExampleSelective(@Param("record") CardValuate record, @Param("example") CardValuateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card_valuate
     *
     * @mbg.generated Thu Apr 11 14:01:47 CST 2019
     */
    int updateByExample(@Param("record") CardValuate record, @Param("example") CardValuateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card_valuate
     *
     * @mbg.generated Thu Apr 11 14:01:47 CST 2019
     */
    int updateByPrimaryKeySelective(CardValuate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card_valuate
     *
     * @mbg.generated Thu Apr 11 14:01:47 CST 2019
     */
    int updateByPrimaryKey(CardValuate record);

	Map<String, Object> countCardValuate(CardValuate cardValuate);

	List<CardValuate> listCardValuatePage(CardValuate cardValuate);
}