package net.chrone.creditpay.mapper;

import java.util.List;
import net.chrone.creditpay.model.Coupon;
import net.chrone.creditpay.model.CouponExample;
import net.chrone.creditpay.model.Level;

import org.apache.ibatis.annotations.Param;

public interface CouponMapper extends ParentMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_coupon
	 * @mbggenerated  Thu Nov 30 15:11:11 CST 2017
	 */
	int countByExample(CouponExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_coupon
	 * @mbggenerated  Thu Nov 30 15:11:11 CST 2017
	 */
	int deleteByExample(CouponExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_coupon
	 * @mbggenerated  Thu Nov 30 15:11:11 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_coupon
	 * @mbggenerated  Thu Nov 30 15:11:11 CST 2017
	 */
	int insert(Coupon record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_coupon
	 * @mbggenerated  Thu Nov 30 15:11:11 CST 2017
	 */
	int insertSelective(Coupon record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_coupon
	 * @mbggenerated  Thu Nov 30 15:11:11 CST 2017
	 */List<Coupon> selectByExample(CouponExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_coupon
	 * @mbggenerated  Thu Nov 30 15:11:11 CST 2017
	 */
	Coupon selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_coupon
	 * @mbggenerated  Thu Nov 30 15:11:11 CST 2017
	 */int updateByExampleSelective(@Param("record") Coupon record,@Param("example") CouponExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_coupon
	 * @mbggenerated  Thu Nov 30 15:11:11 CST 2017
	 */int updateByExample(@Param("record") Coupon record,@Param("example") CouponExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_coupon
	 * @mbggenerated  Thu Nov 30 15:11:11 CST 2017
	 */
	int updateByPrimaryKeySelective(Coupon record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_coupon
	 * @mbggenerated  Thu Nov 30 15:11:11 CST 2017
	 */
	int updateByPrimaryKey(Coupon record);

	int countCoupons(Coupon coupon);

	List<Coupon> listcoupons(Coupon coupon);
	
	Coupon getCouponByPrimaayKey(String id);
	
	List<Level> listLevels(String id);
}