package net.chrone.creditpay.mapper;

import java.util.List;
import net.chrone.creditpay.model.CouponLevel;
import net.chrone.creditpay.model.CouponLevelExample;
import org.apache.ibatis.annotations.Param;

public interface CouponLevelMapper extends ParentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon_level
     *
     * @mbggenerated Mon Nov 27 18:09:20 CST 2017
     */
    int countByExample(CouponLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon_level
     *
     * @mbggenerated Mon Nov 27 18:09:20 CST 2017
     */
    int deleteByExample(CouponLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon_level
     *
     * @mbggenerated Mon Nov 27 18:09:20 CST 2017
     */
    int deleteByPrimaryKey(@Param("id") String id, @Param("levelId") Integer levelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon_level
     *
     * @mbggenerated Mon Nov 27 18:09:20 CST 2017
     */
    int insert(CouponLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon_level
     *
     * @mbggenerated Mon Nov 27 18:09:20 CST 2017
     */
    int insertSelective(CouponLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon_level
     *
     * @mbggenerated Mon Nov 27 18:09:20 CST 2017
     */
    List<CouponLevel> selectByExample(CouponLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon_level
     *
     * @mbggenerated Mon Nov 27 18:09:20 CST 2017
     */
    int updateByExampleSelective(@Param("record") CouponLevel record, @Param("example") CouponLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon_level
     *
     * @mbggenerated Mon Nov 27 18:09:20 CST 2017
     */
    int updateByExample(@Param("record") CouponLevel record, @Param("example") CouponLevelExample example);
}