package net.chrone.creditpay.mapper;

import java.util.List;
import net.chrone.creditpay.model.CreditRootBank;
import net.chrone.creditpay.model.CreditRootBankExample;
import org.apache.ibatis.annotations.Param;

public interface CreditRootBankMapper extends ParentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_credit_root_bank
     *
     * @mbg.generated Fri Jan 18 10:51:52 CST 2019
     */
    long countByExample(CreditRootBankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_credit_root_bank
     *
     * @mbg.generated Fri Jan 18 10:51:52 CST 2019
     */
    int deleteByExample(CreditRootBankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_credit_root_bank
     *
     * @mbg.generated Fri Jan 18 10:51:52 CST 2019
     */
    int deleteByPrimaryKey(String bankNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_credit_root_bank
     *
     * @mbg.generated Fri Jan 18 10:51:52 CST 2019
     */
    int insert(CreditRootBank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_credit_root_bank
     *
     * @mbg.generated Fri Jan 18 10:51:52 CST 2019
     */
    int insertSelective(CreditRootBank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_credit_root_bank
     *
     * @mbg.generated Fri Jan 18 10:51:52 CST 2019
     */
    List<CreditRootBank> selectByExample(CreditRootBankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_credit_root_bank
     *
     * @mbg.generated Fri Jan 18 10:51:52 CST 2019
     */
    CreditRootBank selectByPrimaryKey(String bankNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_credit_root_bank
     *
     * @mbg.generated Fri Jan 18 10:51:52 CST 2019
     */
    int updateByExampleSelective(@Param("record") CreditRootBank record, @Param("example") CreditRootBankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_credit_root_bank
     *
     * @mbg.generated Fri Jan 18 10:51:52 CST 2019
     */
    int updateByExample(@Param("record") CreditRootBank record, @Param("example") CreditRootBankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_credit_root_bank
     *
     * @mbg.generated Fri Jan 18 10:51:52 CST 2019
     */
    int updateByPrimaryKeySelective(CreditRootBank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_credit_root_bank
     *
     * @mbg.generated Fri Jan 18 10:51:52 CST 2019
     */
    int updateByPrimaryKey(CreditRootBank record);
}