package net.chrone.creditpay.mapper;

import java.util.List;
import java.util.Map;

import net.chrone.creditpay.model.FastProfits;
import net.chrone.creditpay.model.FastProfitsExample;
import org.apache.ibatis.annotations.Param;

public interface FastProfitsMapper extends ParentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fast_profits
     *
     * @mbg.generated Fri Apr 27 14:39:15 CST 2018
     */
    long countByExample(FastProfitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fast_profits
     *
     * @mbg.generated Fri Apr 27 14:39:15 CST 2018
     */
    int deleteByExample(FastProfitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fast_profits
     *
     * @mbg.generated Fri Apr 27 14:39:15 CST 2018
     */
    int deleteByPrimaryKey(String profitsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fast_profits
     *
     * @mbg.generated Fri Apr 27 14:39:15 CST 2018
     */
    int insert(FastProfits record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fast_profits
     *
     * @mbg.generated Fri Apr 27 14:39:15 CST 2018
     */
    int insertSelective(FastProfits record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fast_profits
     *
     * @mbg.generated Fri Apr 27 14:39:15 CST 2018
     */
    List<FastProfits> selectByExample(FastProfitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fast_profits
     *
     * @mbg.generated Fri Apr 27 14:39:15 CST 2018
     */
    FastProfits selectByPrimaryKey(String profitsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fast_profits
     *
     * @mbg.generated Fri Apr 27 14:39:15 CST 2018
     */
    int updateByExampleSelective(@Param("record") FastProfits record, @Param("example") FastProfitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fast_profits
     *
     * @mbg.generated Fri Apr 27 14:39:15 CST 2018
     */
    int updateByExample(@Param("record") FastProfits record, @Param("example") FastProfitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fast_profits
     *
     * @mbg.generated Fri Apr 27 14:39:15 CST 2018
     */
    int updateByPrimaryKeySelective(FastProfits record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fast_profits
     *
     * @mbg.generated Fri Apr 27 14:39:15 CST 2018
     */
    int updateByPrimaryKey(FastProfits record);
    
    
    Map<String, Object> countFastProfits(FastProfits fastProfits);
    
    List<FastProfits> listFastProfitsPage(FastProfits fastProfits);
    
    
}