package net.chrone.creditpay.mapper;

import java.util.List;
import java.util.Map;

import net.chrone.creditpay.model.FastOrder;
import net.chrone.creditpay.model.FastOrderExample;
import org.apache.ibatis.annotations.Param;

public interface FastOrderMapper extends ParentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fast_order
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    long countByExample(FastOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fast_order
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    int deleteByExample(FastOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fast_order
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    int deleteByPrimaryKey(String orderNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fast_order
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    int insert(FastOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fast_order
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    int insertSelective(FastOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fast_order
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    List<FastOrder> selectByExample(FastOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fast_order
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    FastOrder selectByPrimaryKey(String orderNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fast_order
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    int updateByExampleSelective(@Param("record") FastOrder record, @Param("example") FastOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fast_order
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    int updateByExample(@Param("record") FastOrder record, @Param("example") FastOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fast_order
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    int updateByPrimaryKeySelective(FastOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fast_order
     *
     * @mbg.generated Tue Jan 09 15:08:53 CST 2018
     */
    int updateByPrimaryKey(FastOrder record);

	Map<String, Object> getOrderByPageCount(FastOrder order);

	List<FastOrder> getOrderByPage(FastOrder order);
}