package net.chrone.creditpay.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import net.chrone.creditpay.model.FastProfitsDetail;
import net.chrone.creditpay.model.FastProfitsDetailExample;

public interface FastProfitsDetailMapper extends ParentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fast_profits_detail
     *
     * @mbg.generated Fri Apr 27 14:39:15 CST 2018
     */
    long countByExample(FastProfitsDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fast_profits_detail
     *
     * @mbg.generated Fri Apr 27 14:39:15 CST 2018
     */
    int deleteByExample(FastProfitsDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fast_profits_detail
     *
     * @mbg.generated Fri Apr 27 14:39:15 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fast_profits_detail
     *
     * @mbg.generated Fri Apr 27 14:39:15 CST 2018
     */
    int insert(FastProfitsDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fast_profits_detail
     *
     * @mbg.generated Fri Apr 27 14:39:15 CST 2018
     */
    int insertSelective(FastProfitsDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fast_profits_detail
     *
     * @mbg.generated Fri Apr 27 14:39:15 CST 2018
     */
    List<FastProfitsDetail> selectByExample(FastProfitsDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fast_profits_detail
     *
     * @mbg.generated Fri Apr 27 14:39:15 CST 2018
     */
    FastProfitsDetail selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fast_profits_detail
     *
     * @mbg.generated Fri Apr 27 14:39:15 CST 2018
     */
    int updateByExampleSelective(@Param("record") FastProfitsDetail record, @Param("example") FastProfitsDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fast_profits_detail
     *
     * @mbg.generated Fri Apr 27 14:39:15 CST 2018
     */
    int updateByExample(@Param("record") FastProfitsDetail record, @Param("example") FastProfitsDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fast_profits_detail
     *
     * @mbg.generated Fri Apr 27 14:39:15 CST 2018
     */
    int updateByPrimaryKeySelective(FastProfitsDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fast_profits_detail
     *
     * @mbg.generated Fri Apr 27 14:39:15 CST 2018
     */
    int updateByPrimaryKey(FastProfitsDetail record);
    
    
    List<FastProfitsDetail> listFastProfitsDetail(String profitsId);
}