package net.chrone.creditpay.mapper;

import java.util.List;
import net.chrone.creditpay.model.Level;
import net.chrone.creditpay.model.LevelExample;
import org.apache.ibatis.annotations.Param;

public interface LevelMapper extends ParentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_level_inf
	 * @mbg.generated  Wed Nov 22 11:21:13 CST 2017
	 */
	long countByExample(LevelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_level_inf
	 * @mbg.generated  Wed Nov 22 11:21:13 CST 2017
	 */
	int deleteByExample(LevelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_level_inf
	 * @mbg.generated  Wed Nov 22 11:21:13 CST 2017
	 */
	int deleteByPrimaryKey(Integer levelId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_level_inf
	 * @mbg.generated  Wed Nov 22 11:21:13 CST 2017
	 */
	int insert(Level record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_level_inf
	 * @mbg.generated  Wed Nov 22 11:21:13 CST 2017
	 */
	int insertSelective(Level record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_level_inf
	 * @mbg.generated  Wed Nov 22 11:21:13 CST 2017
	 */
	List<Level> selectByExample(LevelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_level_inf
	 * @mbg.generated  Wed Nov 22 11:21:13 CST 2017
	 */
	Level selectByPrimaryKey(Integer levelId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_level_inf
	 * @mbg.generated  Wed Nov 22 11:21:13 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Level record, @Param("example") LevelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_level_inf
	 * @mbg.generated  Wed Nov 22 11:21:13 CST 2017
	 */
	int updateByExample(@Param("record") Level record, @Param("example") LevelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_level_inf
	 * @mbg.generated  Wed Nov 22 11:21:13 CST 2017
	 */
	int updateByPrimaryKeySelective(Level record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_level_inf
	 * @mbg.generated  Wed Nov 22 11:21:13 CST 2017
	 */
	int updateByPrimaryKey(Level record);
}