package net.chrone.creditpay.mapper;

import java.util.List;
import java.util.Map;

import net.chrone.creditpay.model.LevelOrder;
import net.chrone.creditpay.model.LevelOrderExample;
import org.apache.ibatis.annotations.Param;

public interface LevelOrderMapper extends ParentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_level_order
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    long countByExample(LevelOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_level_order
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    int deleteByExample(LevelOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_level_order
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    int deleteByPrimaryKey(String orderNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_level_order
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    int insert(LevelOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_level_order
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    int insertSelective(LevelOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_level_order
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    List<LevelOrder> selectByExample(LevelOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_level_order
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    LevelOrder selectByPrimaryKey(String orderNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_level_order
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    int updateByExampleSelective(@Param("record") LevelOrder record, @Param("example") LevelOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_level_order
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    int updateByExample(@Param("record") LevelOrder record, @Param("example") LevelOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_level_order
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    int updateByPrimaryKeySelective(LevelOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_level_order
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    int updateByPrimaryKey(LevelOrder record);

    Map<String, Object> getLevelOrderByPageCount(LevelOrder levelOrder);

	List<LevelOrder> getLevelOrderByPage(LevelOrder levelOrder);
}