package net.chrone.creditpay.mapper;

import java.util.List;
import net.chrone.creditpay.model.LotteryDetail;
import net.chrone.creditpay.model.LotteryDetailExample;
import org.apache.ibatis.annotations.Param;

public interface LotteryDetailMapper extends ParentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lottery_detail
     *
     * @mbggenerated Tue Nov 28 17:42:10 CST 2017
     */
    int countByExample(LotteryDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lottery_detail
     *
     * @mbggenerated Tue Nov 28 17:42:10 CST 2017
     */
    int deleteByExample(LotteryDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lottery_detail
     *
     * @mbggenerated Tue Nov 28 17:42:10 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lottery_detail
     *
     * @mbggenerated Tue Nov 28 17:42:10 CST 2017
     */
    int insert(LotteryDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lottery_detail
     *
     * @mbggenerated Tue Nov 28 17:42:10 CST 2017
     */
    int insertSelective(LotteryDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lottery_detail
     *
     * @mbggenerated Tue Nov 28 17:42:10 CST 2017
     */
    List<LotteryDetail> selectByExample(LotteryDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lottery_detail
     *
     * @mbggenerated Tue Nov 28 17:42:10 CST 2017
     */
    LotteryDetail selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lottery_detail
     *
     * @mbggenerated Tue Nov 28 17:42:10 CST 2017
     */
    int updateByExampleSelective(@Param("record") LotteryDetail record, @Param("example") LotteryDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lottery_detail
     *
     * @mbggenerated Tue Nov 28 17:42:10 CST 2017
     */
    int updateByExample(@Param("record") LotteryDetail record, @Param("example") LotteryDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lottery_detail
     *
     * @mbggenerated Tue Nov 28 17:42:10 CST 2017
     */
    int updateByPrimaryKeySelective(LotteryDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lottery_detail
     *
     * @mbggenerated Tue Nov 28 17:42:10 CST 2017
     */
    int updateByPrimaryKey(LotteryDetail record);
    
    int countLotteryDetail(LotteryDetail lotteryDetail);
	
	List<LotteryDetail> listLotteryDetail(LotteryDetail lotteryDetail);
}