package net.chrone.creditpay.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import net.chrone.creditpay.model.PayPlanTask;
import net.chrone.creditpay.model.PayPlanTaskExample;

public interface PayPlanTaskMapper extends ParentMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pay_plan_task
	 * @mbg.generated  Wed Dec 12 09:56:45 CST 2018
	 */
	long countByExample(PayPlanTaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pay_plan_task
	 * @mbg.generated  Wed Dec 12 09:56:45 CST 2018
	 */
	int deleteByExample(PayPlanTaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pay_plan_task
	 * @mbg.generated  Wed Dec 12 09:56:45 CST 2018
	 */
	int deleteByPrimaryKey(String taskId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pay_plan_task
	 * @mbg.generated  Wed Dec 12 09:56:45 CST 2018
	 */
	int insert(PayPlanTask record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pay_plan_task
	 * @mbg.generated  Wed Dec 12 09:56:45 CST 2018
	 */
	int insertSelective(PayPlanTask record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pay_plan_task
	 * @mbg.generated  Wed Dec 12 09:56:45 CST 2018
	 */List<PayPlanTask> selectByExample(PayPlanTaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pay_plan_task
	 * @mbg.generated  Wed Dec 12 09:56:45 CST 2018
	 */
	PayPlanTask selectByPrimaryKey(String taskId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pay_plan_task
	 * @mbg.generated  Wed Dec 12 09:56:45 CST 2018
	 */int updateByExampleSelective(@Param("record") PayPlanTask record,@Param("example") PayPlanTaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pay_plan_task
	 * @mbg.generated  Wed Dec 12 09:56:45 CST 2018
	 */int updateByExample(@Param("record") PayPlanTask record,@Param("example") PayPlanTaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pay_plan_task
	 * @mbg.generated  Wed Dec 12 09:56:45 CST 2018
	 */
	int updateByPrimaryKeySelective(PayPlanTask record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pay_plan_task
	 * @mbg.generated  Wed Dec 12 09:56:45 CST 2018
	 */
	int updateByPrimaryKey(PayPlanTask record);

	Map<String, Object> getPayPlanTaskByPageCount(PayPlanTask payPlanTask);

	List<PayPlanTask>  getPayPlanTaskByPage(PayPlanTask payPlanTask);
	
	Map<String, Object> yesterdayTask(String dateTime);
	
	Map<String, Object> taskRealTimeStatistics(@Param("dateTime")String dateTime);
	
	Map<String, Object> countTaskStatistics(PayPlanTask payPlanTask);
	
	List<Map<String, Object>> listTaskStatistics(PayPlanTask payPlanTask);
}