package net.chrone.creditpay.mapper;

import java.util.List;
import java.util.Map;

import net.chrone.creditpay.model.PayProfits;
import net.chrone.creditpay.model.PayProfitsExample;
import org.apache.ibatis.annotations.Param;

public interface PayProfitsMapper extends ParentMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pay_profits
	 * @mbg.generated  Mon Dec 25 14:53:20 CST 2017
	 */
	long countByExample(PayProfitsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pay_profits
	 * @mbg.generated  Mon Dec 25 14:53:20 CST 2017
	 */
	int deleteByExample(PayProfitsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pay_profits
	 * @mbg.generated  Mon Dec 25 14:53:20 CST 2017
	 */
	int deleteByPrimaryKey(String profitsId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pay_profits
	 * @mbg.generated  Mon Dec 25 14:53:20 CST 2017
	 */
	int insert(PayProfits record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pay_profits
	 * @mbg.generated  Mon Dec 25 14:53:20 CST 2017
	 */
	int insertSelective(PayProfits record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pay_profits
	 * @mbg.generated  Mon Dec 25 14:53:20 CST 2017
	 */
	List<PayProfits> selectByExample(PayProfitsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pay_profits
	 * @mbg.generated  Mon Dec 25 14:53:20 CST 2017
	 */
	PayProfits selectByPrimaryKey(String profitsId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pay_profits
	 * @mbg.generated  Mon Dec 25 14:53:20 CST 2017
	 */
	int updateByExampleSelective(@Param("record") PayProfits record, @Param("example") PayProfitsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pay_profits
	 * @mbg.generated  Mon Dec 25 14:53:20 CST 2017
	 */
	int updateByExample(@Param("record") PayProfits record, @Param("example") PayProfitsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pay_profits
	 * @mbg.generated  Mon Dec 25 14:53:20 CST 2017
	 */
	int updateByPrimaryKeySelective(PayProfits record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pay_profits
	 * @mbg.generated  Mon Dec 25 14:53:20 CST 2017
	 */
	int updateByPrimaryKey(PayProfits record);

	Map<String, Object> countPayProfits(PayProfits payProfits);
    
    List<PayProfits> listPayProfitsPage(PayProfits payProfits);
}