package net.chrone.creditpay.mapper;

import java.util.List;
import net.chrone.creditpay.model.PayPlanTaskTemp;
import net.chrone.creditpay.model.PayPlanTaskTempExample;
import org.apache.ibatis.annotations.Param;

public interface PayPlanTaskTempMapper extends ParentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_plan_task_temp
     *
     * @mbg.generated Tue Mar 13 16:11:45 CST 2018
     */
    long countByExample(PayPlanTaskTempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_plan_task_temp
     *
     * @mbg.generated Tue Mar 13 16:11:45 CST 2018
     */
    int deleteByExample(PayPlanTaskTempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_plan_task_temp
     *
     * @mbg.generated Tue Mar 13 16:11:45 CST 2018
     */
    int deleteByPrimaryKey(String taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_plan_task_temp
     *
     * @mbg.generated Tue Mar 13 16:11:45 CST 2018
     */
    int insert(PayPlanTaskTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_plan_task_temp
     *
     * @mbg.generated Tue Mar 13 16:11:45 CST 2018
     */
    int insertSelective(PayPlanTaskTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_plan_task_temp
     *
     * @mbg.generated Tue Mar 13 16:11:45 CST 2018
     */
    List<PayPlanTaskTemp> selectByExample(PayPlanTaskTempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_plan_task_temp
     *
     * @mbg.generated Tue Mar 13 16:11:45 CST 2018
     */
    PayPlanTaskTemp selectByPrimaryKey(String taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_plan_task_temp
     *
     * @mbg.generated Tue Mar 13 16:11:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") PayPlanTaskTemp record, @Param("example") PayPlanTaskTempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_plan_task_temp
     *
     * @mbg.generated Tue Mar 13 16:11:45 CST 2018
     */
    int updateByExample(@Param("record") PayPlanTaskTemp record, @Param("example") PayPlanTaskTempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_plan_task_temp
     *
     * @mbg.generated Tue Mar 13 16:11:45 CST 2018
     */
    int updateByPrimaryKeySelective(PayPlanTaskTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_plan_task_temp
     *
     * @mbg.generated Tue Mar 13 16:11:45 CST 2018
     */
    int updateByPrimaryKey(PayPlanTaskTemp record);
}