package net.chrone.creditpay.mapper;

import java.util.List;
import java.util.Map;

import net.chrone.creditpay.model.PayPlan;
import net.chrone.creditpay.model.PayPlanDCStatisticsDTO;
import net.chrone.creditpay.model.PayPlanExample;
import org.apache.ibatis.annotations.Param;

public interface PayPlanMapper extends ParentMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pay_plan
	 * @mbg.generated  Mon Dec 25 14:44:25 CST 2017
	 */
	long countByExample(PayPlanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pay_plan
	 * @mbg.generated  Mon Dec 25 14:44:25 CST 2017
	 */
	int deleteByExample(PayPlanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pay_plan
	 * @mbg.generated  Mon Dec 25 14:44:25 CST 2017
	 */
	int deleteByPrimaryKey(String planId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pay_plan
	 * @mbg.generated  Mon Dec 25 14:44:25 CST 2017
	 */
	int insert(PayPlan record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pay_plan
	 * @mbg.generated  Mon Dec 25 14:44:25 CST 2017
	 */
	int insertSelective(PayPlan record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pay_plan
	 * @mbg.generated  Mon Dec 25 14:44:25 CST 2017
	 */
	List<PayPlan> selectByExample(PayPlanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pay_plan
	 * @mbg.generated  Mon Dec 25 14:44:25 CST 2017
	 */
	PayPlan selectByPrimaryKey(String planId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pay_plan
	 * @mbg.generated  Mon Dec 25 14:44:25 CST 2017
	 */
	int updateByExampleSelective(@Param("record") PayPlan record, @Param("example") PayPlanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pay_plan
	 * @mbg.generated  Mon Dec 25 14:44:25 CST 2017
	 */
	int updateByExample(@Param("record") PayPlan record, @Param("example") PayPlanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pay_plan
	 * @mbg.generated  Mon Dec 25 14:44:25 CST 2017
	 */
	int updateByPrimaryKeySelective(PayPlan record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pay_plan
	 * @mbg.generated  Mon Dec 25 14:44:25 CST 2017
	 */
	int updateByPrimaryKey(PayPlan record);

	Map<String,Object> getPayPlanByPageCount(PayPlan payPlan);

	List<PayPlan> getPayPlanByPage(PayPlan payPlan);
	
	List<Map<String,Object>> listPayPlayStatistics(PayPlan payPlan);
	
	Map<String,Object> countPayPlayStatistics(PayPlan payPlan);

	Map<String, Object> countPayPlayDCStatistics(PayPlanDCStatisticsDTO dcStatisticsDTO);

	List<PayPlanDCStatisticsDTO> pagePayPlayDCStatistics(PayPlanDCStatisticsDTO dcStatisticsDTO);
}