package net.chrone.creditpay.mapper;

import java.util.List;
import java.util.Map;

import net.chrone.creditpay.model.RegionInfo;
import net.chrone.creditpay.model.RegionInfoExample;
import org.apache.ibatis.annotations.Param;

public interface RegionInfoMapper extends ParentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_region_info
     *
     * @mbg.generated Wed Apr 03 16:40:41 CST 2019
     */
    long countByExample(RegionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_region_info
     *
     * @mbg.generated Wed Apr 03 16:40:41 CST 2019
     */
    int deleteByExample(RegionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_region_info
     *
     * @mbg.generated Wed Apr 03 16:40:41 CST 2019
     */
    int insert(RegionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_region_info
     *
     * @mbg.generated Wed Apr 03 16:40:41 CST 2019
     */
    int insertSelective(RegionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_region_info
     *
     * @mbg.generated Wed Apr 03 16:40:41 CST 2019
     */
    List<RegionInfo> selectByExample(RegionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_region_info
     *
     * @mbg.generated Wed Apr 03 16:40:41 CST 2019
     */
    int updateByExampleSelective(@Param("record") RegionInfo record, @Param("example") RegionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_region_info
     *
     * @mbg.generated Wed Apr 03 16:40:41 CST 2019
     */
    int updateByExample(@Param("record") RegionInfo record, @Param("example") RegionInfoExample example);

	List<Map<String, String>> selectProvinceAll();

	List<Map<String, String>> selectCityInfo(String provCd);

	List<Map<String, String>> selectCountyInfo(String regionCd);
}