package net.chrone.creditpay.mapper;

import java.util.List;
import java.util.Map;

import net.chrone.creditpay.model.RoleInf;
import net.chrone.creditpay.model.RoleInfExample;
import org.apache.ibatis.annotations.Param;

public interface RoleInfMapper extends ParentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_inf
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    long countByExample(RoleInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_inf
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    int deleteByExample(RoleInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_inf
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    int deleteByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_inf
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    int insert(RoleInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_inf
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    int insertSelective(RoleInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_inf
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    List<RoleInf> selectByExample(RoleInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_inf
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    RoleInf selectByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_inf
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    int updateByExampleSelective(@Param("record") RoleInf record, @Param("example") RoleInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_inf
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    int updateByExample(@Param("record") RoleInf record, @Param("example") RoleInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_inf
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    int updateByPrimaryKeySelective(RoleInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_inf
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    int updateByPrimaryKey(RoleInf record);

	List<RoleInf> getRoleInfByPage(Map<String, Object> map);

	int getRoleInfByPageCount(Map<String, Object> map);
}