package net.chrone.creditpay.mapper;

import java.util.List;
import net.chrone.creditpay.model.RootBank;
import net.chrone.creditpay.model.RootBankExample;
import org.apache.ibatis.annotations.Param;

public interface RootBankMapper extends ParentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_root_bank
     *
     * @mbg.generated Fri Nov 17 17:01:57 CST 2017
     */
    long countByExample(RootBankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_root_bank
     *
     * @mbg.generated Fri Nov 17 17:01:57 CST 2017
     */
    int deleteByExample(RootBankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_root_bank
     *
     * @mbg.generated Fri Nov 17 17:01:57 CST 2017
     */
    int deleteByPrimaryKey(String bankNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_root_bank
     *
     * @mbg.generated Fri Nov 17 17:01:57 CST 2017
     */
    int insert(RootBank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_root_bank
     *
     * @mbg.generated Fri Nov 17 17:01:57 CST 2017
     */
    int insertSelective(RootBank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_root_bank
     *
     * @mbg.generated Fri Nov 17 17:01:57 CST 2017
     */
    List<RootBank> selectByExample(RootBankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_root_bank
     *
     * @mbg.generated Fri Nov 17 17:01:57 CST 2017
     */
    RootBank selectByPrimaryKey(String bankNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_root_bank
     *
     * @mbg.generated Fri Nov 17 17:01:57 CST 2017
     */
    int updateByExampleSelective(@Param("record") RootBank record, @Param("example") RootBankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_root_bank
     *
     * @mbg.generated Fri Nov 17 17:01:57 CST 2017
     */
    int updateByExample(@Param("record") RootBank record, @Param("example") RootBankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_root_bank
     *
     * @mbg.generated Fri Nov 17 17:01:57 CST 2017
     */
    int updateByPrimaryKeySelective(RootBank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_root_bank
     *
     * @mbg.generated Fri Nov 17 17:01:57 CST 2017
     */
    int updateByPrimaryKey(RootBank record);
}