package net.chrone.creditpay.mapper;

import java.util.List;
import net.chrone.creditpay.model.ShareImg;
import net.chrone.creditpay.model.ShareImgExample;
import org.apache.ibatis.annotations.Param;

public interface ShareImgMapper extends ParentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_share_img
     *
     * @mbg.generated Wed Sep 19 15:13:02 CST 2018
     */
    long countByExample(ShareImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_share_img
     *
     * @mbg.generated Wed Sep 19 15:13:02 CST 2018
     */
    int deleteByExample(ShareImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_share_img
     *
     * @mbg.generated Wed Sep 19 15:13:02 CST 2018
     */
    int deleteByPrimaryKey(String imgName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_share_img
     *
     * @mbg.generated Wed Sep 19 15:13:02 CST 2018
     */
    int insert(ShareImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_share_img
     *
     * @mbg.generated Wed Sep 19 15:13:02 CST 2018
     */
    int insertSelective(ShareImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_share_img
     *
     * @mbg.generated Wed Sep 19 15:13:02 CST 2018
     */
    List<ShareImg> selectByExample(ShareImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_share_img
     *
     * @mbg.generated Wed Sep 19 15:13:02 CST 2018
     */
    ShareImg selectByPrimaryKey(String imgName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_share_img
     *
     * @mbg.generated Wed Sep 19 15:13:02 CST 2018
     */
    int updateByExampleSelective(@Param("record") ShareImg record, @Param("example") ShareImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_share_img
     *
     * @mbg.generated Wed Sep 19 15:13:02 CST 2018
     */
    int updateByExample(@Param("record") ShareImg record, @Param("example") ShareImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_share_img
     *
     * @mbg.generated Wed Sep 19 15:13:02 CST 2018
     */
    int updateByPrimaryKeySelective(ShareImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_share_img
     *
     * @mbg.generated Wed Sep 19 15:13:02 CST 2018
     */
    int updateByPrimaryKey(ShareImg record);
}