package net.chrone.creditpay.mapper;

import java.util.List;
import net.chrone.creditpay.model.SmsMessageLevel;
import net.chrone.creditpay.model.SmsMessageLevelExample;
import org.apache.ibatis.annotations.Param;

public interface SmsMessageLevelMapper extends ParentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_smsmessage_level
	 * @mbggenerated  Mon Dec 04 18:10:07 CST 2017
	 */
	int countByExample(SmsMessageLevelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_smsmessage_level
	 * @mbggenerated  Mon Dec 04 18:10:07 CST 2017
	 */
	int deleteByExample(SmsMessageLevelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_smsmessage_level
	 * @mbggenerated  Mon Dec 04 18:10:07 CST 2017
	 */int deleteByPrimaryKey(@Param("id") String id,@Param("levelId") Integer levelId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_smsmessage_level
	 * @mbggenerated  Mon Dec 04 18:10:07 CST 2017
	 */
	int insert(SmsMessageLevel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_smsmessage_level
	 * @mbggenerated  Mon Dec 04 18:10:07 CST 2017
	 */
	int insertSelective(SmsMessageLevel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_smsmessage_level
	 * @mbggenerated  Mon Dec 04 18:10:07 CST 2017
	 */List<SmsMessageLevel> selectByExample(SmsMessageLevelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_smsmessage_level
	 * @mbggenerated  Mon Dec 04 18:10:07 CST 2017
	 */int updateByExampleSelective(@Param("record") SmsMessageLevel record,@Param("example") SmsMessageLevelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_smsmessage_level
	 * @mbggenerated  Mon Dec 04 18:10:07 CST 2017
	 */int updateByExample(@Param("record") SmsMessageLevel record,@Param("example") SmsMessageLevelExample example);
	 
	 List<String> getLevelNames(String id);
}