package net.chrone.creditpay.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import net.chrone.creditpay.model.TxRecord;
import net.chrone.creditpay.model.TxRecordExample;

public interface TxRecordMapper extends ParentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tx_record
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    long countByExample(TxRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tx_record
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    int deleteByExample(TxRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tx_record
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    int deleteByPrimaryKey(String recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tx_record
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    int insert(TxRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tx_record
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    int insertSelective(TxRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tx_record
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    List<TxRecord> selectByExample(TxRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tx_record
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    TxRecord selectByPrimaryKey(String recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tx_record
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    int updateByExampleSelective(@Param("record") TxRecord record, @Param("example") TxRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tx_record
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    int updateByExample(@Param("record") TxRecord record, @Param("example") TxRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tx_record
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    int updateByPrimaryKeySelective(TxRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tx_record
     *
     * @mbg.generated Thu Nov 16 10:53:39 CST 2017
     */
    int updateByPrimaryKey(TxRecord record);
    
    Map<String, Object> countTxRecord(TxRecord record);
    
    List<TxRecord> listTxRecordPage(TxRecord txRecord);
}