package net.chrone.creditpay.mapper;

import java.util.List;
import net.chrone.creditpay.model.UpProfitsDetail;
import net.chrone.creditpay.model.UpProfitsDetailExample;
import org.apache.ibatis.annotations.Param;

public interface UpProfitsDetailMapper extends ParentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_up_profits_detail
     *
     * @mbggenerated Tue Nov 21 18:17:01 CST 2017
     */
    int countByExample(UpProfitsDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_up_profits_detail
     *
     * @mbggenerated Tue Nov 21 18:17:01 CST 2017
     */
    int deleteByExample(UpProfitsDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_up_profits_detail
     *
     * @mbggenerated Tue Nov 21 18:17:01 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_up_profits_detail
     *
     * @mbggenerated Tue Nov 21 18:17:01 CST 2017
     */
    int insert(UpProfitsDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_up_profits_detail
     *
     * @mbggenerated Tue Nov 21 18:17:01 CST 2017
     */
    int insertSelective(UpProfitsDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_up_profits_detail
     *
     * @mbggenerated Tue Nov 21 18:17:01 CST 2017
     */
    List<UpProfitsDetail> selectByExample(UpProfitsDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_up_profits_detail
     *
     * @mbggenerated Tue Nov 21 18:17:01 CST 2017
     */
    UpProfitsDetail selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_up_profits_detail
     *
     * @mbggenerated Tue Nov 21 18:17:01 CST 2017
     */
    int updateByExampleSelective(@Param("record") UpProfitsDetail record, @Param("example") UpProfitsDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_up_profits_detail
     *
     * @mbggenerated Tue Nov 21 18:17:01 CST 2017
     */
    int updateByExample(@Param("record") UpProfitsDetail record, @Param("example") UpProfitsDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_up_profits_detail
     *
     * @mbggenerated Tue Nov 21 18:17:01 CST 2017
     */
    int updateByPrimaryKeySelective(UpProfitsDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_up_profits_detail
     *
     * @mbggenerated Tue Nov 21 18:17:01 CST 2017
     */
    int updateByPrimaryKey(UpProfitsDetail record);
    
    List<UpProfitsDetail> listUpProfitsDetail(String profitsId);
}