package net.chrone.creditpay.mapper;

import java.util.List;
import net.chrone.creditpay.model.UserAwardStatus;
import net.chrone.creditpay.model.UserAwardStatusExample;
import org.apache.ibatis.annotations.Param;

public interface UserAwardStatusMapper extends ParentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_award_status
     *
     * @mbg.generated Wed Feb 27 10:11:17 CST 2019
     */
    long countByExample(UserAwardStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_award_status
     *
     * @mbg.generated Wed Feb 27 10:11:17 CST 2019
     */
    int deleteByExample(UserAwardStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_award_status
     *
     * @mbg.generated Wed Feb 27 10:11:17 CST 2019
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_award_status
     *
     * @mbg.generated Wed Feb 27 10:11:17 CST 2019
     */
    int insert(UserAwardStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_award_status
     *
     * @mbg.generated Wed Feb 27 10:11:17 CST 2019
     */
    int insertSelective(UserAwardStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_award_status
     *
     * @mbg.generated Wed Feb 27 10:11:17 CST 2019
     */
    List<UserAwardStatus> selectByExample(UserAwardStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_award_status
     *
     * @mbg.generated Wed Feb 27 10:11:17 CST 2019
     */
    UserAwardStatus selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_award_status
     *
     * @mbg.generated Wed Feb 27 10:11:17 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserAwardStatus record, @Param("example") UserAwardStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_award_status
     *
     * @mbg.generated Wed Feb 27 10:11:17 CST 2019
     */
    int updateByExample(@Param("record") UserAwardStatus record, @Param("example") UserAwardStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_award_status
     *
     * @mbg.generated Wed Feb 27 10:11:17 CST 2019
     */
    int updateByPrimaryKeySelective(UserAwardStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_award_status
     *
     * @mbg.generated Wed Feb 27 10:11:17 CST 2019
     */
    int updateByPrimaryKey(UserAwardStatus record);

	void resetUserStatus(@Param("type") int type);
}