package net.chrone.creditpay.mapper;

import java.util.List;

import net.chrone.creditpay.model.RoleMenu;
import net.chrone.creditpay.model.UserTree;
import net.chrone.creditpay.model.UserTreeExample;
import org.apache.ibatis.annotations.Param;

public interface UserTreeMapper extends ParentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_tree
     *
     * @mbg.generated Sat Jan 05 09:31:16 CST 2019
     */
    long countByExample(UserTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_tree
     *
     * @mbg.generated Sat Jan 05 09:31:16 CST 2019
     */
    int deleteByExample(UserTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_tree
     *
     * @mbg.generated Sat Jan 05 09:31:16 CST 2019
     */
    int deleteByPrimaryKey(@Param("userId") String userId, @Param("lowUserId") String lowUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_tree
     *
     * @mbg.generated Sat Jan 05 09:31:16 CST 2019
     */
    int insert(UserTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_tree
     *
     * @mbg.generated Sat Jan 05 09:31:16 CST 2019
     */
    int insertSelective(UserTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_tree
     *
     * @mbg.generated Sat Jan 05 09:31:16 CST 2019
     */
    List<UserTree> selectByExample(UserTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_tree
     *
     * @mbg.generated Sat Jan 05 09:31:16 CST 2019
     */
    UserTree selectByPrimaryKey(@Param("userId") String userId, @Param("lowUserId") String lowUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_tree
     *
     * @mbg.generated Sat Jan 05 09:31:16 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserTree record, @Param("example") UserTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_tree
     *
     * @mbg.generated Sat Jan 05 09:31:16 CST 2019
     */
    int updateByExample(@Param("record") UserTree record, @Param("example") UserTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_tree
     *
     * @mbg.generated Sat Jan 05 09:31:16 CST 2019
     */
    int updateByPrimaryKeySelective(UserTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_tree
     *
     * @mbg.generated Sat Jan 05 09:31:16 CST 2019
     */
    int updateByPrimaryKey(UserTree record);
    
    void batchAdd(@Param("treeList")List<UserTree> treeList);
}