package net.chrone.creditpay.mapper;

import java.util.List;
import net.chrone.creditpay.model.VerifiedDetail;
import net.chrone.creditpay.model.VerifiedDetailExample;
import org.apache.ibatis.annotations.Param;

public interface VerifiedDetailMapper extends ParentMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_verified_detail
	 * @mbggenerated  Wed Dec 06 19:03:48 CST 2017
	 */
	int countByExample(VerifiedDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_verified_detail
	 * @mbggenerated  Wed Dec 06 19:03:48 CST 2017
	 */
	int deleteByExample(VerifiedDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_verified_detail
	 * @mbggenerated  Wed Dec 06 19:03:48 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_verified_detail
	 * @mbggenerated  Wed Dec 06 19:03:48 CST 2017
	 */
	int insert(VerifiedDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_verified_detail
	 * @mbggenerated  Wed Dec 06 19:03:48 CST 2017
	 */
	int insertSelective(VerifiedDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_verified_detail
	 * @mbggenerated  Wed Dec 06 19:03:48 CST 2017
	 */List<VerifiedDetail> selectByExample(VerifiedDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_verified_detail
	 * @mbggenerated  Wed Dec 06 19:03:48 CST 2017
	 */
	VerifiedDetail selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_verified_detail
	 * @mbggenerated  Wed Dec 06 19:03:48 CST 2017
	 */int updateByExampleSelective(@Param("record") VerifiedDetail record,@Param("example") VerifiedDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_verified_detail
	 * @mbggenerated  Wed Dec 06 19:03:48 CST 2017
	 */int updateByExample(@Param("record") VerifiedDetail record,@Param("example") VerifiedDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_verified_detail
	 * @mbggenerated  Wed Dec 06 19:03:48 CST 2017
	 */
	int updateByPrimaryKeySelective(VerifiedDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_verified_detail
	 * @mbggenerated  Wed Dec 06 19:03:48 CST 2017
	 */
	int updateByPrimaryKey(VerifiedDetail record);

	int countVerifiedDetail(VerifiedDetail verifiedDetail);
	
	List<VerifiedDetail> listVerifiedDetail(VerifiedDetail verifiedDetail);
}